import {automaticRunPredicate} from './research-actor.mjs';
// Unified read-only navigation; decisions still use the original versioned APIs.
function readQueue(db,{kind='all',offset=0,limit=20,topic}={},now=Date.now()){
 if(!['all','model','pipeline','observation','relation','cluster','order'].includes(kind)||!/^\d+$/.test(String(offset))||!/^\d+$/.test(String(limit))||Number(limit)<1||Number(limit)>100||Number(offset)>100000||topic!==undefined&&(typeof topic!=='string'||topic.length>100))throw Error('待办分页参数无效');
 const sources=[
 `SELECT 'model:'||m.id id,'model' kind,m.topic_id topicId,json_extract(t.payload,'$.title') title,'candidate' status,m.created_at at,'模型结果待本人复核' reason,NULL account FROM model_research_runs m LEFT JOIN research_topics t ON t.id=m.topic_id WHERE m.status='candidate' AND coalesce(json_extract(m.payload,'$.subject'),'')!='event-cluster' AND NOT EXISTS(SELECT 1 FROM research_pipeline_event_jobs j WHERE j.run_id=m.id AND json_extract(j.payload,'$.automatic')=1)`,
 `SELECT 'pipeline:'||p.id,'pipeline',p.topic_id,json_extract(p.payload,'$.title'),CASE WHEN m.status='running' AND m.expires_at<${Math.trunc(now)} THEN 'interrupted' WHEN m.status IS NULL AND p.status='preparing' AND NOT EXISTS(SELECT 1 FROM operation_tasks o WHERE o.name='discovery' AND o.paused=0 AND o.lease_until>${Math.trunc(now)} AND o.token=json_extract(p.payload,'$.token')) THEN 'interrupted' ELSE coalesce(m.status,p.status) END,json_extract(p.payload,'$.createdAt'),coalesce(json_extract(m.payload,'$.failure.message'),json_extract(p.payload,'$.reason'),'等待准备或重新核对'),NULL FROM research_pipeline_items p LEFT JOIN model_research_runs m ON m.id=p.run_id WHERE coalesce(json_extract(p.payload,'$.configuration.automatic'),0)!=1 AND (CASE WHEN m.status='running' AND m.expires_at<${Math.trunc(now)} THEN 'interrupted' WHEN m.status IS NULL AND p.status='preparing' AND NOT EXISTS(SELECT 1 FROM operation_tasks o WHERE o.name='discovery' AND o.paused=0 AND o.lease_until>${Math.trunc(now)} AND o.token=json_extract(p.payload,'$.token')) THEN 'interrupted' ELSE coalesce(m.status,p.status) END) IN ('queued','preparing','ready','running','failed','interrupted','invalidated','needs-review')`,
 `SELECT 'observation:'||id,'observation',json_extract(payload,'$.topicId'),json_extract(payload,'$.title'),state,created_at,json_extract(payload,'$.reason'),NULL FROM observation_todos WHERE state!='completed'`,
 `SELECT 'relation:'||r.id,'relation',NULL,coalesce(json_extract(r.payload,'$.packet.input.left.title'),'语义比较')||' → '||coalesce(json_extract(r.payload,'$.packet.input.right.title'),'已有材料'),r.status,json_extract(r.payload,'$.createdAt'),'关联比较待本人核对',NULL FROM semantic_runs r WHERE r.status='candidate' AND NOT ${automaticRunPredicate('r.id')} AND NOT EXISTS(SELECT 1 FROM semantic_decisions d WHERE d.run_id=r.id)`
 ];
 for(const [table,decisions,field,index,label,prefix] of [['material_event_runs','material_event_decisions','$.candidate.decomposition.events','event_index','事项拆分待核对','material-model'],['company_entity_runs','company_entity_decisions','$.candidate.resolution.mentions','mention_index','公司身份待核对','identity-model']])sources.push(`SELECT '${prefix}:'||m.id,'model',m.topic_id,json_extract(t.payload,'$.title'),m.status,json_extract(m.payload,'$.createdAt'),'${label}',NULL FROM ${table} m LEFT JOIN research_topics t ON t.id=m.topic_id WHERE m.status='candidate' AND coalesce(json_extract(m.payload,'$.subject'),'')!='event-cluster' AND NOT EXISTS(SELECT 1 FROM research_pipeline_event_jobs j WHERE j.run_id=m.id AND json_extract(j.payload,'$.automatic')=1) AND EXISTS(SELECT 1 FROM json_each(m.payload,'${field}') e WHERE NOT EXISTS(SELECT 1 FROM ${decisions} d WHERE d.run_id=m.id AND d.${index}=e.key AND d.version=(SELECT max(x.version) FROM ${decisions} x WHERE x.run_id=m.id AND x.${index}=e.key) AND json_extract(d.payload,'$.action')!='reopen'))`);
 sources.push(`SELECT 'cluster:'||b.id,'cluster',NULL,'比较批次 · '||substr(b.id,1,8),'needs-review',json_extract(b.payload,'$.createdAt'),'配对已结束；需在原批次核对分组、冲突与成员版本',NULL FROM semantic_batches b WHERE NOT EXISTS(SELECT 1 FROM research_pipeline_cluster_jobs j WHERE (j.batch_id=b.id OR json_extract(j.payload,'$.correspondenceBatchId')=b.id) AND json_extract(j.payload,'$.automatic')=1) AND json_extract(b.payload,'$.state')!='cancelled' AND EXISTS(SELECT 1 FROM semantic_batch_items i WHERE i.batch_id=b.id) AND NOT EXISTS(SELECT 1 FROM semantic_batch_items i LEFT JOIN semantic_runs r ON r.id=i.run_id WHERE i.batch_id=b.id AND coalesce(r.status,i.status) IN ('queued','running','failed','interrupted','invalidated')) AND NOT EXISTS(SELECT 1 FROM event_cluster_versions c WHERE json_extract(c.payload,'$.batchId')=b.id)`);
 for(const [table,account] of [['market_sim_book_aggressive','aggressive'],['market_sim_book_steady','steady'],['paper_books','scenario']])sources.push(`SELECT 'order:${account}:'||json_extract(o.value,'$.id'),'order',json_extract(o.value,'$.topicId'),json_extract(o.value,'$.symbol')||' · 待批模拟申请',json_extract(o.value,'$.status'),json_extract(o.value,'$.createdAt'),'保存申请不代表批准或成交','${account}' FROM ${table} b,json_each(b.payload,'$.orders') o WHERE json_extract(o.value,'$.status')='pending'`);
 const sql=`WITH queue AS (${sources.join(' UNION ALL ')})`,where=[],args=[];
 if(kind!=='all'){where.push('kind=?');args.push(kind);}if(topic){where.push('topicId=?');args.push(topic);}
 const filter=where.length?' WHERE '+where.join(' AND '):'';
 const counts=Object.fromEntries(db.prepare(sql+' SELECT kind,count(*) n FROM queue GROUP BY kind').all().map(r=>[r.kind,r.n]));
 const total=db.prepare(sql+' SELECT count(*) n FROM queue'+filter).get(...args).n;
 const items=db.prepare(sql+' SELECT * FROM queue'+filter+" ORDER BY CASE kind WHEN 'model' THEN 0 WHEN 'observation' THEN 1 WHEN 'order' THEN 2 WHEN 'relation' THEN 3 ELSE 4 END,at DESC,id LIMIT ? OFFSET ?").all(...args,Number(limit),Number(offset));
 return {items,total,counts,offset:Number(offset),nextOffset:Number(offset)+items.length<total?Number(offset)+items.length:null,policy:'仅整合待办入口，原版本、采纳、回执与审批规则不变'};
}

export function workbenchQueue(db,input,now){if(db.isTransaction)return readQueue(db,input,now);db.exec('BEGIN');try{const result=readQueue(db,input,now);db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}}
