import React,{useEffect,useLayoutEffect,useState} from 'react';
import {Button} from '../major/Primitives';
import {request,time} from '../major/api';
import MaterialityReview from '../major/MaterialityReview';
import {synthesisStates} from '../../shared/event-synthesis-view.mjs';
import '../major/research-dossier.css';
const sections={facts:'事件事实与变化',materiality:'重大性与影响',companies:'公司影响',scenarios:'情景、分歧与风险',conditions:'条件与后续核验'};
const safeLink=url=>{try{const u=new URL(url);return ['http:','https:'].includes(u.protocol)?u.href:null;}catch{return null;}};
export default function EventSynthesisDetail({clusterId,jobId,initialSection='summary',initialEvidence='',initialExpanded={},symbol,revision,onReady,onMember,onCancel,busy}){
 const [job,setJob]=useState(jobId||''),[tab,setTab]=useState(initialSection),[activeEvidence,setActiveEvidence]=useState(initialEvidence),[expanded,setExpanded]=useState(initialExpanded),[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;setLoading(true);setError('');request(`/api/event-clusters/${encodeURIComponent(clusterId)}/research${job?'?job='+encodeURIComponent(job):''}`).then(r=>{if(active){setData(r);if(!job&&r.selected?.id)setJob(r.selected.id);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[clusterId,job,revision]);
 useLayoutEffect(()=>{if(data)onReady?.();},[data]);
 const selected=data?.selected,packet=selected?.packet,input=packet?.input,evidence=input?.evidence||[],run=selected?.run,valid=selected&&['completed','historical'].includes(selected.status)&&run?.status==='adopted',candidate=valid?run.candidate:null;
 const evidenceName=id=>{const e=evidence.find(e=>e.id===id);return e?`${e.sourceName||'保存材料'} · ${e.materialRevision?`材料 v${e.materialRevision}`:'原始记录'}`:'引用记录缺失';};
 function chooseVersion(id){setJob(id);setData(null);setActiveEvidence('');setExpanded({});}
 function openMember(id){onMember(id,{jobId:job,section:tab,evidenceId:activeEvidence,expanded});}
 function disclosure(key){return {open:!!expanded[key],onToggle:e=>{const value=e.currentTarget.open;setExpanded(old=>old[key]===value?old:{...old,[key]:value});}};}
 function section(s){return <section key={s.id}><h3>{sections[s.id]||s.title}</h3>{s.paragraphs.map((p,i)=><p key={i}>{p}</p>)}{s.sourceIds?.length>0&&<div className="dossier-sources">引用：{s.sourceIds.map(id=><Button key={id} onClick={()=>{setActiveEvidence(id);setExpanded(old=>({...old,['e:'+id]:true}));setTab('evidence');}}>{evidenceName(id)}</Button>)}</div>}</section>;}
 return <article className="research-dossier synthesis-detail" aria-label="事件综合详情">
  {error&&<p role="alert">{error} · 当前有效性无法确认，以下如有旧内容仅供回看。</p>}{loading&&<p role="status">正在读取保存的综合版本…</p>}
  {data&&<><p className="dossier-meta">{selected?`综合 v${selected.version} · ${synthesisStates[selected.status]||selected.status} · ${time(selected.updatedAt)}`:'尚未生成综合版本'} · 系统生成，事实待核实</p>
   {selected&&!selected.current&&<p className="m-warning">这份结果不是当前有效结论。{data.overview.reason||'请结合当前输入状态阅读。'}</p>}
   {data.overview.id&&data.overview.id!==selected?.id&&<Button onClick={()=>chooseVersion(data.overview.id)}>查看最新综合状态</Button>}
   <div className="detail-section-tools" role="tablist" aria-label="事件综合分区">{[['summary','综合判断'],['evidence','证据与原文'],['companies','公司依据'],['conditions','条件与缺口'],['history','版本与任务']].map(([id,label])=><Button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)}>{label}</Button>)}</div>
   {!candidate&&<p className="m-note">{selected?.reason||data.overview.reason||'后台仍在处理，尚无可用综合结论。'} 原研究保留；不会随机选一篇代替事件综合。</p>}
   {tab==='summary'&&<>{candidate?.sections.filter(s=>['facts','materiality','scenarios'].includes(s.id)).map(section)}<p className="m-note">综合基于归组 v{selected?.clusterVersion??'—'}、{selected?.memberCount??'—'} 份研究。多篇转载不等于独立证据；保存结论不创建交易。</p></>}
   {tab==='evidence'&&<><p className="m-note">这里展示本版实际输入的不可变材料。原网页可能已变化；不同材料也可能转述同一来源。</p>{evidence.map(e=><details key={e.id} className="synthesis-source" {...disclosure('e:'+e.id)}><summary>{e.sourceName||'来源待核'} · {e.material?.title||e.claim} · v{e.materialRevision||'—'}</summary><p>发布 {time(e.publishedAt)} · 可用 {time(e.availableAt||e.material?.availableAt)} · {e.material?.scope||e.contentScope||'范围待核'}</p><p>原研究 {e.memberTopicId} · 引用 {e.originalEvidenceId}</p>{safeLink(e.url)&&<a href={safeLink(e.url)} target="_blank" rel="noreferrer">打开原网页 ↗</a>}<pre>{e.material?.body||'本版未保存正文，只能使用标题或摘要。'}</pre><Button onClick={()=>openMember(e.memberTopicId)}>查看对应研究当前版本</Button></details>)}{!evidence.length&&<p>暂无保存的综合输入材料。</p>}</>}
   {tab==='companies'&&<>{candidate?.sections.filter(s=>s.id==='companies').map(section)}{symbol&&<p className="m-note">从 {symbol} 进入；保留本事件全部公司与分歧。</p>}{input?.companies.map(c=><section key={c.symbol}><h3>{c.name} · {c.symbol}{c.symbol===symbol?' · 当前查看':''}</h3><p className="m-note">{c.researchVariants.length} 份研究版本。概率、影响金额和证券数量未相加；完整量级与判断保留在对应研究。</p>{c.researchVariants.map((v,i)=><details key={v.topicId+':'+i} {...disclosure('c:'+c.symbol+':'+v.topicId+':'+i)}><summary>研究 v{v.topicVersion} · {v.company.role||'关联角色待核'}</summary><p>{v.company.note||'该研究未记录关系摘要'}</p><Button onClick={()=>openMember(v.topicId)}>打开对应研究当前版本</Button></details>)}</section>)}{!input?.companies.length&&<p>本事件尚无确定的上市证券关联，继续观察。</p>}<MaterialityReview review={candidate?.materialityReviews?{topicVersion:input.topicVersion,checks:candidate.materialityReviews,targets:input.materialityReview.targets}:null} evidence={evidence}/></>}
   {tab==='conditions'&&<>{candidate?.sections.filter(s=>s.id==='conditions').map(section)}<h3>仍缺哪些依据</h3>{candidate?.missingEvidence.map((m,i)=><p key={i}>{m}</p>)}<p className="m-note">这里是研究条件，不是经报价、账户和数量校验后的交易方案；最终买卖仍由本人决定。</p></>}
   {tab==='history'&&<><h3>已保存版本</h3>{data.history.map(h=><Button key={h.id} aria-pressed={selected?.id===h.id} onClick={()=>chooseVersion(h.id)}>v{h.version} · {synthesisStates[h.status]||h.status} · {h.memberCount} 份研究</Button>)}<h3>本版冻结的研究输入</h3>{input?.eventSynthesis.members.map(m=><details key={m.topicId} {...disclosure('m:'+m.topicId)}><summary>{m.title} · 研究 v{m.topicVersion}</summary><p>{m.priorJudgment.summary}</p>{m.priorJudgment.dossier?.sections?.map(s=><section key={s.id}><h4>{sections[s.id]||s.title}</h4>{s.paragraphs.map((p,i)=><p key={i}>{p}</p>)}</section>)}<Button onClick={()=>openMember(m.topicId)}>查看该研究当前版本</Button></details>)}<details {...disclosure('calls')}><summary>任务与调用记录 · {selected?.attemptCount||0} 次</summary><p>模型 {selected?.model||run?.model||'尚未调用'} · 输入 {packet?.inputHash||'尚未形成'}</p>{selected?.attemptRuns.map(a=><p key={a.id}>{time(a.createdAt)} · {synthesisStates[a.status]||({candidate:'结果待保存',adopted:'系统结果已保存',failed:'调用失败',interrupted:'调用中断'})[a.status]||a.status} · {a.failure?.message||a.id}</p>)}{selected&&['queued','running'].includes(selected.status)&&<Button disabled={busy} onClick={()=>onCancel(selected.id)}>取消本版任务</Button>}</details></>}
  </>}
 </article>;
}
