import './semantic-events.css';
import ClusterReplacement,{ReplacementEvidence} from './ClusterReplacement';
import React,{useEffect,useState} from 'react';
import {Button} from '../major/Primitives';
import {request,time} from '../major/api';
import {semanticKinds,semanticScopeLabels} from '../../shared/semantic-labels.mjs';
import {clusterGroupStates,clusterPairStates,clusterMemberVersion} from '../../shared/event-cluster-labels.mjs';
const target=group=>({clusterId:group.overlaps[0]?.id||'',version:group.overlaps[0]?.version||0});
function PairEvidence({pair,onResult}){
 const b=pair.basis;
 return <article className="source-item"><strong>{pair.left.title} ↔ {pair.right.title}</strong><p>{semanticKinds[b.comparison.relation]} · {b.model} · {b.decisionVersion?`成对决定 v${b.decisionVersion}`:"尚无成对人工决定"}</p><p>{b.comparison.reason}</p><blockquote>左侧：{b.comparison.left.quote}</blockquote><blockquote>右侧：{b.comparison.right.quote}</blockquote>{b.comparison.missingEvidence.map((m,i)=><p className="m-note" key={i}>{m}</p>)}{onResult&&<Button onClick={()=>onResult(b.runId)}>打开原比较</Button>}</article>;
}
export function ClusterCandidate({group,batchId,busy,onSave,onResult}){
 const [form,setForm]=useState(()=>({title:group.overlaps[0]?.title||group.members[0].title.slice(0,140),note:'',previewHash:group.hash,...target(group),requestId:crypto.randomUUID()}));
 const stale=form.previewHash!==group.hash;
 return <article className="source-item" aria-label={`事件簇候选 ${group.indices.map(n=>n+1).join('、')}`}><h4>{clusterGroupStates[group.state]} · {group.members.length} 份输入</h4><ul>{group.members.map(m=><li key={m.id}>{m.title} · {clusterMemberVersion(m)} · {semanticScopeLabels[m.contentScope]}</li>)}</ul>
 {group.overlaps.map(c=><p key={c.id}>已有事件簇：{c.title} · v{c.version} · {c.id}</p>)}
 {group.overlaps.length>1&&<p className="m-warning">成员分属多个已确认事件簇，不能自动合并；需先核对原簇及归档决定。</p>}
 {!!group.missing.length&&<p className="m-warning">此批次缺少原簇成员：{group.missing.map(m=>m.title).join('、')}。新批次需包含原簇全部成员的当前版本；材料已修订时，可在下方选择原簇并核对事项延续。</p>}
 <details open={group.state==='conflict'}><summary>逐对核对 · {group.pairs.length} 对</summary>{group.pairs.map(p=><div className="source-item" key={p.ordinal}><strong>输入 {p.left+1} ↔ {p.right+1} · {clusterPairStates[p.status]}</strong><p>{semanticKinds[p.relation]||'尚无有效判断'}</p>{p.basis&&<PairEvidence pair={{left:group.members[group.indices.indexOf(p.left)],right:group.members[group.indices.indexOf(p.right)],basis:p.basis}} onResult={onResult}/>}</div>)}</details>
 {group.state==='conflict'&&<p className="m-warning">关系链不足以证明整组是同一事件。缺失、冲突或失效的配对需先重新比较核对；本组不可确认。</p>}
 {group.canSave&&<form className="m-form" onSubmit={e=>{e.preventDefault();if(busy||stale)return;onSave({batchId,groupId:group.id,...form});}}><label>事件簇名称<input disabled={busy} required maxLength={140} value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))}/></label><label>归组核对说明<textarea disabled={busy} required maxLength={1200} value={form.note} onChange={e=>setForm(v=>({...v,note:e.target.value}))} placeholder="说明是否确为同一交易、产品或政策，以及仍未核实的事实。"/></label>{stale&&<p className="m-warning">预览已变化，输入保留；请重新核对当前组内比较。</p>}{stale&&<Button type="button" disabled={busy} onClick={()=>setForm(v=>({...v,previewHash:group.hash,...target(group),requestId:crypto.randomUUID()}))}>载入当前预览</Button>}<Button primary type="submit" disabled={busy||stale||!form.title.trim()||!form.note.trim()}>{form.clusterId?'确认事件簇新版本':'确认建立事件簇'}</Button></form>}
 </article>;
}
export function ClusterRecord({record,onResult}){
 return <section aria-label="已保存事件簇"><h3>{record.title} · v{record.version} · {record.status==='archived'?'已归档':record.health.current?'依据仍匹配':'依据需复核'}</h3><p>稳定 ID：{record.id}</p><p className={record.health.current?'m-note':'m-warning'}>{record.health.reason}</p><p>{record.actor?.kind==='system'?'系统归组 · 事实仍未核实':'本人确认归组'}</p><p>首次保存 {time(record.confirmedAt)} · 本版保存 {time(record.updatedAt)}</p><p>{record.note}</p><ul>{record.members.map(m=><li key={m.id}>{m.title} · {clusterMemberVersion(m)} · {semanticScopeLabels[m.contentScope]}</li>)}</ul><details><summary>本版冻结的全部比较依据 · {record.pairs.length} 对</summary>{record.pairs.map(p=><PairEvidence key={p.basis.runId} pair={p} onResult={onResult}/>)}</details><details><summary>事件簇历史 · {record.history.length} 版</summary>{record.history.map(h=><article className="source-item" key={h.version}><strong>v{h.version} · {h.status==='archived'?'归档':h.actor?.kind==='system'?'系统归组':'本人确认'} · {time(h.updatedAt)}</strong><p>{h.title} · {h.note}</p><ReplacementEvidence replacement={h.replacement}/><ul>{h.members.map(m=><li key={m.id}>{m.title} · {clusterMemberVersion(m)}</li>)}</ul><details><summary>此版比较依据</summary>{h.pairs.map(p=><PairEvidence key={p.basis.runId} pair={p} onResult={onResult}/>)}</details><small>快照指纹 {h.snapshotHash}</small></article>)}</details></section>;
}
export default function EventClusters({batchId=null,initialClusterId='',onBack,onResult}){
 const [preview,setPreview]=useState(null),[data,setData]=useState(null),[selected,setSelected]=useState(initialClusterId),[record,setRecord]=useState(null),[refresh,setRefresh]=useState(0),[actionBusy,setBusy]=useState(false),[replacementBusy,setReplacementBusy]=useState(false),[error,setError]=useState(''),[archiveNotes,setArchiveNotes]=useState({});
 const busy=actionBusy||replacementBusy;
 const [q,setQ]=useState(''),[query,setQuery]=useState(''),[offset,setOffset]=useState(0),[status,setStatus]=useState('active');
 useEffect(()=>{let live=true;Promise.all([request(`/api/event-clusters?${new URLSearchParams({q:query,offset:String(offset),status})}`),batchId?request(`/api/semantic-batches/${batchId}/clusters`):Promise.resolve(null),selected?request(`/api/event-clusters/${selected}`):Promise.resolve(null)]).then(([d,p,r])=>{if(live){setData(d);setPreview(p);setRecord(r);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[batchId,selected,refresh,query,offset,status]);
 const act=async fn=>{if(busy)return;setBusy(true);setError('');try{await fn();setRefresh(n=>n+1);}catch(e){setError(e.message);}finally{setBusy(false);}};
 const current=record?.id===selected?record:null;
 const archiveKey=current?`${current.id}:${current.version}`:'',archiveNote=archiveNotes[archiveKey]||'',openResult=busy?undefined:onResult;
 return <section className="semantic-events" aria-label="事件身份与聚类"><div className="event-actions"><Button disabled={busy} onClick={onBack}>返回</Button><Button disabled={busy} onClick={()=>{setError('');setRefresh(n=>n+1);}}>刷新事件簇依据</Button></div><h3>事件身份与聚类</h3><p>自动模式在全部组内配对一致后保存系统事件簇；手动批次仍由本人核对确认。重复、进展和反向变化可提出同一事件候选；相关、类比和未知不自动归组。确认不改写研究证据、不增加独立来源数，也不生成交易。</p>{error&&<p className="m-warning" role="alert">{error}</p>}
 {preview&&<section aria-label="批次聚类候选"><p>{preview.inputCount} 份输入 · {preview.groups.length} 个候选范围（含未归组单项）。只覆盖此批次，不代表全库事件已分清；人工尚未确认的模型结果同样明确标为候选。</p>{preview.groups.map(g=><React.Fragment key={g.id}><ClusterCandidate group={g} batchId={batchId} busy={busy} onResult={openResult} onSave={input=>act(async()=>{const saved=await request('/api/event-clusters','POST',input);setSelected(saved.id);})}/>{g.state==='ready'&&<ClusterReplacement key={`${g.id}:${current?.id||''}`} record={current} group={g} batchId={batchId} busy={busy} onWorkingChange={setReplacementBusy} onSaved={saved=>{setSelected(saved.id);setRefresh(n=>n+1);}}/>}</React.Fragment>)}<details><summary>相关、不同、未知或未完成配对 · {preview.unmergedPairs.length} 对</summary>{preview.unmergedPairs.map(p=><p key={p.ordinal}>输入 {p.left+1} ↔ {p.right+1} · {clusterPairStates[p.status]} · {semanticKinds[p.relation]||'尚无判断'} {p.runId&&onResult&&<Button disabled={busy} onClick={()=>onResult(p.runId)}>核对原比较</Button>}</p>)}</details></section>}
 {!batchId&&<p className="m-note">手动新建或扩充事件簇，可从“持久比较批次”选择已保存批次，再点击“核对事件簇”。扩充时需把原簇所有成员的当前版本加入同一批次。</p>}
 <h3>已保存事件簇</h3><form className="m-form" onSubmit={e=>{e.preventDefault();if(busy)return;setQuery(q);setOffset(0);setRefresh(n=>n+1);}}><label>搜索事件簇名称<input disabled={busy} maxLength={140} value={q} onChange={e=>setQ(e.target.value)}/></label><label>事件簇状态<select disabled={busy} value={status} onChange={e=>{setStatus(e.target.value);setOffset(0);}}><option value="active">活动</option><option value="archived">已归档</option><option value="all">全部</option></select></label><Button disabled={busy} type="submit">查询事件簇</Button></form>
 <div className="source-news-list">{data?.items.map(c=><button key={c.id} disabled={busy} aria-pressed={selected===c.id} onClick={()=>setSelected(c.id)}><strong>{c.title}</strong><span>{c.actor?.kind==='system'?'系统归组':'本人确认'} · v{c.version} · {c.memberCount} 份输入 · {c.status==='archived'?'已归档':c.health.current?'依据匹配':'需复核'}</span></button>)}</div>{data&&<div className="source-pagination"><span>{data.total} 个事件簇 · 第 {Math.floor(offset/20)+1} 页</span><Button disabled={busy||!offset} onClick={()=>setOffset(n=>n-20)}>上一页事件簇</Button><Button disabled={busy||offset+20>=data.total} onClick={()=>setOffset(n=>n+20)}>下一页事件簇</Button></div>}
 {current&&<><ClusterRecord record={current} onResult={openResult}/>{current.status==='active'&&<form className="m-form" onSubmit={e=>{e.preventDefault();act(async()=>{await request(`/api/event-clusters/${current.id}/archive`,'POST',{version:current.version,note:archiveNote,requestId:crypto.randomUUID()});setArchiveNotes(notes=>{const next={...notes};delete next[archiveKey];return next;});});}}><label>归档原因<textarea disabled={busy} required maxLength={1200} value={archiveNote} onChange={e=>setArchiveNotes(notes=>({...notes,[archiveKey]:e.target.value}))}/></label><p className="m-note">归档保留全部历史，释放当前成员分配；不会删除材料、研究或比较。</p><Button type="submit" disabled={busy||!archiveNote.trim()}>归档此事件簇</Button></form>}</>}
 </section>;
}
