import React,{useEffect,useRef,useState} from 'react';
import {Button} from '../major/Primitives';
import {evaluationVerdicts} from '../../shared/evaluation-review.mjs';
import {OUTCOMES} from '../../shared/claims.mjs';
import {clusterReviews} from '../../shared/forward-review.mjs';
import {request,time} from '../major/api';
const statuses={running:'调用中',candidate:'待核对候选',adopted:'已采纳',failed:'失败',cancelled:'已取消',interrupted:'已中断'};
function Counts({title,values,names={}}){return <div><strong>{title}</strong>{Object.keys(values).length?<ul>{Object.entries(values).map(([k,n])=><li key={k}>{names[k]||k}：{n}</li>)}</ul>:<p>无</p>}</div>;}
const local=v=>{const d=new Date(v);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
export default function ForwardWindows({baselines}){
 const [catalog,setCatalog]=useState(null),[report,setReport]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[baselineId,setBaselineId]=useState(baselines[0]?.id||''),[title,setTitle]=useState(''),[start,setStart]=useState(local(Date.now()-86400000)),[end,setEnd]=useState(local(Date.now()));
 const lock=useRef(false),pending=useRef(null),live=useRef(true);
 async function perform(fn){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn();}catch(e){if(live.current)setError(e.message);}finally{lock.current=false;if(live.current)setBusy(false);}}
 const refresh=()=>perform(async()=>{const c=await request('/api/forward-windows');if(live.current)setCatalog(c);});
 useEffect(()=>{live.current=true;refresh();return()=>{live.current=false;};},[]);
 async function freeze(e){e.preventDefault();await perform(async()=>{const data={baselineId,title:title.trim(),start:new Date(start).toISOString(),end:new Date(end).toISOString()},key=JSON.stringify(data);if(pending.current?.key!==key)pending.current={key,data:{...data,requestId:crypto.randomUUID()}};const r=await request('/api/forward-windows','POST',pending.current.data);if(live.current){setReport(r);pending.current=null;}const c=await request('/api/forward-windows');if(live.current)setCatalog(c);});}
 const inspect=id=>perform(async()=>{const r=await request('/api/forward-windows/'+id);if(live.current)setReport(r);});
 return <section aria-label="固定窗口汇总"><h4>固定窗口汇总</h4><p>包含指定基线和调用时间段内的全部已登记调用，包括失败、排除和未解决项。复核版本截至本次冻结时刻；后续更正不会改写旧报告。没有登记的新闻或调用不在统计范围。</p>{error&&<p role="alert" className="m-warning">{error}</p>}
 <Button disabled={busy} onClick={refresh}>刷新窗口报告</Button>
 <form className="m-form" onSubmit={freeze}><fieldset disabled={busy}><label>窗口报告名称<input required maxLength={100} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>窗口基线<select required value={baselineId} onChange={e=>setBaselineId(e.target.value)}><option value="">请选择</option>{baselines.map(b=><option key={b.id} value={b.id}>{b.title} · {time(b.frozenAt)}</option>)}</select></label><label>调用窗口开始（本机时间）<input required type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label>调用窗口结束（不含，本机时间）<input required type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label><p>窗口不得早于所选基线，结束不得在未来。最多5000次调用，超限会拒绝，不能截取成功项。</p><Button primary type="submit">冻结完整窗口</Button></fieldset></form>
 {catalog&&<><p>已保存 {catalog.total} 份报告，显示最近 {catalog.reports.length} 份；更早报告仍保留，可按ID读取。</p>{catalog.reports.map(r=><article className="evaluation-case" key={r.id}><strong>{r.title}</strong><p>{time(r.start)} 至 {time(r.end)} · {r.summary.calls} 次调用</p><Button disabled={busy} onClick={()=>inspect(r.id)}>查看窗口 {r.id.slice(0,8)}</Button></article>)}</>}
 {report&&<article className="evaluation-case" aria-label="冻结窗口报告"><h4>{report.title}</h4><p>调用窗口 [{report.start}, {report.end})<br/>复核版本截至 {report.asOf}<br/>报告指纹 {report.hash}</p><p>全部调用 {report.summary.calls} · 输入准入 {report.summary.inputEligible} · 输入排除 {report.summary.inputExcluded} · 执行依据通过 {report.summary.executionVerified}</p><p>已知簇 {report.summary.clusters.known} · 同簇后续调用 {report.summary.clusters.repeatCalls} · 未知簇调用 {report.summary.clusters.unknownCalls}。簇数量不证明事件独立。</p><p>冻结主张 {report.summary.claims.total} · 有单条描述误差 {report.summary.claims.withDescriptiveError} · 未评分 {report.summary.claims.withoutDescriptiveError}</p><details><summary>状态、标签、结局与排除明细</summary><Counts title="调用状态" values={report.summary.statuses} names={statuses}/><Counts title="重大性复核" values={report.summary.labels} names={{...evaluationVerdicts,unreviewed:"未复核"}}/><Counts title="事件簇复核" values={report.summary.clusterReviews} names={{...clusterReviews,unreviewed:"未复核"}}/><Counts title="主张结局" values={report.summary.claims.outcomes} names={{...OUTCOMES,unregistered:"尚未登记"}}/><Counts title="输入排除原因（可重复）" values={report.summary.exclusionReasons}/><Counts title="未评分原因（可重复）" values={report.summary.claims.unscoredReasons}/><p>每次调用的完整输入及引用随报告保存在本机，以下列出调用与复核版本。</p>{report.rows.map(r=><p key={r.capture.runId}>{r.capture.topicTitle} · {r.capture.runId}<br/>{statuses[r.capture.modelStatus]||"未知状态"} · 复核 v{r.review.version} · {r.capture.inputEligibility.reasons.join('；')||'输入结构准入通过'}</p>)}</details><ul>{report.limitations.map(t=><li key={t}>{t}</li>)}</ul></article>}
 </section>;
}
