import ActivitySidebar from './ActivitySidebar';
import {createDeferredView} from '../DeferredView';
const NewsLibrary=createDeferredView(()=>import('../major/NewsLibrary'),{title:'完整新闻库'});
import React,{useEffect,useRef,useState} from 'react';
import DatasetIdentity from './DatasetIdentity';
const EvaluationReview=createDeferredView(()=>import('./EvaluationReview'),{title:'研究评估',mode:'dialog'});
const MarketSimulation=createDeferredView(()=>import('./MarketSimulation'),{title:'市场模拟',mode:'dialog'});
const ObservationInbox=createDeferredView(()=>import('./ObservationInbox'),{title:'观察待办',mode:'dialog'});
const DataDesk=createDeferredView(()=>import('../terminal/DataDesk'),{title:'数据源',mode:'dialog'});
import '../terminal/terminal.css';
import {Button,Modal,ErrorContext} from '../major/Primitives';
import {request,time} from '../major/api';
import {NewTopic,AddEvidence,CompanyForm,Rulebook,VerifyEvidence} from '../major/ResearchForms';
const TopicDetail=createDeferredView(()=>import('../major/TopicDetail'),{title:'研究、证据与历史追踪'});
const NewsInspector=createDeferredView(()=>import('../major/NewsInspector'),{title:'事件增量核验'});
import '../major/major.css';
import '../major/research-materials.css';
import MarketPanel from './MarketPanel';
const CompanyDossier=createDeferredView(()=>import('./CompanyDossier'),{title:'公司研究',mode:'dialog'});
import {readResearchContext,researchContexts} from './research-context';
import EventBrief from './EventBrief';
import {eventProfile,eventGroups} from './event-view';
import {AccountStrip,DecisionQueue,Holdings} from './PaperPanels';
import {Proposal,Decision,Parameters,Review,Records} from './PaperForms';
import './integrated.css';
import './workbench-layout.css';
import './workspace.css';
import './event-continuity.css';
import {orderedTopics} from './decision-model';
import {HealthStrip,Operations} from './Operations';
const EventContinuity=createDeferredView(()=>import('./EventContinuity'),{title:'事件追踪',mode:'dialog'});
export default function IntegratedWorkbench(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[selected,setSelected]=useState(()=>new URLSearchParams(window.location.search).get('topic')||''),[stock,setStock]=useState(()=>readResearchContext(new URLSearchParams(window.location.search).get('topic')).symbol),[dialog,setDialog]=useState(null),[tab,setTab]=useState('evidence'),[archived,setArchived]=useState(false),[eventScope,setEventScope]=useState('all'),[search,setSearch]=useState(''),[eventType,setEventType]=useState('all'),[focus,setFocus]=useState('research'),[radarTab,setRadarTab]=useState('research'),[researchStage,setResearchStage]=useState('ready'),[marketNavigation,setMarketNavigation]=useState({account:'aggressive',order:'',nonce:0}),[recent,setRecent]=useState(()=>researchContexts().map(r=>r.id).reverse());
 const active=useRef(true),sequence=useRef(0),inFlight=useRef(false),readFlight=useRef(false);
 async function load(){if(inFlight.current||readFlight.current)return;readFlight.current=true;const seq=++sequence.current;try{const result=await request('/api/data');if(active.current&&seq===sequence.current){setData(result);setError('');}}catch(e){if(active.current&&seq===sequence.current)setError(e.message);}finally{readFlight.current=false;}}
 useEffect(()=>{active.current=true;void load();const timer=setInterval(load,15000);return()=>{active.current=false;sequence.current++;clearInterval(timer);};},[]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(timer);},[notice]);
 async function mutate(path,method,payload){if(inFlight.current)return null;inFlight.current=true;sequence.current++;setBusy(true);setError('');try{const r=await request(path,method,payload);if(active.current){setData(r);setNotice('已保存到本机，历史版本保留');}return r;}catch(e){if(active.current)setError(e.message);return null;}finally{inFlight.current=false;if(active.current)setBusy(false);}}
 const topics=data?.research?.topics||[],topic=topics.find(t=>t.id===selected)||topics[0],watch=data?.watchlist||[],book=data?.paper,inbox=data?.research?.inbox||[],workflow=data?.workflow?.find(x=>x.topicId===topic?.id);
 useEffect(()=>{if(!topics.length)return;const target=topics.find(t=>t.id===selected)||topics.find(t=>t.origin==='recent-data-test')||topics[0];if(target.id!==selected){setSelected(target.id);setStock(target.companies[0]?.symbol||'');}else if(!stock)setStock(target.companies[0]?.symbol||'');},[topics,selected,stock]);
 const filteredTopics=orderedTopics(topics,data?.workflow||[]).filter(t=>(eventType==='all'||eventProfile(t).id===eventType)&&(!search||[t.title,t.label,...t.companies.flatMap(c=>[c.name,c.symbol])].join(' ').toLowerCase().includes(search.trim().toLowerCase()))).filter(t=>t.status===(archived?'archived':'active')&&(researchStage==='all'||t.origin!=='news-candidate'||t.dossier||t.id===selected)&&(eventScope==='all'||eventScope==='recent'&&t.origin==='recent-data-test'||eventScope==='attachments'&&t.origin==='attachment-research'||eventScope==='examples'&&t.origin==='retrospective-case'));
 function choose(t){const context=readResearchContext(t.id);setSelected(t.id);setStock(context.symbol||t.companies[0]?.symbol||'');setRecent(v=>[...new Set([t.id,selected,...v].filter(Boolean))].slice(0,8));const u=new URL(window.location.href);u.searchParams.set('topic',t.id);u.searchParams.set('range',context.range);u.searchParams.set('view',context.view);window.history.pushState(null,'',u);}
 useEffect(()=>{function restore(){const id=new URLSearchParams(window.location.search).get('topic');const t=topics.find(t=>t.id===id);if(t){setSelected(t.id);setStock(readResearchContext(t.id).symbol||t.companies[0]?.symbol||'');}}window.addEventListener('popstate',restore);return()=>window.removeEventListener('popstate',restore);},[topics]);
 useEffect(()=>{if(!topic)return;const u=new URL(window.location.href);if(u.searchParams.get('topic')!==topic.id){u.searchParams.set('topic',topic.id);window.history.replaceState(null,'',u);}},[topic?.id]); function open(value){setError('');setDialog(value);}
 function proposal(symbol,side='buy',target=topic){if(target){setSelected(target.id);open({type:'proposal',symbol,side,topicId:target.id});}}
 function sell(p){proposal(p.symbol,'sell',topics.find(t=>t.id===p.topicId));}
 const openCompany=symbol=>{setStock(symbol);open({type:'dossier',symbol});};
 const close=()=>setDialog(null),dtopic=topics.find(t=>t.id===dialog?.topicId)||topic;
 return <ErrorContext.Provider value={error}><main className={`integrated major v6 v7 v8 focus-${focus}`} aria-label="全球重大事件交易工作台"><header className="i-header"><div className="m-brand"><img src="/signal.svg" alt=""/><strong>信号猎手</strong><span>Signal Hunter</span><b className="i-live-dot">{data?.runtime?.offline?'DEMO':'LOCAL'}</b></div><div className="i-header-actions"><Button disabled={!data} onClick={()=>open({type:'settings'})}>设置</Button><Button primary disabled={!data} onClick={()=>open({type:'new'})}>＋ 新建主题</Button></div></header>
 {data?.runtime?.offline&&<div className="demo-banner" role="status">离线演示 · 事件、新闻与曲线均为虚构；证券代码仅作界面示例。操作只保存在独立演示库。</div>}
 <DatasetIdentity runtime={data?.runtime} count={topics.length}/>
 <nav className="workspace-nav" aria-label="主导航">{[['research','工作台'],['portfolio','组合'],['evaluation','评估']].map(([k,v])=><button key={k} aria-pressed={focus===k} onClick={()=>setFocus(k)}>{v}</button>)}</nav>
 <HealthStrip data={data} onOpen={()=>open({type:'operations'})}/>
 {error&&<div className="i-error" role="alert">{error}<Button onClick={load}>刷新连接</Button></div>}
 <div className={`i-main workspace-main ${focus==='research'?'':'workspace-wide'}`}>
 {focus==='research'?<><aside className="i-radar i-panel"><nav className="inbox-tabs" aria-label="收件箱视图"><button aria-pressed={radarTab==='research'} onClick={()=>setRadarTab('research')}>研究</button><button aria-pressed={radarTab==='news'} onClick={()=>setRadarTab('news')}>新闻收件箱</button></nav>{radarTab==='news'?<NewsLibrary compact onOpen={news=>open({type:'news',newsId:news.id,news})}/>:<><div className="i-section-head"><h2>事件研究</h2><select aria-label="事件研究范围" value={eventScope} onChange={e=>setEventScope(e.target.value)}><option value="all">全部研究</option><option value="recent">本轮实测</option><option value="attachments">附件研判</option><option value="examples">既有案例</option></select><button className="i-text-button" onClick={()=>setArchived(!archived)}>{archived?'回到在研':'归档'}</button></div><div className="v6-radar-filters"><select aria-label="研究成熟度" value={researchStage} onChange={e=>setResearchStage(e.target.value)}><option value="ready">已形成研判 / 当前研究</option><option value="all">全部草稿与研究</option></select><input aria-label="搜索事件或公司" placeholder="搜索事件、公司或代码…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="事件类型" value={eventType} onChange={e=>setEventType(e.target.value)}><option value="all">全部事件类型</option>{eventGroups.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="i-topics">{filteredTopics.map(t=>{const w=data.workflow?.find(w=>w.topicId===t.id);return <button key={t.id} className={`i-topic ${topic?.id===t.id?'selected':''}`} onClick={()=>choose(t)}><div><span>{t.label}</span><em className={w?.priority==='优先复核'?'amber':'i-muted'}>{w?.priorityReason||'待研判'}</em><small>v{t.version}</small></div><h3>{t.title}</h3><p>{t.summary}</p><footer><span>{t.coverage.support} 支持 / {t.coverage.against} 反证 / {t.coverage.pending} 待核</span><b>{t.companies.length} 公司{w?.positionSymbols?.length?` · ${w.positionSymbols.length} 持仓`: ''}</b></footer></button>;})}{!filteredTopics.length&&<p className="i-note">没有匹配的研究事件。可清空搜索或选择其他类型。</p>}</div><div className="v10-library-button"><Button onClick={()=>setRadarTab('news')}>打开统一新闻收件箱</Button><Button onClick={()=>open({type:'event-continuity'})}>关联事件与比较</Button></div></>}</aside>
 <section className="i-research i-panel" aria-label="事件研判与行情"><nav className="research-tabs" aria-label="最近研究">{[topic?.id,...recent.filter(id=>id!==topic?.id)].filter(Boolean).slice(0,8).map(id=>{const t=topics.find(t=>t.id===id);return t?<button key={id} aria-pressed={id===topic?.id} onClick={()=>choose(t)} title={t.title}>{t.title}</button>:null;})}</nav>{topic?<><EventBrief topic={topic} workflow={workflow} onDetail={value=>{setTab(value);open({type:'detail'});}} onEvidence={()=>open({type:'evidence'})} onCompany={()=>open({type:'company'})}/><MarketPanel key={topic.id} topic={topic} topics={topics} book={book} watch={watch} selected={stock} onSelect={setStock} onCompany={openCompany} onPropose={s=>proposal(s)} onManage={()=>open({type:'data'})} checks={data?.checks||{}} busy={busy} onRefresh={async symbols=>{const r=await mutate('/api/daily/refresh','POST',{symbols});if(r){const failed=symbols.filter(s=>r.checks['daily:'+s]?.state==='error');setNotice(failed.length?`${failed.length} 家公司日线更新有误，保留可用缓存`:'日线已检查，数据时间以各图为准');}}}/></>:<p className="i-note">{data?'尚无研究事件。点击右上角「＋ 新建主题」开始，或从新闻建立草稿。':'等待研究数据…'}</p>}</section>
 </>:<section className="workspace-primary i-panel">{data&&(focus==='portfolio'?<><MarketSimulation key={marketNavigation.nonce} embedded initialAccount={marketNavigation.account} initialOrder={marketNavigation.order} data={data} onClose={()=>setFocus('research')}/><details className="advanced-scenario"><summary>高级：结构演练账本（独立于激进 / 稳健账户）</summary>{book&&<><AccountStrip book={book}/><DecisionQueue book={book} topics={topics} selectedTopic={topic?.id} workflow={data.workflow||[]} initialScope="all" onTopic={(id,symbol)=>{const t=topics.find(t=>t.id===id);if(t)choose(t);if(symbol)setStock(symbol);}} onReview={p=>open({type:'review',symbol:p.symbol})} onDecision={o=>open({type:'decision',orderId:o.id})} onParams={()=>open({type:'params'})} onRecords={()=>open({type:'records'})}/><Holdings book={book} selectedTopic={topic?.id} selectedSymbol={stock} topics={topics} watch={watch} onSelect={p=>{const t=topics.find(t=>t.id===p.topicId);if(t)choose(t);setStock(p.symbol);}} onSell={sell} onReview={p=>open({type:'review',symbol:p.symbol})} onRecords={()=>open({type:'records'})}/></>}</details></>:<EvaluationReview embedded data={data} onClose={()=>setFocus('research')}/>)}</section>}
 <ActivitySidebar instanceId={data?.runtime?.instance?.id} topicId={topic?.id} onOperations={()=>open({type:'operations'})} onRecord={item=>{const t=topics.find(t=>t.id===item.topicId);if(t){choose(t);setFocus('research');setTab('materials');open({type:'detail'});}else if(item.newsId){void request(`/api/news/${item.newsId}`).then(news=>open({type:'news',newsId:news.id,news})).catch(e=>setError(e.message));}else open({type:'operations'});}} onTodo={item=>{const t=topics.find(t=>t.id===item.topicId);if(t)choose(t);if(item.kind==='model'){setFocus('research');setTab('materials');open({type:'detail'});}else if(item.kind==='observation')open({type:'observations',todoId:item.id.slice('observation:'.length)});else if(['relation','cluster'].includes(item.kind))open({type:'event-continuity',semantic:true});else if(item.kind==='order'&&item.account!=='scenario'){setMarketNavigation(n=>({account:item.account,order:item.id.split(':').at(-1),nonce:n.nonce+1}));setFocus('portfolio');}else if(item.kind==='order')open({type:'decision',orderId:item.id.split(':').at(-1)});else open({type:'operations',pipelineId:item.id.slice('pipeline:'.length)});}}/>
 </div>
 <footer className="i-footer"><span>研究与模拟分离 · 版本与原始记录保留</span><span>{data?.autoWatch?.deferred?.length?`关注待处理 ${data.autoWatch.deferred.length} · `:''}{busy?'保存中':data?'本机存储已连接':'连接中'} · {watch.length}/40 重点标的</span></footer>
 {notice&&<div className="m-toast" role="status">{notice}<button aria-label="关闭提示" onClick={()=>setNotice('')}>×</button></div>}
 {dialog?.type==='settings'&&<Modal title="设置" onClose={close}><div className="settings-links">{[['data','数据来源与关注证券','来源开关、关键词、抓取与关注管理'],['operations','自动化与运维','任务控制、模型预算、备份和异常'],['rules','规则与执行边界','初筛规则、行情能力与模拟限制']].map(([type,title,description])=><button key={type} onClick={()=>open({type})}><strong>{title}</strong><span>{description}</span></button>)}</div><p className="m-note">账户风险参数在“组合”中随账户配置；评估批次在“评估”中管理。</p></Modal>}
 {dialog?.type==='dossier' &&data&&<CompanyDossier key={dialog.symbol} symbol={dialog.symbol} topicId={topic?.id} data={data} onClose={close} onCompany={openCompany} onTopic={id=>{const t=topics.find(t=>t.id===id);if(t){choose(t);close();}}} onEdit={(id,symbol)=>{const t=topics.find(t=>t.id===id);if(t){choose(t);open({type:'company',symbol});}}} onPropose={(symbol,id)=>proposal(symbol,'buy',topics.find(t=>t.id===id))}/> }
 {dialog?.type==='evaluation'&&data&&<EvaluationReview data={data} onClose={close}/>}
 {dialog?.type==='market-simulation'&&data&&<MarketSimulation data={data} onClose={close}/>}
 {dialog?.type==='observations'&&<ObservationInbox data={data} initialTopicId={topic?.id} initialTodoId={dialog.todoId} busy={busy} mutate={mutate} onClose={close} onTopic={id=>{const t=topics.find(t=>t.id===id);if(t){choose(t);close();}}}/>}
 {dialog?.type==='operations'&&data&&<Operations data={data} initialPipelineId={dialog.pipelineId} onClose={close} busy={busy} onPriceCollection={payload=>mutate('/api/price-collection','PATCH',payload)} onPipeline={(action,payload)=>action==='configure'?mutate('/api/research-pipeline','PATCH',payload):mutate(`/api/research-pipeline/${action==='retry-relation'?'relations/':action==='retry-event'?'events/':''}${payload.id}/retry`,'POST',{})} onControl={(name,payload)=>mutate(`/api/operations/${name}`,'POST',payload)}/>}
 {dialog?.type==='data'&&<DataDesk data={data} mutate={mutate} busy={busy} onClose={()=>{close();void load();}}/>}{dialog?.type==='rules'&&<Rulebook onClose={close}/>}
 {dialog?.type==='new'&&<NewTopic onClose={close} busy={busy} onCreate={p=>mutate('/api/research','POST',p)} onCreated={r=>setSelected(r.createdTopicId)}/>}
 {dialog?.type==='evidence'&&topic&&<AddEvidence key={topic.id} topic={topic} onClose={close} busy={busy} mutate={mutate}/>}{dialog?.type==='company'&&topic&&<CompanyForm topic={topic} onClose={close} busy={busy} mutate={mutate} watch={watch} deferred={data?.autoWatch?.deferred||[]} initialSymbol={dialog.symbol||''}/>}
 {dialog?.type==='verify'&&topic&&<VerifyEvidence key={`${topic.id}:${dialog.evidence.id}`} topic={topic} evidence={dialog.evidence} onClose={close} busy={busy} mutate={mutate}/>}
 {dialog?.type==='detail'&&topic&&<Modal title="研究、证据与历史追踪" onClose={close}><TopicDetail topic={topic} topics={topics} busy={busy} mutate={mutate} tab={tab} setTab={setTab} onEvidence={()=>open({type:'evidence'})} onCompany={openCompany} onVerify={e=>open({type:'verify',evidence:e})}/></Modal>}
 {dialog?.type==='event-continuity'&&<EventContinuity initialSemantic={dialog.semantic} busy={busy} mutate={mutate} onClose={close} onTopic={id=>{const t=topics.find(t=>t.id===id);if(t){choose(t);close();}}} onNews={async id=>{try{const news=await request(`/api/news/${id}`);open({type:'news',newsId:id,news});}catch(e){setError(e.message);}}}/>}
 {dialog?.type==='news'&&<Modal title="事件增量核验" onClose={close}><NewsInspector news={dialog.news||inbox.find(n=>n.id===dialog.newsId)} topics={topics} busy={busy} mutate={mutate} onTarget={id=>{const t=topics.find(t=>t.id===id);if(t)choose(t);}} onCreated={id=>{setSelected(id);setStock('');setArchived(false);setEventScope('all');setEventType('all');setSearch('');close();}}/></Modal>}
 {dialog?.type==='proposal'&&book&&dtopic&&<Proposal book={book} topic={dtopic} workflow={data.workflow?.find(w=>w.topicId===dtopic.id)} symbol={dialog.symbol} side={dialog.side} onClose={close} mutate={mutate} busy={busy}/>}
 {dialog?.type==='decision'&&book&&<Decision book={book} workflow={data.workflow?.find(w=>w.topicId===book.orders.find(o=>o.id===dialog.orderId)?.topicId)} order={book.orders.find(o=>o.id===dialog.orderId)} onClose={close} mutate={mutate} busy={busy}/>}
 {dialog?.type==='params'&&book&&<Parameters book={book} onClose={close} mutate={mutate} busy={busy}/>}
 {dialog?.type==='review'&&book&&<Review book={book} position={book.positions.find(p=>p.symbol===dialog.symbol)} onClose={close} onExit={sell} mutate={mutate} busy={busy}/>}
 {dialog?.type==='records'&&book&&<Records book={book} onClose={close}/>}
 </main></ErrorContext.Provider>;
}
