import ActivitySidebar from './ActivitySidebar';
import EventRadar from './EventRadar';
import {groupEventResearch} from '../../shared/workbench-events.mjs';
import {DashboardStatus,DecisionSidebar,HoldingsSummary,PositionDetails} from './DashboardPanels';
import {createDeferredView} from '../DeferredView';
const NewsLibrary=createDeferredView(()=>import('../major/NewsLibrary'),{title:'完整新闻库'});
import React,{useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import DatasetIdentity from './DatasetIdentity';
const EvaluationReview=createDeferredView(()=>import('./EvaluationReview'),{title:'研究评估',mode:'dialog'});
const MarketSimulation=createDeferredView(()=>import('./MarketSimulation'),{title:'市场模拟',mode:'dialog'});
const ObservationInbox=createDeferredView(()=>import('./ObservationInbox'),{title:'观察待办',mode:'dialog'});
const DataDesk=createDeferredView(()=>import('../terminal/DataDesk'),{title:'数据源',mode:'dialog'});
import '../terminal/terminal.css';
import {Button,Modal,ErrorContext} from '../major/Primitives';
import {request,time} from '../major/api';
import {NewTopic,AddEvidence,CompanyForm,Rulebook,VerifyEvidence} from '../major/ResearchForms';
const TopicDetail=createDeferredView(()=>import('../major/TopicDetail'),{title:'研究、证据与历史追踪'});
const NewsInspector=createDeferredView(()=>import('../major/NewsInspector'),{title:'事件增量核验'});
import '../major/major.css';
import '../major/research-materials.css';
import MarketPanel from './MarketPanel';
const CompanyDossier=createDeferredView(()=>import('./CompanyDossier'),{title:'公司研究',mode:'dialog'});
import {readResearchContext,researchContexts} from './research-context';
import EventBrief,{HistoricalResearchNotice} from './EventBrief';
import {eventProfile} from './event-view';
import {AccountStrip,DecisionQueue,Holdings} from './PaperPanels';
import {Proposal,Decision,Parameters,Review,Records} from './PaperForms';
import './integrated.css';
import './workbench-layout.css';
import './workspace.css';
import './event-continuity.css';
import './dashboard.css';
import {orderedTopics} from './decision-model';
import {Operations} from './Operations';
const EventContinuity=createDeferredView(()=>import('./EventContinuity'),{title:'事件追踪',mode:'dialog'});
export default function IntegratedWorkbench(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[selected,setSelected]=useState(()=>new URLSearchParams(window.location.search).get('topic')||''),[stock,setStock]=useState(()=>readResearchContext(new URLSearchParams(window.location.search).get('topic')).symbol),[dialog,setDialog]=useState(null),[tab,setTab]=useState('evidence'),[archived,setArchived]=useState(false),[eventScope,setEventScope]=useState('all'),[search,setSearch]=useState(''),[eventType,setEventType]=useState('all'),[focus,setFocusState]=useState('research'),[researchStage,setResearchStage]=useState('ready'),[marketNavigation,setMarketNavigation]=useState({account:'aggressive',order:'',nonce:0}),[recent,setRecent]=useState(()=>researchContexts().map(r=>r.id).reverse());
 const [accountId,setAccountId]=useState(null),[expandedPosition,setExpandedPosition]=useState(null),[dialogHistory,setDialogHistory]=useState([]),[expandedEvent,setExpandedEvent]=useState(null),[historyExpanded,setHistoryExpanded]=useState(null);
 const mainRef=useRef(null),scrolls=useRef({}),restoreDialogScroll=useRef(null);
 function changeFocus(value){
  const root=mainRef.current;if(root)scrolls.current[focus]=Object.fromEntries(['.i-topics','.i-research','.workspace-primary','.dashboard-holdings-scroll'].map(q=>[q,root.querySelector(q)?.scrollTop||0]));
  setFocusState(value);
 }
 useLayoutEffect(()=>{for(const [selector,top] of Object.entries(scrolls.current[focus]||{})){const el=mainRef.current?.querySelector(selector);if(el)el.scrollTop=top;}},[focus]);
 useEffect(()=>{if(restoreDialogScroll.current!==null){const el=mainRef.current?.querySelector('dialog[open] .m-modal-body');if(el)el.scrollTop=restoreDialogScroll.current;restoreDialogScroll.current=null;}},[dialog]);
 const active=useRef(true),sequence=useRef(0),inFlight=useRef(false),readFlight=useRef(false);
 async function load(){if(inFlight.current||readFlight.current)return;readFlight.current=true;const seq=++sequence.current;try{const result=await request('/api/data');if(active.current&&seq===sequence.current){setData(result);setError('');}}catch(e){if(active.current&&seq===sequence.current)setError(e.message);}finally{readFlight.current=false;}}
 useEffect(()=>{active.current=true;void load();const timer=setInterval(load,15000);return()=>{active.current=false;sequence.current++;clearInterval(timer);};},[]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(timer);},[notice]);
 async function mutate(path,method,payload){if(inFlight.current)return null;inFlight.current=true;sequence.current++;setBusy(true);setError('');try{const r=await request(path,method,payload);if(active.current){setData(r);setNotice('已保存到本机，历史版本保留');}return r;}catch(e){if(active.current)setError(e.message);return null;}finally{inFlight.current=false;if(active.current)setBusy(false);}}
 const topics=data?.research?.topics||[],watch=data?.watchlist||[],book=data?.paper,inbox=data?.research?.inbox||[],overview=data?.overview;
 const eventRows=useMemo(()=>groupEventResearch(topics,overview),[topics,overview]),currentTopics=eventRows.flatMap(row=>row.topics).filter(t=>t.status==='active'),defaultTopic=currentTopics.find(t=>t.origin==='recent-data-test')||currentTopics[0]||topics[0];
 const topic=topics.find(t=>t.id===selected)||defaultTopic,workflow=data?.workflow?.find(x=>x.topicId===topic?.id);
 useEffect(()=>{if(!topic)return;if(topic.id!==selected){setSelected(topic.id);setStock(topic.companies[0]?.symbol||'');}else if(!stock)setStock(topic.companies[0]?.symbol||'');},[topic,selected,stock]);
 const eventIndex=new Map((overview?.events||[]).map((e,i)=>[e.id,{...e,index:i}])),eventNames=new Map(eventRows.flatMap(row=>row.allTopics.map(t=>[t.id,row.title]))),selectedEvent=eventRows.find(row=>row.allTopics.some(t=>t.id===topic?.id));
 const historical=selectedEvent?.historicalTopics.some(t=>t.id===topic?.id)?selectedEvent.cluster.history.find(h=>h.topicId===topic.id):null;
 useEffect(()=>{if(historical){setExpandedEvent(selectedEvent.id);setHistoryExpanded(selectedEvent.id);}},[topic?.id,historical?.currentTopicId,selectedEvent?.id]);
 function showCurrentResearch(){const current=topics.find(t=>t.id===historical?.currentTopicId);if(current)choose(current);}
 const filteredTopics=(overview?[...topics].sort((a,b)=>(eventIndex.get(a.id)?.index??Infinity)-(eventIndex.get(b.id)?.index??Infinity)):orderedTopics(topics,data?.workflow||[])).filter(t=>(eventType==='all'||eventProfile(t).id===eventType)&&(!search||[t.title,t.label,eventNames.get(t.id),...t.companies.flatMap(c=>[c.name,c.symbol])].join(' ').toLowerCase().includes(search.trim().toLowerCase()))).filter(t=>t.status===(archived?'archived':'active')&&(researchStage==='all'||t.origin!=='news-candidate'||t.dossier||t.id===selected)&&(eventScope==='all'||eventScope==='holdings'&&eventIndex.get(t.id)?.positions>0||eventScope==='recent'&&t.origin==='recent-data-test'||eventScope==='attachments'&&t.origin==='attachment-research'||eventScope==='examples'&&t.origin==='retrospective-case'));
 function choose(t){const context=readResearchContext(t.id);setSelected(t.id);setStock(context.symbol||t.companies[0]?.symbol||'');setRecent(v=>[...new Set([t.id,selected,...v].filter(Boolean))].slice(0,8));const u=new URL(window.location.href);u.searchParams.set('topic',t.id);u.searchParams.set('range',context.range);u.searchParams.set('view',context.view);window.history.pushState(null,'',u);}
 useEffect(()=>{function restore(){const id=new URLSearchParams(window.location.search).get('topic');const t=topics.find(t=>t.id===id);if(t){setSelected(t.id);setStock(readResearchContext(t.id).symbol||t.companies[0]?.symbol||'');}}window.addEventListener('popstate',restore);return()=>window.removeEventListener('popstate',restore);},[topics]);
 useEffect(()=>{if(!topic)return;const u=new URL(window.location.href);if(u.searchParams.get('topic')!==topic.id){u.searchParams.set('topic',topic.id);window.history.replaceState(null,'',u);}},[topic?.id]); function open(value){setError('');if(dialog&&dialog.type!==value.type)setDialogHistory(h=>[...h,{dialog,tab,selected:topic?.id,stock,scroll:mainRef.current?.querySelector('dialog[open] .m-modal-body')?.scrollTop||0}]);setDialog(value);}
 function proposal(symbol,side='buy',target=topic){if(target){setSelected(target.id);open({type:'proposal',symbol,side,topicId:target.id});}}
 function sell(p){proposal(p.symbol,'sell',topics.find(t=>t.id===p.topicId));}
 const openCompany=symbol=>{setStock(symbol);open({type:'dossier',symbol});};
 const close=()=>{const previous=dialogHistory.at(-1);if(previous){setDialog(previous.dialog);setTab(previous.tab);if(previous.selected){setSelected(previous.selected);setStock(previous.stock);const context=readResearchContext(previous.selected),url=new URL(window.location.href);url.searchParams.set('topic',previous.selected);url.searchParams.set('range',context.range);url.searchParams.set('view',context.view);window.history.replaceState(null,'',url);}restoreDialogScroll.current=previous.scroll;setDialogHistory(h=>h.slice(0,-1));}else setDialog(null);},dtopic=topics.find(t=>t.id===dialog?.topicId)||topic;
 const radarProps={topics:filteredTopics,rows:eventRows,expanded:expandedEvent,onExpand:setExpandedEvent,historyExpanded,onHistoryExpand:setHistoryExpanded,overview,selected:topic?.id,filters:{archived,eventScope,eventType,researchStage,search},onFilter:(key,value)=>({archived:setArchived,eventScope:setEventScope,eventType:setEventType,researchStage:setResearchStage,search:setSearch}[key])(value),onSelect:choose,onMore:()=>changeFocus('events'),onNews:()=>changeFocus('news'),onRelations:()=>open({type:'event-continuity'})};
 function showPortfolio(account=accountId||overview?.defaultAccount){setAccountId(account);setMarketNavigation(n=>({account:account==='scenario'?'aggressive':account,order:'',nonce:n.nonce+1}));setDialog(null);setDialogHistory([]);changeFocus('portfolio');}
 function openDecision(item){if(item.account==='scenario')open({type:'decision',orderId:item.orderId});else{setMarketNavigation(n=>({account:item.account,order:item.orderId,nonce:n.nonce+1}));setDialog(null);setDialogHistory([]);changeFocus('portfolio');}}
 function openRisk(item){if(item.positionId)open({type:'position',positionId:item.positionId});else showPortfolio(item.account);}
 function openRecord(item){const t=topics.find(t=>t.id===item.topicId);if(t){choose(t);setTab('materials');open({type:'detail'});}else if(item.newsId){void request(`/api/news/${item.newsId}`).then(news=>open({type:'news',newsId:news.id,news})).catch(e=>setError(e.message));}else open({type:'operations'});}
 function openTodo(item){const t=topics.find(t=>t.id===item.topicId);if(t)choose(t);if(item.kind==='model'){setTab('materials');open({type:'detail'});}else if(item.kind==='observation')open({type:'observations',todoId:item.id.slice('observation:'.length)});else if(['relation','cluster'].includes(item.kind))open({type:'event-continuity',semantic:true});else if(item.kind==='order')openDecision({...item,orderId:item.id.split(':').at(-1)});else open({type:'operations',pipelineId:item.id.slice('pipeline:'.length)});}
 const positionAccount=overview?.accounts.find(a=>a.positions.some(p=>p.id===dialog?.positionId)),detailPosition=positionAccount?.positions.find(p=>p.id===dialog?.positionId);
 return <ErrorContext.Provider value={error}><main ref={mainRef} className={`integrated major v6 v7 v8 dashboard-shell focus-${focus} ${focus==='research'?'dashboard-home':''}`} aria-label="全球重大事件交易工作台"><header className="i-header"><div className="m-brand"><img src="/signal.svg" alt=""/><strong>信号猎手</strong><span>Signal Hunter</span><b className="i-live-dot">{data?.runtime?.offline?'DEMO':'LOCAL'}</b></div><div className="i-header-actions"><Button disabled={!data} onClick={()=>open({type:'settings'})}>设置</Button><Button disabled={!data} onClick={()=>open({type:'operations'})}>运行详情</Button></div></header>
 {data?.runtime?.offline&&<div className="demo-banner" role="status">离线演示 · 事件、新闻与曲线均为虚构；证券代码仅作界面示例。操作只保存在独立演示库。</div>}
 <nav className="workspace-nav" aria-label="主导航">{[['research','工作台'],['portfolio','组合'],['evaluation','评估']].map(([k,v])=><button key={k} aria-pressed={focus===k||k==='research'&&['events','news'].includes(focus)} onClick={()=>changeFocus(k)}>{v}</button>)}</nav>
 <DashboardStatus data={data} busy={busy} onAutomation={action=>mutate('/api/research-automation','POST',{action,version:data.researchPipeline.settings.version})} onRuntime={()=>open({type:'runtime'})}/>
 {error&&<div className="i-error" role="alert">{error}<Button onClick={load}>刷新连接</Button></div>}
 <div className={`i-main workspace-main ${focus==='research'?'':'workspace-wide'}`}>
 {focus==='research'?<><EventRadar {...radarProps}/>
 <section className="i-research i-panel" aria-label="事件研判与行情"><nav className="research-tabs" aria-label="最近研究">{[topic?.id,...recent.filter(id=>id!==topic?.id)].filter(Boolean).slice(0,8).map(id=>{const t=topics.find(t=>t.id===id);return t?<button key={id} aria-pressed={id===topic?.id} onClick={()=>choose(t)} title={t.title}>{t.title}</button>:null;})}</nav>{topic?<><EventBrief compact historical={historical} onCurrent={showCurrentResearch} eventGroup={selectedEvent?.cluster?selectedEvent:undefined} topic={topic} workflow={workflow} onDetail={value=>{setTab(value);open({type:'detail'});}} onEvidence={()=>open({type:'evidence'})} onCompany={()=>open({type:'company'})}/><MarketPanel key={topic.id} topic={topic} topics={topics} book={book} watch={watch} selected={stock} onSelect={setStock} onCompany={openCompany} proposalLabel={data.runtime.offline?'拟演练申请':'查看行动条件'} pageSize={3} onPropose={s=>{if(data.runtime.offline)proposal(s);else{setStock(s);setTab('hypothesis');open({type:'detail'});}}} onManage={()=>open({type:'data'})} checks={data?.checks||{}} busy={busy} onRefresh={async symbols=>{const r=await mutate('/api/daily/refresh','POST',{symbols});if(r){const failed=symbols.filter(s=>r.checks['daily:'+s]?.state==='error');setNotice(failed.length?`${failed.length} 家公司日线更新有误，保留可用缓存`:'日线已检查，数据时间以各图为准');}}}/></>:<p className="i-note">{data?'尚无研究事件。在设置中「新建研究」，或等待自动研究结果，或从新闻建立草稿。':'等待研究数据…'}</p>}</section>
 </>:<section className="workspace-primary i-panel">{data&&(focus==='news'?<><div className="dashboard-page-head"><h2>完整新闻库</h2><Button onClick={()=>changeFocus('research')}>← 返回原看板</Button></div><NewsLibrary onOpen={news=>open({type:'news',newsId:news.id,news})}/></>:focus==='events'?<><div className="dashboard-page-head"><h2>全部事件与研究</h2><Button onClick={()=>changeFocus('research')}>← 返回原看板</Button></div><EventRadar {...radarProps} full onSelect={t=>{choose(t);setTab(t.dossier?'brief':'evidence');open({type:'detail'});}}/></>:focus==='portfolio'?<><MarketSimulation key={marketNavigation.nonce} embedded initialAccount={marketNavigation.account} initialOrder={marketNavigation.order} data={data} onClose={()=>changeFocus('research')}/><details className="advanced-scenario" open={accountId==='scenario'||undefined}><summary>高级：结构演练账本（独立于激进 / 稳健账户）</summary>{book&&<><AccountStrip book={book}/><DecisionQueue book={book} topics={topics} selectedTopic={topic?.id} workflow={data.workflow||[]} initialScope="all" onTopic={(id,symbol)=>{const t=topics.find(t=>t.id===id);if(t)choose(t);if(symbol)setStock(symbol);}} onReview={p=>open({type:'review',symbol:p.symbol})} onDecision={o=>open({type:'decision',orderId:o.id})} onParams={()=>open({type:'params'})} onRecords={()=>open({type:'records'})}/><Holdings book={book} selectedTopic={topic?.id} selectedSymbol={stock} topics={topics} watch={watch} onSelect={p=>{const t=topics.find(t=>t.id===p.topicId);if(t)choose(t);setStock(p.symbol);}} onSell={sell} onReview={p=>open({type:'review',symbol:p.symbol})} onRecords={()=>open({type:'records'})}/></>}</details></>:<EvaluationReview embedded data={data} onClose={()=>changeFocus('research')}/>)}</section>}
 {focus==='research'&&<DecisionSidebar overview={overview} onDecision={openDecision} onRisk={openRisk} onPosition={positionId=>open({type:'position',positionId})} onAllRisks={view=>open({type:'dashboard-risks',view})} onMonitoring={()=>open({type:'monitoring'})} onRuntime={()=>open({type:'runtime'})}/>}
 </div>
 {focus==='research'&&<HoldingsSummary overview={overview} accountId={accountId} onAccount={value=>{setAccountId(value);setExpandedPosition(null);}} selectedTopic={topic?.id} selectedSymbol={stock} onSelect={p=>{const t=topics.find(t=>t.id===p.topicId);if(t)choose(t);setStock(p.symbol);}} onDetail={positionId=>open({type:'position',positionId})} onPortfolio={showPortfolio} expanded={expandedPosition} onExpand={setExpandedPosition}/>}
 <footer className="i-footer"><span>研究与模拟分离 · 版本与原始记录保留</span><span>{data?.autoWatch?.deferred?.length?`关注待处理 ${data.autoWatch.deferred.length} · `:''}{busy?'保存中':data?'本机存储已连接':'连接中'} · {watch.length}/40 重点标的</span></footer>
 {notice&&<div className="m-toast" role="status">{notice}<button aria-label="关闭提示" onClick={()=>setNotice('')}>×</button></div>}
 {dialog?.type==='runtime'&&<Modal title="后台进度与记录" className="workspace-detail dashboard-runtime-detail" closeLabel="← 返回" onClose={close}><ActivitySidebar instanceId={data?.runtime?.instance?.id} topicId={topic?.id} onOperations={()=>open({type:'operations'})} onRecord={openRecord} onTodo={openTodo}/></Modal>}
 {dialog?.type==='position'&&<Modal title="持仓长期档案" className="workspace-detail" closeLabel={dialogHistory.length?'← 返回上一层':'← 返回原看板'} onClose={close}><PositionDetails position={detailPosition} account={positionAccount} onResearch={p=>{const t=topics.find(t=>t.id===p.topicId);if(t){choose(t);setTab('hypothesis');open({type:'detail'});}}} onAccount={showPortfolio}/></Modal>}
 {dialog?.type==='dashboard-risks'&&<Modal title="全局风险与买卖待决定" className="workspace-detail" closeLabel="← 返回原看板" onClose={close}><div className="detail-section-tools">{[['risks','持仓风险',overview?.risks.length||0],['decisions','买卖待决定',overview?.decisions.length||0]].map(([view,label,count])=><Button key={view} aria-pressed={dialog.view===view} onClick={()=>setDialog({...dialog,view})}>{label} · {count}</Button>)}</div><div className="dashboard-all-items">{dialog.view==='decisions'?<>{overview?.decisions.map(d=><button className="dashboard-list-item" key={d.id} onClick={()=>openDecision(d)}><strong>{d.symbol} · {d.side==='sell'?'卖出':'买入'}</strong><span>{overview.accounts.find(a=>a.id===d.account)?.label} · 研究 v{d.topicVersion} · 到期 {time(d.expiresAt)}</span></button>)}{!overview?.decisions.length&&<p className="m-note">当前没有待决定的有效模拟申请。</p>}</>:<>{overview?.risks.map(r=><button className="dashboard-list-item" key={r.id} onClick={()=>openRisk(r)}><strong>{r.symbol||overview.accounts.find(a=>a.id===r.account)?.label}</strong><span>{r.message}</span></button>)}{!overview?.risks.length&&<p className="m-note">暂无已识别风险，仍需核对账户的数据完整性。</p>}</>}</div></Modal>}
 {dialog?.type==='monitoring'&&<Modal title="后续监控" className="workspace-detail" closeLabel="← 返回原看板" onClose={close}><p className="m-note">持仓监控与原研究保持关联；缺数据不能解释为风险解除。详细巡检记录仍保留。</p>{overview?.monitoring.map(m=><button className="dashboard-list-item" key={m.id} onClick={()=>open({type:'position',positionId:m.id})}><strong>{m.symbol} · {m.account}</strong><span>复核 {time(m.reviewAt)} · {m.holdingHorizon||'窗口待评估'}</span><span>{m.risks.join('；')||'暂无已识别风险'}</span></button>)}<Button onClick={()=>open({type:'observations'})}>查看研究观察与历史巡检</Button></Modal>}
 {dialog?.type==='settings'&&<Modal title="设置" onClose={close}><DatasetIdentity runtime={data?.runtime} count={topics.length}/><div className="settings-links">{[['new','新建研究','手工建立补充研究；不作为自动研究的前置步骤'],['data','数据来源与关注证券','来源开关、关键词、抓取与关注管理'],['operations','自动化与运维','任务控制、模型预算、备份和异常'],['rules','规则与执行边界','初筛规则、行情能力与模拟限制']].map(([type,title,description])=><button key={type} onClick={()=>open({type})}><strong>{title}</strong><span>{description}</span></button>)}</div><p className="m-note">账户风险参数在“组合”中随账户配置；评估批次在“评估”中管理。</p></Modal>}
 {dialog?.type==='dossier' &&data&&<CompanyDossier key={dialog.symbol} symbol={dialog.symbol} topicId={topic?.id} data={data} onClose={close} onCompany={openCompany} onTopic={id=>{const t=topics.find(t=>t.id===id);if(t){choose(t);close();}}} onEdit={(id,symbol)=>{const t=topics.find(t=>t.id===id);if(t){choose(t);open({type:'company',symbol});}}} onPropose={(symbol,id)=>proposal(symbol,'buy',topics.find(t=>t.id===id))}/> }
 {dialog?.type==='evaluation'&&data&&<EvaluationReview data={data} onClose={close}/>}
 {dialog?.type==='market-simulation'&&data&&<MarketSimulation data={data} onClose={close}/>}
 {dialog?.type==='observations'&&<ObservationInbox data={data} initialTopicId={topic?.id} initialTodoId={dialog.todoId} busy={busy} mutate={mutate} onClose={close} onTopic={id=>{const t=topics.find(t=>t.id===id);if(t){choose(t);close();}}}/>}
 {dialog?.type==='operations'&&data&&<Operations data={data} initialPipelineId={dialog.pipelineId} onClose={close} busy={busy} onPriceCollection={payload=>mutate('/api/price-collection','PATCH',payload)} onPipeline={(action,payload)=>action==='configure'?mutate('/api/research-pipeline','PATCH',payload):mutate(`/api/research-pipeline/${action==='retry-relation'?'relations/':action==='retry-event'?'events/':''}${payload.id}/retry`,'POST',{})} onControl={(name,payload)=>mutate(`/api/operations/${name}`,'POST',payload)}/>}
 {dialog?.type==='data'&&<DataDesk data={data} mutate={mutate} busy={busy} onClose={()=>{close();void load();}}/>}{dialog?.type==='rules'&&<Rulebook onClose={close}/>}
 {dialog?.type==='new'&&<NewTopic onClose={close} busy={busy} onCreate={p=>mutate('/api/research','POST',p)} onCreated={r=>setSelected(r.createdTopicId)}/>}
 {dialog?.type==='evidence'&&topic&&<AddEvidence key={topic.id} topic={topic} onClose={close} busy={busy} mutate={mutate}/>}{dialog?.type==='company'&&topic&&<CompanyForm topic={topic} onClose={close} busy={busy} mutate={mutate} watch={watch} deferred={data?.autoWatch?.deferred||[]} initialSymbol={dialog.symbol||''}/>}
 {dialog?.type==='verify'&&topic&&<VerifyEvidence key={`${topic.id}:${dialog.evidence.id}`} topic={topic} evidence={dialog.evidence} onClose={close} busy={busy} mutate={mutate}/>}
 {dialog?.type==='detail'&&topic&&<Modal title="研究、证据与历史追踪" className="workspace-detail" closeLabel={dialogHistory.length?'← 返回上一层':focus==='events'?'← 返回事件列表':'← 返回原看板'} onClose={close}><HistoricalResearchNotice history={historical} onCurrent={showCurrentResearch}/><TopicDetail topic={topic} topics={topics} busy={busy} mutate={mutate} tab={tab} setTab={setTab} onEvidence={()=>open({type:'evidence'})} onCompany={openCompany} onVerify={e=>open({type:'verify',evidence:e})}/></Modal>}
 {dialog?.type==='event-continuity'&&<EventContinuity initialSemantic={dialog.semantic} busy={busy} mutate={mutate} onClose={close} onTopic={id=>{const t=topics.find(t=>t.id===id);if(t){choose(t);close();}}} onNews={async id=>{try{const news=await request(`/api/news/${id}`);open({type:'news',newsId:id,news});}catch(e){setError(e.message);}}}/>}
 {dialog?.type==='news'&&<Modal title="事件增量核验" className="workspace-detail" closeLabel={dialogHistory.length?'← 返回上一层':'← 返回列表'} onClose={close}><NewsInspector news={dialog.news||inbox.find(n=>n.id===dialog.newsId)} topics={topics} busy={busy} mutate={mutate} onTarget={id=>{const t=topics.find(t=>t.id===id);if(t)choose(t);}} onCreated={id=>{setSelected(id);setStock('');setArchived(false);setEventScope('all');setEventType('all');setSearch('');close();}}/></Modal>}
 {dialog?.type==='proposal'&&book&&dtopic&&<Proposal book={book} topic={dtopic} workflow={data.workflow?.find(w=>w.topicId===dtopic.id)} symbol={dialog.symbol} side={dialog.side} onClose={close} mutate={mutate} busy={busy}/>}
 {dialog?.type==='decision'&&book&&<Decision book={book} workflow={data.workflow?.find(w=>w.topicId===book.orders.find(o=>o.id===dialog.orderId)?.topicId)} order={book.orders.find(o=>o.id===dialog.orderId)} onClose={close} mutate={mutate} busy={busy}/>}
 {dialog?.type==='params'&&book&&<Parameters book={book} onClose={close} mutate={mutate} busy={busy}/>}
 {dialog?.type==='review'&&book&&<Review book={book} position={book.positions.find(p=>p.symbol===dialog.symbol)} onClose={close} onExit={sell} mutate={mutate} busy={busy}/>}
 {dialog?.type==='records'&&book&&<Records book={book} onClose={close}/>}
 </main></ErrorContext.Provider>;
}
