import React,{useRef,useState} from 'react';
import {Button} from '../major/Primitives';
import {request,time} from '../major/api';
const count=c=>`${c.observedSum}${c.unknownRuns?`（另${c.unknownRuns}次未知）`:''}`;
export default function NewsCoverageReport({serverTime}){
 const [window,setWindow]=useState(()=>{const end=(serverTime||new Date().toISOString()).slice(0,10);return {from:new Date(Date.parse(end+'T00:00:00Z')-6*86400000).toISOString().slice(0,10),to:end};}),[report,setReport]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),pending=useRef(false);
 const run=async e=>{e.preventDefault();if(pending.current)return;pending.current=true;setLoading(true);setError('');setReport(null);try{setReport(await request('/api/news/coverage?'+new URLSearchParams(window)));}catch(e){setError(e.message);}finally{pending.current=false;setLoading(false);}};
 return <section aria-label="按窗口核对采集记录"><h4>按窗口核对采集记录</h4><p className="m-note">完整统计所选UTC日期内开始的采集尝试，最多31天；不会发起补采。当前启停状态不能代表历史配置。</p>
 <form className="m-form" onSubmit={run}><label>报告开始日期（UTC）<input type="date" required value={window.from} disabled={loading} onChange={e=>setWindow({...window,from:e.target.value})}/></label><label>报告结束日期（UTC，含当日）<input type="date" required value={window.to} disabled={loading} onChange={e=>setWindow({...window,to:e.target.value})}/></label><Button type="submit" aria-disabled={loading}>生成覆盖报告</Button></form>
 {error&&<p role="alert">{error}</p>}<p role="status">{loading?'正在汇总完整窗口…':report?`${report.from} 至 ${report.to} · 共 ${report.runCount} 次采集尝试`:'尚未生成窗口报告'}</p>
 {report&&<><p className="m-note">本报告生成于 {time(report.generatedAt)}。修改日期后需重新生成；旧结果仍对应上方报告日期。指纹 {report.inputHash.slice(0,16)}</p><div className="coverage-queries">{report.sources.map(s=><article key={s.queryId}><header><b>{s.label}</b><span>{s.attempts} 次尝试</span></header><p>成功 {s.states.ok} · 部分 {s.states.partial} · 失败 {s.states.failed} · 中止 {s.states.cancelled} · 中断 {s.states.interrupted} · 执行中 {s.states.running} · 未知 {s.states.unknown}</p><small>原始 {count(s.counts.rawCount)} · 接受 {count(s.counts.acceptedCount)} · 不合格 {count(s.counts.rejectedCount)} · 窗口外 {count(s.counts.outsideWindow)} · 重复 {count(s.counts.duplicates)}</small><small>新增 {count(s.counts.added)} · 修订 {count(s.counts.updated)} · 已留样唯一标题 {s.uniqueObservedItems} · 唯一修订 {s.uniqueObservedRevisions}</small><p>可能截断 {s.truncatedRuns} 次 · 分页重叠 {s.overlapRuns} 次 · 成功空返回 {s.emptySuccessfulRuns} 次</p><small>窗口内最长无尝试间隔约 {Math.ceil(s.longestNoAttemptSeconds/60)} 分钟（含首尾边界）</small><details><summary>逐日尝试与配置</summary>{s.days.map(d=><p key={d.day}>{d.day} · {d.attempts} 次尝试 / {d.successfulAttempts} 次成功{!d.attempts?' · 没有采集记录':!d.successfulAttempts?' · 没有成功记录':''}</p>)}{s.configurations.map((c,i)=><p key={i}>{c.provider||'旧记录来源未知'} · {c.kind||'类型未知'} · {c.keywords===null?'关键词未知':c.keywords||'无关键词'} · {c.adapterVersion||'版本未知'} · {c.attempts} 次</p>)}</details></article>)}</div><ul>{report.limitations.map(t=><li key={t}>{t}</li>)}</ul></>}
 </section>;
}
