import React,{useEffect,useState} from 'react';
import {Button} from '../major/Primitives';
import {instrument} from '../../shared/securities.mjs';
import {request,time} from '../major/api';
import './observation-rules.css';
const kinds={at:'指定复核时间',price:'价格达到阈值','research-change':'研究出现新版本',counterevidence:'出现新的反向线索'};
const describe=c=>c.type==='price'?`${c.symbol} ${c.interval==='1d'?'日线收盘':'分钟柱收盘'} ${c.operator==='gte'?'≥':'≤'} ${c.value} ${c.currency}`:c.type==='at'?`复核时间 ${time(c.at)}`:kinds[c.type];
const defaults=type=>type==='price'?{type,symbol:'',interval:'1d',operator:'gte',value:''}:type==='at'?{type,at:''}:{type};
const beijing=value=>value?new Date(Date.parse(value)+8*3600000).toISOString().slice(0,16):'';
const editable=rule=>rule.definition.conditions.map(({currency,...c})=>c.type==='at'?{...c,at:beijing(c.at)}:c);
function readDraft(key,topic,rule){try{const value=JSON.parse(sessionStorage.getItem(key));if(value&&typeof value.label==='string'&&['all','any'].includes(value.join)&&Array.isArray(value.conditions)&&value.conditions.length>=1&&value.conditions.length<=8&&value.conditions.every(c=>c&&Object.hasOwn(kinds,c.type))&&Number.isInteger(value.topicVersion)&&Number.isInteger(value.version)&&typeof value.clientId==='string'&&typeof value.note==='string')return value;}catch{}return initial(topic,rule);}
const initial=(topic,rule)=>({clientId:crypto.randomUUID(),topicVersion:topic.version,version:rule?.version||0,label:rule?.definition.label||'',join:rule?.definition.join||'all',conditions:rule?editable(rule):[defaults('at')],note:''});
function RuleEditor({topic,rule,instanceId,busy,mutate,onDone}){
 const key=`signal-observation-draft:${instanceId||'local'}:${topic.id}:${rule?.id||'new'}`;
 const [form,setForm]=useState(()=>readDraft(key,topic,rule)),[storageError,setStorageError]=useState(false);
 useEffect(()=>{try{sessionStorage.setItem(key,JSON.stringify(form));}catch{setStorageError(true);}},[key,form]);
 const update=(field,value)=>setForm(old=>({...old,[field]:value}));
 const change=(i,value)=>update('conditions',form.conditions.map((c,index)=>index===i?value:c));
 const staleTopic=form.topicVersion!==topic.version,staleRule=rule&&form.version!==rule.version;
 async function save(e){e.preventDefault();const conditions=form.conditions.map(c=>c.type==='at'?{...c,at:`${c.at}:00+08:00`}:c.type==='price'?{...c,value:Number(c.value)}:c),definition={label:form.label,join:form.join,conditions};
  const result=await mutate(rule?`/api/observation-rules/${rule.id}`:`/api/research/${topic.id}/observation-rules`,rule?'PATCH':'POST',{...definition,topicVersion:form.topicVersion,...(rule?{version:form.version,action:'edit',note:form.note}:{clientId:form.clientId})});
  if(result){try{if(sessionStorage.getItem(key)===JSON.stringify(form))sessionStorage.removeItem(key);}catch{}onDone();}
 }
 return <form className="m-form observation-editor" onSubmit={save}><h3>{rule?'修改观察条件':'添加观察条件'} · {topic.title}</h3><p>每个配置版本只生成一次待办。修改、恢复或重新监测会建立新版本，重新记录研究和反证基线。</p>{storageError&&<p role="alert">浏览器无法保存未提交草稿；关闭页面可能丢失输入。</p>}{staleTopic&&<p role="alert">研究已有新版本。核对后再保存。<Button type="button" disabled={busy} onClick={()=>update('topicVersion',topic.version)}>已核对，使用当前研究版本</Button></p>}{staleRule&&<p role="alert">配置已被其他操作更新。<Button type="button" disabled={busy} onClick={()=>setForm(initial(topic,rule))}>放弃本地编辑并载入当前配置</Button></p>}
 <fieldset disabled={busy}><label>观察名称<input required maxLength={100} value={form.label} onChange={e=>update('label',e.target.value)}/></label><label>组合方式<select value={form.join} onChange={e=>update('join',e.target.value)}><option value="all">全部满足（且）</option><option value="any">任一满足（或）</option></select></label>
 {form.conditions.map((c,i)=><fieldset key={i} className="observation-clause"><legend>条件 {i+1}</legend><label>条件类型<select value={c.type} onChange={e=>change(i,defaults(e.target.value))}>{Object.entries(kinds).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>
 {c.type==='at'&&<label>复核时间（北京时间）<input type="datetime-local" required step="60" value={c.at} onChange={e=>change(i,{...c,at:e.target.value})}/></label>}
 {c.type==='price'&&<><label>关联证券<select required value={c.symbol} onChange={e=>change(i,{...c,symbol:e.target.value})}><option value="">选择关联证券</option>{topic.companies.map(company=><option key={company.symbol} value={company.symbol}>{company.name} · {company.symbol}</option>)}</select></label><div className="m-form-row"><label>价格类型<select value={c.interval} onChange={e=>change(i,{...c,interval:e.target.value})}><option value="1d">最近有效日线收盘</option><option value="1m">最近有效分钟柱收盘</option></select></label><label>比较<select value={c.operator} onChange={e=>change(i,{...c,operator:e.target.value})}><option value="gte">大于等于</option><option value="lte">小于等于</option></select></label></div><label>阈值（{c.symbol?instrument(c.symbol).currency:'证券原币'}）<input type="number" min="0.00000001" max="1000000000000" step="any" required value={c.value} onChange={e=>change(i,{...c,value:e.target.value})}/></label><small>比较缓存价格是否已达到阈值，不推断两次采样之间的穿越；过期、缺失或时间未核验时不判断该条件。</small></>}
 {['research-change','counterevidence'].includes(c.type)&&<p>以此次保存时的研究 v{form.topicVersion} 为基线；已有版本和已有反证不重复命中。</p>}
 <Button type="button" disabled={form.conditions.length===1} onClick={()=>update('conditions',form.conditions.filter((_,index)=>index!==i))}>移除条件 {i+1}</Button></fieldset>)}
 <Button type="button" disabled={form.conditions.length>=8} onClick={()=>update('conditions',[...form.conditions,defaults('at')])}>增加一项条件</Button>
 {rule&&<label>变更说明<input required maxLength={500} value={form.note} onChange={e=>update('note',e.target.value)}/></label>}
 <div className="m-form-actions"><Button primary type="submit" disabled={staleTopic||staleRule}>保存观察条件</Button><Button type="button" onClick={onDone}>返回列表（保留未提交草稿）</Button></div></fieldset></form>;
}
export function ObservationResults({results=[]}){return <ul className="observation-results">{results.map((r,i)=><li key={i}><strong>{i+1}. {{true:'满足',false:'未满足',unknown:'无法判断'}[r.state]} · {r.reason}</strong>{r.input?.symbol&&<p>{r.input.symbol} · {r.input.price??'无有效价格'} {r.input.currency} · 阈值 {r.input.operator==='gte'?'≥':'≤'} {r.input.threshold??'—'}<br/>{r.input.provider||'来源未知'} · 数据时点 {r.input.dataAt||'未知'} · 接收 {time(r.input.receivedAt)}{r.input.synthetic?' · 合成演示':' · 研究价格，非成交报价'}</p>}{r.input?.at&&<p>复核时刻 {time(r.input.at)}</p>}{r.input?.currentVersion!==undefined&&<p>基线 v{r.input.baselineVersion} → 当前 v{r.input.currentVersion}</p>}{r.input?.evidence?.map(e=><p key={e.id}>{e.claim} · {e.verification}</p>)}</li>)}</ul>;}
function RuleCard({rule,topic,busy,mutate,onEdit}){
 const [note,setNote]=useState(''),[history,setHistory]=useState(null),[error,setError]=useState('');
 const state=!rule.active?'已暂停':rule.check?.firstMatchedAt?'已生成待办':{true:'已命中',false:'等待条件',unknown:'无法判断'}[rule.check?.state]||'等待后台检查';
 const action=async value=>{const result=await mutate(`/api/observation-rules/${rule.id}`,'PATCH',{version:rule.version,topicVersion:topic?.version,action:value,note});if(result){setNote('');setHistory(null);}};
 return <section className="observation-rule"><h3>{rule.definition.label} · v{rule.version}</h3><p>{state} · {rule.definition.join==='all'?'全部满足':'任一满足'} · 研究基线 v{rule.binding.topicVersion}</p><p>{rule.definition.conditions.map(describe).join(' / ')}</p><small>最近检查 {time(rule.check?.checkedAt)}{rule.check?.firstMatchedAt?' · 首次命中 '+time(rule.check.firstMatchedAt):''}</small>{rule.check&&<ObservationResults results={rule.check.results}/>}
 <label>操作说明<input aria-label={`操作说明 ${rule.definition.label}`} maxLength={500} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="m-form-actions"><Button disabled={busy||topic?.status!=='active'} onClick={onEdit}>编辑条件</Button><Button disabled={busy||!note.trim()||!rule.active&&topic?.status!=='active'} onClick={()=>action(rule.active?'pause':'resume')}>{rule.active?'暂停观察':'恢复观察'}</Button>{rule.active&&<Button disabled={busy||!note.trim()||topic?.status!=='active'} onClick={()=>action('rearm')}>重新监测（新版本）</Button>}<Button onClick={async()=>{try{setHistory(await request(`/api/observation-rules/${rule.id}/history`));setError('');}catch(e){setError(e.message);}}}>配置版本记录</Button></div>{error&&<p role="alert">{error}</p>}{history&&<div>{history.map(r=><details key={r.version}><summary>v{r.version} · {time(r.updatedAt)} · {r.reason}</summary><pre>{JSON.stringify({definition:r.definition,binding:r.binding,active:r.active},null,2)}</pre></details>)}</div>}</section>;
}
export default function ObservationRules({data,initialTopicId,busy,mutate}){
 const topics=data?.research?.topics||[],[selected,setSelected]=useState(initialTopicId||topics[0]?.id||''),[editing,setEditing]=useState(null),topic=topics.find(t=>t.id===selected),rules=(data?.observationInbox?.rules||[]).filter(r=>r.topicId===selected),rule=rules.find(r=>r.id===editing);
 return <section className="observation-settings" aria-label="观察条件设置"><p>后台检查条件并生成站内待办；不改变研究、风险限额或订单。价格条件不等于买卖建议。{data?.runtime?.offline?'当前为合成演示数据。':''}</p>{editing&&topic?<RuleEditor key={selected+editing} topic={topic} rule={rule} instanceId={data?.runtime?.instance?.id} busy={busy} mutate={mutate} onDone={()=>setEditing(null)}/>:<><label>选择研究<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">选择一个研究</option>{topics.map(t=><option key={t.id} value={t.id}>{t.title}{t.status==='active'?'':'（已归档）'}</option>)}</select></label><Button primary disabled={busy||topic?.status!=='active'} onClick={()=>setEditing('new')}>添加观察条件</Button>{!rules.length&&<p>此研究尚未配置观察条件。</p>}{rules.map(r=><RuleCard key={r.id} rule={r} topic={topic} busy={busy} mutate={mutate} onEdit={()=>setEditing(r.id)}/>)}</>}</section>;
}
