import React,{useEffect,useRef,useState} from 'react';
import useEditorDraft from '../major/useEditorDraft';
import {StatisticalControls,StatisticalResult,statisticalLabel} from './StatisticalObservation';
import {Button} from '../major/Primitives';
import {instrument} from '../../shared/securities.mjs';
import {request,time} from '../major/api';
import './observation-rules.css';
const kinds={'minute-anomaly':'分钟统计异常','daily-anomaly':'日线统计异常',at:'指定复核时间',price:'价格达到阈值','research-change':'研究出现新版本',counterevidence:'出现新的反向线索'};
const temporalLabel=c=>c.mode==='cross'?' · 相邻采样穿越':c.mode==='held'?` · 采样持续${c.holdSeconds}秒`:'';
const describe=c=>['daily-anomaly','minute-anomaly'].includes(c.type)?statisticalLabel(c):c.type==='price'?`${c.symbol} ${c.interval==='1d'?'日线收盘':'分钟柱收盘'} ${c.operator==='gte'?'≥':'≤'} ${c.value} ${c.currency}${temporalLabel(c)}${c.mode?` · 最大采样间隔${c.maxGapSeconds}秒`:""}`:c.type==='at'?`复核时间 ${time(c.at)}`:kinds[c.type];
const defaults=type=>['daily-anomaly','minute-anomaly'].includes(type)?{type,symbol:'',metric:'return',windowSize:20,zThreshold:3,direction:'both'}:type==='price'?{type,symbol:'',interval:'1d',operator:'gte',value:''}:type==='at'?{type,at:''}:{type};
const beijing=value=>value?new Date(Date.parse(value)+8*3600000).toISOString().slice(0,16):'';
const editable=rule=>rule.definition.conditions.map(({currency,...c})=>c.type==='at'?{...c,at:beijing(c.at)}:c);
const validForm=value=>value&&typeof value.label==='string'&&['all','any'].includes(value.join)&&Array.isArray(value.conditions)&&value.conditions.length>=1&&value.conditions.length<=8&&value.conditions.every(c=>c&&Object.hasOwn(kinds,c.type))&&Number.isSafeInteger(value.topicVersion)&&value.topicVersion>0&&Number.isSafeInteger(value.version)&&value.version>=0&&typeof value.clientId==='string'&&typeof value.note==='string';
function readLegacyDraft(key){try{const value=JSON.parse(window.sessionStorage.getItem(key));return validForm(value)?value:null;}catch{return null;}}
const initial=(topic,rule)=>({clientId:crypto.randomUUID(),topicVersion:topic.version,version:rule?.version||0,label:rule?.definition.label||'',join:rule?.definition.join||'all',conditions:rule?editable(rule):[defaults('at')],note:''});
function RuleEditor({topic,rule,instanceId,busy,mutate,onDone}){
 const legacyKey=`signal-observation-draft:${instanceId||'local'}:${topic.id}:${rule?.id||'new'}`;
 const editor=useEditorDraft({id:topic.id,createdAt:JSON.stringify([topic.createdAt||'',rule?.id||'new',rule?.createdAt||'']),version:rule?.version||topic.version},'observation-rule',()=>initial(topic,rule),validForm,instanceId||'local'),form=editor.draft.value;
 const [legacy]=useState(()=>readLegacyDraft(legacyKey)),[saving,setSaving]=useState(false),[error,setError]=useState(''),mounted=useRef(true),flight=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const update=(field,value)=>editor.change(old=>({...old,[field]:value}));
 const change=(i,value)=>editor.change(old=>({...old,conditions:old.conditions.map((c,index)=>index===i?value:c)}));
 const staleTopic=form.topicVersion!==topic.version,staleRule=rule&&form.version!==rule.version,locked=busy||saving;
 async function save(e){e.preventDefault();if(busy||flight.current||staleTopic||staleRule||topic.status!=='active')return;
  flight.current=true;setSaving(true);setError('');const submitted=editor.draft;
  const conditions=form.conditions.map(c=>['daily-anomaly','minute-anomaly'].includes(c.type)?{...c,windowSize:Number(c.windowSize),zThreshold:Number(c.zThreshold)}:c.type==='at'?{...c,at:`${c.at}:00+08:00`}:c.type==='price'?{...c,value:Number(c.value),...(c.mode&&c.mode!=='level'?{maxGapSeconds:Number(c.maxGapSeconds)}:{}),...(c.mode==='held'?{holdSeconds:Number(c.holdSeconds)}:{})}:c),definition={label:form.label,join:form.join,conditions};
  try{
   const result=await mutate(rule?`/api/observation-rules/${rule.id}`:`/api/research/${topic.id}/observation-rules`,rule?'PATCH':'POST',{...definition,topicVersion:form.topicVersion,...(rule?{version:form.version,action:'edit',note:form.note}:{clientId:form.clientId})});
   if(result){const saved=result.observationInbox?.rules?.find(r=>r.id===(rule?.id||form.clientId));if(!saved){if(mounted.current)setError('已收到保存回执，但未能核对配置版本，请返回列表核对。');return;}
    const ack=editor.ack(submitted,initial(topic,saved),saved.version);if(mounted.current&&!ack.retained)onDone();}
  }catch(e){if(mounted.current)setError(e.message);}finally{flight.current=false;if(mounted.current)setSaving(false);}
 }
 return <form className="m-form observation-editor" onSubmit={save}><h3>{rule?'修改观察条件':'添加观察条件'} · {topic.title}</h3><p>每个配置版本只生成一次待办。修改、恢复或重新监测会建立新版本，重新记录研究和反证基线。</p>{editor.draft.volatile&&<p role="alert">浏览器无法保存未提交草稿；关闭页面可能丢失输入。</p>}{error&&<p role="alert">{error}</p>}{legacy&&<p className="m-warning">发现旧观察草稿，没有研究创建时间记录；核对所属研究后可显式载入，原件保留。<Button type="button" disabled={locked} onClick={()=>editor.change(legacy,rule?.version||topic.version)}>载入旧观察条件草稿</Button></p>}{staleTopic&&<p role="alert">研究已有新版本。核对后再保存。<Button type="button" disabled={locked} onClick={()=>update('topicVersion',topic.version)}>已核对，使用当前研究版本</Button></p>}{staleRule&&<p role="alert">配置已被其他操作更新。<Button type="button" disabled={locked} onClick={()=>editor.reset()}>放弃本地编辑并载入当前配置</Button></p>}
 <fieldset disabled={locked}><label>观察名称<input required maxLength={100} value={form.label} onChange={e=>update('label',e.target.value)}/></label><label>组合方式<select value={form.join} onChange={e=>update('join',e.target.value)}><option value="all">全部满足（且）</option><option value="any">任一满足（或）</option></select></label>
 {form.conditions.map((c,i)=><fieldset key={i} className="observation-clause"><legend>条件 {i+1}</legend><label>条件类型<select value={c.type} onChange={e=>change(i,defaults(e.target.value))}>{Object.entries(kinds).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>
 {c.type==='at'&&<label>复核时间（北京时间）<input type="datetime-local" required step="60" value={c.at} onChange={e=>change(i,{...c,at:e.target.value})}/></label>}
 {['daily-anomaly','minute-anomaly'].includes(c.type)&&<StatisticalControls condition={c} companies={topic.companies} onChange={v=>change(i,v)}/>}
 {c.type==='price'&&<><label>关联证券<select required value={c.symbol} onChange={e=>change(i,{...c,symbol:e.target.value})}><option value="">选择关联证券</option>{topic.companies.map(company=><option key={company.symbol} value={company.symbol}>{company.name} · {company.symbol}</option>)}</select></label><div className="m-form-row"><label>价格类型<select disabled={!!c.mode&&c.mode!=='level'} value={c.interval} onChange={e=>change(i,{...c,interval:e.target.value})}><option value="1d">最近有效日线收盘</option><option value="1m">最近有效分钟柱收盘</option></select></label><label>比较<select value={c.operator} onChange={e=>change(i,{...c,operator:e.target.value})}><option value="gte">大于等于</option><option value="lte">小于等于</option></select></label></div><label>阈值（{c.symbol?instrument(c.symbol).currency:'证券原币'}）<input type="number" min="0.00000001" max="1000000000000" step="any" required value={c.value} onChange={e=>change(i,{...c,value:e.target.value})}/></label><label>触发方式<select aria-label="触发方式" value={c.mode||'level'} onChange={e=>{const {mode,maxGapSeconds,holdSeconds,...base}=c;change(i,e.target.value==='level'?base:{...base,interval:'1m',mode:e.target.value,maxGapSeconds:180,...(e.target.value==='held'?{holdSeconds:180}:{})});}}><option value="level">当前值达到阈值</option><option value="cross">相邻有效采样穿越</option><option value="held">有效采样持续满足</option></select></label>
 {c.mode&&c.mode!=='level'&&<><label>最大采样间隔（秒）<input type="number" min="60" max="600" step="1" required value={c.maxGapSeconds} onChange={e=>change(i,{...c,maxGapSeconds:e.target.value})}/></label>{c.mode==='held'&&<label>持续满足时长（秒）<input type="number" min="60" max="21600" step="1" required value={c.holdSeconds} onChange={e=>change(i,{...c,holdSeconds:e.target.value})}/></label>}<small>只使用本版启用后的新分钟采样。重复不计时；缺失、来源切换、修订、超间隔或跨休市会重建基线。持续仅指已观察样本，不能证明采样之间价格始终满足。组合按同一检查轮判断，穿越不会锁存等待其他条件。</small></>}
 <small>研究缓存不是可成交报价；时区或新鲜度未核验时不判断条件，提醒不执行交易。</small></>}
 {['research-change','counterevidence'].includes(c.type)&&<p>以此次保存时的研究 v{form.topicVersion} 为基线；已有版本和已有反证不重复命中。</p>}
 <Button type="button" disabled={form.conditions.length===1} onClick={()=>update('conditions',form.conditions.filter((_,index)=>index!==i))}>移除条件 {i+1}</Button></fieldset>)}
 <Button type="button" disabled={form.conditions.length>=8} onClick={()=>update('conditions',[...form.conditions,defaults('at')])}>增加一项条件</Button>
 {rule&&<label>变更说明<input required maxLength={500} value={form.note} onChange={e=>update('note',e.target.value)}/></label>}
 <div className="m-form-actions"><Button primary type="submit" disabled={staleTopic||staleRule||locked||topic.status!=='active'}>保存观察条件</Button><Button type="button" onClick={onDone}>返回列表（保留未提交草稿）</Button></div></fieldset></form>;
}
export function ObservationResults({results=[]}){return <ul className="observation-results">{results.map((r,i)=><li key={i}><strong>{i+1}. {{true:'满足',false:'未满足',unknown:'无法判断'}[r.state]} · {r.reason}</strong>{r.input?.statistical&&<StatisticalResult input={r.input}/>} {r.input?.symbol&&!r.input.statistical&&<p>{r.input.symbol} · {r.input.price??'无有效价格'} {r.input.currency} · 阈值 {r.input.operator==='gte'?'≥':'≤'} {r.input.threshold??'—'}<br/>{r.input.provider||'来源未知'} · 数据时点 {r.input.dataAt||'未知'} · 接收 {time(r.input.receivedAt)}{r.input.synthetic?' · 合成演示':' · 研究价格，非成交报价'}</p>}{r.input?.temporal&&<div><p>{r.input.temporal.mode==='cross'?'相邻采样穿越':'采样持续满足'} · 已记录 {r.input.temporal.sampleCount} 个样本 · 最大间隔 {r.input.temporal.maxGapSeconds} 秒{r.input.temporal.observedSeconds!=null?` · 已观察 ${r.input.temporal.observedSeconds} / ${r.input.temporal.holdSeconds} 秒`:''}</p>{r.input.temporal.startedAt&&<p>窗口开始 {time(r.input.temporal.startedAt)}</p>}{r.input.temporal.samples&&<details><summary>查看命中采样依据</summary>{r.input.temporal.samples.map((s,j)=><p key={j}>{s.dataAt} · {s.price} {r.input.currency} · {s.provider}<br/>获取 {s.receivedAt} · 观察 {s.observedAt} · 指纹 {s.quoteHash}</p>)}</details>}</div>}{r.input?.at&&<p>复核时刻 {time(r.input.at)}</p>}{r.input?.currentVersion!==undefined&&<p>基线 v{r.input.baselineVersion} → 当前 v{r.input.currentVersion}</p>}{r.input?.evidence?.map(e=><p key={e.id}>{e.claim} · {e.verification}</p>)}</li>)}</ul>;}
function RuleCard({rule,topic,instanceId,busy,mutate,onEdit}){
 const editor=useEditorDraft({id:rule.id,createdAt:rule.createdAt,version:rule.version},'observation-operation',()=>({note:'',topicVersion:topic?.version??rule.binding.topicVersion}),v=>v&&typeof v.note==='string'&&Number.isSafeInteger(v.topicVersion),instanceId||'local'),note=editor.draft.value.note;
 const [history,setHistory]=useState(null),[error,setError]=useState(''),[saving,setSaving]=useState(false),mounted=useRef(true),flight=useRef(false),sequence=useRef(0);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;sequence.current++;};},[]);
 useEffect(()=>{sequence.current++;setHistory(null);},[rule.version]);
 const stale=editor.draft.base!==rule.version||editor.draft.value.topicVersion!==(topic?.version??rule.binding.topicVersion),locked=busy||saving;
 const state=!rule.active?'已暂停':rule.check?.firstMatchedAt?'已生成待办':{true:'已命中',false:'等待条件',unknown:'无法判断'}[rule.check?.state]||'等待后台检查';
 const action=async value=>{if(busy||flight.current||stale||!note.trim()||value!=='pause'&&topic?.status!=='active')return;
  flight.current=true;setSaving(true);setError('');const submitted=editor.draft;sequence.current++;
  try{const result=await mutate(`/api/observation-rules/${rule.id}`,'PATCH',{version:submitted.base,topicVersion:submitted.value.topicVersion,action:value,note});if(result){const saved=result.observationInbox?.rules?.find(r=>r.id===rule.id);
    if(!saved){if(mounted.current)setError('已收到保存回执，但未能核对配置版本，请刷新列表核对。');return;}
    editor.ack(submitted,{note:'',topicVersion:topic?.version??saved.binding.topicVersion},saved.version);if(mounted.current)setHistory(null);
   }
  }catch(e){if(mounted.current)setError(e.message);}finally{flight.current=false;if(mounted.current)setSaving(false);}
 };
 return <section className="observation-rule"><h3>{rule.definition.label} · v{rule.version}</h3><p>{state} · {rule.definition.join==='all'?'全部满足':'任一满足'} · 研究基线 v{rule.binding.topicVersion}</p><p>{rule.definition.conditions.map(describe).join(' / ')}</p><small>最近检查 {time(rule.check?.checkedAt)}{rule.check?.firstMatchedAt?' · 首次命中 '+time(rule.check.firstMatchedAt):''}</small>{rule.check&&<ObservationResults results={rule.check.results}/>}
 <label>操作说明<input aria-label={`操作说明 ${rule.definition.label}`} maxLength={500} disabled={locked} value={note} onChange={e=>editor.change(v=>({...v,note:e.target.value}))}/></label>{editor.draft.volatile&&<p role="alert">会话存储不可用，操作说明仅在本页面保留。</p>}{stale&&<p role="alert" className="m-warning">操作说明基于配置 v{editor.draft.base} / 研究 v{editor.draft.value.topicVersion}，当前配置 v{rule.version} / 研究 v{topic?.version??rule.binding.topicVersion}；请核对后重新填写。</p>}<Button disabled={locked} onClick={()=>editor.reset()}>丢弃操作说明并载入最新版本</Button><div className="m-form-actions"><Button disabled={locked||topic?.status!=='active'} onClick={onEdit}>编辑条件</Button><Button disabled={locked||stale||!note.trim()||!rule.active&&topic?.status!=='active'} onClick={()=>action(rule.active?'pause':'resume')}>{rule.active?'暂停观察':'恢复观察'}</Button>{rule.active&&<Button disabled={locked||stale||!note.trim()||topic?.status!=='active'} onClick={()=>action('rearm')}>重新监测（新版本）</Button>}<Button disabled={locked} onClick={async()=>{const ticket=++sequence.current;try{const result=await request(`/api/observation-rules/${rule.id}/history`);if(mounted.current&&ticket===sequence.current){setHistory(result);setError('');}}catch(e){if(mounted.current&&ticket===sequence.current)setError(e.message);}}}>配置版本记录</Button></div>{error&&<p role="alert">{error}</p>}{history&&<div>{history.map(r=><details key={r.version}><summary>v{r.version} · {time(r.updatedAt)} · {r.reason}</summary><pre>{JSON.stringify({definition:r.definition,binding:r.binding,active:r.active},null,2)}</pre></details>)}</div>}</section>;
}
export default function ObservationRules(props){return <ObservationRulesBody key={props.data?.runtime?.instance?.id||'local'} {...props}/>;}
function ObservationRulesBody({data,initialTopicId,busy,mutate}){
 const topics=data?.research?.topics||[],[selected,setSelected]=useState(initialTopicId||topics[0]?.id||''),[editing,setEditing]=useState(null),topic=topics.find(t=>t.id===selected),rules=(data?.observationInbox?.rules||[]).filter(r=>r.topicId===selected),rule=rules.find(r=>r.id===editing);
 return <section className="observation-settings" aria-label="观察条件设置"><p>后台检查条件并生成站内待办；不改变研究、风险限额或订单。价格条件不等于买卖建议。{data?.runtime?.offline?'当前为合成演示数据。':''}</p>{editing&&(!topic||editing!=='new'&&!rule)?<><p role="alert">研究或配置已不在当前列表，请返回列表核对；不会自动新建观察条件。</p><Button onClick={()=>setEditing(null)}>返回观察条件列表</Button></>:editing&&topic?<RuleEditor key={JSON.stringify([selected,topic.createdAt,editing,rule?.createdAt])} topic={topic} rule={rule} instanceId={data?.runtime?.instance?.id} busy={busy} mutate={mutate} onDone={()=>setEditing(null)}/>:<><label>选择研究<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">选择一个研究</option>{topics.map(t=><option key={t.id} value={t.id}>{t.title}{t.status==='active'?'':'（已归档）'}</option>)}</select></label><Button primary disabled={busy||topic?.status!=='active'} onClick={()=>setEditing('new')}>添加观察条件</Button>{!rules.length&&<p>此研究尚未配置观察条件。</p>}{rules.map(r=><RuleCard key={JSON.stringify([r.id,r.createdAt])} rule={r} topic={topic} instanceId={data?.runtime?.instance?.id} busy={busy} mutate={mutate} onEdit={()=>setEditing(r.id)}/>)}</>}</section>;
}
