import {securityIdentity} from '../../shared/securities.mjs';
import {dailyHealth,marketClock,CALENDAR_VERSION} from '../../shared/market-clock.mjs';
import React from 'react';
import {Modal} from '../major/Primitives';
import {time} from '../major/api';
import {dataHealth} from './decision-model';
export function HealthStrip({data,onOpen}){
 if(data?.runtime?.offline)return <div className="v7-health" aria-label="数据与研究状态"><span>离线演示 · 外部采集已关闭</span><button onClick={onOpen}>合成日线 {data.watchlist.length} 只 · 不评估交易日新鲜度 <b>查看状态 ↗</b></button></div>;
 const h=dataHealth(data),priority=(data?.workflow||[]).filter(w=>w.priorityRank<=4),expired=data?.paper?.orders.filter(o=>o.status==='expired').length||0;
 return <div className="v7-health" aria-label="数据与研究状态"><span><i className={h.issue?'warning':''}/>{priority.length} 项优先复核</span><span className="v7-mode">{[['600825.SH','A股'],['00293.HK','港股'],['AAPL.US','美股']].map(([s,n])=>`${n} ${marketClock(s).label}`).join(' · ')}</span><button onClick={onOpen}>Reuters {h.rssState} · 日线缓存 {h.dailyCount}/{h.total} · {h.laggingCount||0} 落后交易日{h.failedCount?` · ${h.failedCount} 获取失败`:h.oldCount?` · ${h.oldCount} 旧缓存`:''} <b>查看状态 ↗</b></button>{expired>0&&<span>{expired} 笔申请到期 · 已释放</span>}</div>;
}
export function Operations({data,onClose}){
 if(data?.runtime?.offline)return <Modal title="离线演示数据" onClose={onClose}><p className="m-note">事件、新闻和走势由本地原创示例生成，不是 Reuters 新闻或 Yahoo 行情。未模拟交易所节假日、复权或供应商延迟，不适用行情新鲜度判断。</p><p className="m-note">演示模式禁止服务端外部采集及正文读取。已有演示修改和模拟决定会保留；研究自己的事件请另行启动空白研究模式。</p></Modal>;
 const h=dataHealth(data),lanes={news:'新闻采集',daily:'日线采集',minutes:'分钟采集'};
 return <Modal title="数据与采集状态" onClose={onClose}><p className="m-note">采集成功只表示获取到了数据，不代表实时、完整或已核验。日线接收时间和交易所收盘日分别显示；行情不进入场景净值。</p><h3>Reuters 标题</h3><p>{h.rssState} · 最后成功 {time(h.rssAt)} · 最近尝试 {time(data.checks.news?.attemptedAt)}</p>{data.checks.news?.error&&<p className="m-warning">{data.checks.news.error} · 保留原有新闻</p>}<h3>后台任务</h3><div className="v7-lanes">{Object.entries(lanes).map(([key,name])=>{const state=data.operations?.[key];return <div key={key}><b>{name}</b><span>{state?.running?'采集中':state?.outcome==='partial'?'部分失败':state?.outcome==='error'?'获取失败':state?.outcome==='skipped'?'无需重复获取':state?.outcome==='ok'?'获取完成':'尚未运行'}</span><small>{state?.completedAt?`成功 ${state.succeeded||0} / 失败 ${state.failed||0} / 跳过 ${state.skipped||0}`:'等待任务'}</small><small>{state?.error||`结束 ${time(state?.completedAt)}`}</small></div>;})}</div><p className="m-note">日历 {CALENDAR_VERSION}：覆盖2026年普通股票，含常规休市与半日市；不判断个股停牌、临时休市或互联互通资格。证券按交易所及代码区分；A/H/ADR 的发行人关系只采用已有手工表，美股交易所和未映射关系仍待核验，不按名称合并。收盘后30分钟是本地研究缓冲，不能保证上游已给最终价。</p><h3>重点股票日线 · {h.dailyCount}/{h.total}</h3><table className="i-table"><thead><tr><th>证券</th><th>最近收盘日</th><th>接收时间</th><th>市场状态 / 应有收盘日</th><th>状态</th></tr></thead><tbody>{data.watchlist.map(w=><tr key={w.symbol}><td>{w.symbol}<small className="v8-security-id">{securityIdentity(w.symbol).currency} · {securityIdentity(w.symbol).venue}<br/>{securityIdentity(w.symbol).listing} · {securityIdentity(w.symbol).relationStatus}</small></td><td>{w.daily?.lastDate||'—'}</td><td>{time(w.daily?.receivedAt)}</td><td>{marketClock(w.symbol).label} · {dailyHealth(w.symbol,w.daily).expectedDate||'日历待补'}</td><td>{data.checks['daily:'+w.symbol]?.state==='error'?'更新失败，保留缓存':`${dailyHealth(w.symbol,w.daily).label}；供应商延迟未核验`}</td></tr>)}</tbody></table><p className="m-note">新闻、日线与分钟独立调度，同一任务未结束时不重复启动。无行情时不补造曲线；本地连接正常不等于上游数据正常。</p></Modal>;
}
