import React,{useState} from 'react';
import {Button} from '../major/Primitives';
import {usd,number,names} from './format';
import {time} from '../major/api';
export function AccountStrip({book}){
 return <><div className="i-account"><div><small>初始资金 · USD</small><strong>{usd(book.initial)}</strong></div><div><small>演练净值</small><strong>{usd(book.nav)} <em className={book.pnl>=0?'up':'down'}>{book.returnPct.toFixed(2)}%</em></strong></div><div><small>现金 / 可用</small><strong>{usd(book.cash)}<em>{usd(book.available)}</em></strong></div><div><small>持仓 / 待批占用</small><strong>{book.exposurePct.toFixed(1)}%<em>{usd(book.reserved)}</em></strong></div><div className="i-account-mode"><b>结构演练</b><span>初始化样例 · 人工批准模拟</span><small>场景价格 + 固定 FX · {time(book.updatedAt)}</small></div></div><div className="i-allocation-strip"><span style={{width:`${book.exposurePct}%`}}>持仓 {book.exposurePct.toFixed(1)}%</span><span style={{width:`${100-book.exposurePct}%`}}>现金 {(100-book.exposurePct).toFixed(1)}%</span></div></>;
}
export function DecisionQueue({initialScope='topic',book,topics,selectedTopic,workflow,onTopic,onReview,onDecision,onParams,onRecords}){
 const [scope,setScope]=useState(initialScope);
 const allOrders=book.orders.filter(o=>o.status==='pending').sort((a,b)=>Number(b.topicId===selectedTopic)-Number(a.topicId===selectedTopic));
 const orders=scope==='all'?allOrders:allOrders.filter(o=>o.topicId===selectedTopic);
 const urgent=workflow.filter(w=>w.positionSymbols?.length&&w.priorityRank<=4).sort((a,b)=>a.priorityRank-b.priorityRank);
 return <aside id="v6-decisions" className="i-decision i-panel"><div className="i-section-head"><h2>{scope==='topic'?'本事件行动':'全局行动'} <em>{orders.length}</em></h2><Button onClick={onRecords}>历史记录</Button></div><div className="v8-queue-tabs"><button aria-pressed={scope==='topic'} onClick={()=>setScope('topic')}>本事件 {allOrders.filter(o=>o.topicId===selectedTopic).length}</button><button aria-pressed={scope==='all'} onClick={()=>setScope('all')}>全部 {allOrders.length}</button></div>{urgent.length>0&&<div className="v8-global-alert"><b>全局风险 {urgent.length}</b><button onClick={()=>setScope('all')}>查看相关持仓 ↗</button></div>}<div className="i-orders">{(scope==='all'?urgent:urgent.filter(w=>w.topicId===selectedTopic)).map(w=><article className="v7-risk-review" key={w.topicId}><b>{w.priorityReason}</b><span>{w.positionSymbols.join(' · ')}</span><Button onClick={()=>{onTopic(w.topicId);onReview(book.positions.find(p=>p.symbol===w.positionSymbols[0]));}}>复核持仓</Button></article>)}<p className="v7-queue-scope">本事件 {orders.filter(o=>o.topicId===selectedTopic).length} 笔 · 全部 {allOrders.length} 笔待批</p>{orders.map(o=><article key={o.id} className={`i-order ${o.topicId===selectedTopic?'related':''}`} title={o.reason}><div><button className="v7-order-symbol" onClick={()=>onTopic(o.topicId,o.symbol)}>{o.symbol}</button><span className={o.side==='sell'?'down':'up'}>{names[o.side]}</span><em className="amber">{o.stale?'需重建':o.topicId===selectedTopic?'本事件':'待确认'}</em></div><p>{usd(o.estimate.total)} · {o.qty} 股 · 场景价 {number(o.price)} {o.estimate.currency}</p><div className="i-order-bottom"><span className={o.errors.length||o.stale?'down':'i-muted'}>{o.stale?'研究版本已变化':o.errors[0]||`冻结研究 v${o.topicVersion} · 到期 ${time(o.expiresAt)}`}</span><Button primary onClick={()=>onDecision(o)}>审核</Button></div></article>)}{!orders.length&&<p className="i-note">{scope==='topic'?'本事件暂无待批申请。可在关联公司卡片拟申请；保存研究不等于下单。':'暂无有效待批申请。过期记录保留在历史中，未执行占用已释放。'}</p>}</div><div className="i-section-head"><h2>组合约束</h2><Button onClick={onParams}>调整参数</Button></div><div className="i-rule-checks"><div><span>现金底线</span><b>{book.params.cashFloorPct}%</b><em>{(book.cash/book.nav*100).toFixed(1)}% 当前</em></div><div><span>同一发行人（A/H 合并）</span><b>≤ {book.params.issuerCapPct}%</b></div><div><span>主题上限（含待批）</span><b>≤ {book.params.themeCapPct}%</b></div><div><span>演练费率 / 滑点</span><b>{book.params.feeBps} / {book.params.slippageBps} bp</b></div></div><div className="i-exposure" title="同主题多公司仍可能同涨同跌；申请计入现金与集中度检查"><h3>已持仓主题敞口</h3>{Object.entries(book.themes).map(([id,value])=><div key={id}><span>{topics.find(t=>t.id===id)?.label||'初始化观察'}</span><i><b style={{width:`${Math.min(100,value/book.nav*100/book.params.themeCapPct*100)}%`}}/></i><code>{(value/book.nav*100).toFixed(1)}%</code></div>)}</div><p className="i-note">同主题多公司仍可能同涨同跌；申请会计入现金与集中度检查。</p></aside>;
}
export function Holdings({book,topics,watch,selectedTopic,selectedSymbol,onSelect,onSell,onReview,onRecords}){
 const [showMarket,setShowMarket]=useState(false);
 return <section id="v6-holdings" className="i-holdings i-panel"><div className="i-section-head"><h2>模拟持仓 <em>{book.positions.length}</em></h2><span className="amber">高亮当前研究关联 · 结构演练</span><Button onClick={()=>setShowMarket(!showMarket)}>{showMarket?'隐藏市场参照':'显示市场参照'}</Button><small>已实现 {usd(book.realized)} · 累计费用 {usd(book.fees)}</small><Button onClick={onRecords}>成交 / 复核记录</Button></div><div className="i-holdings-scroll"><table className="i-table"><thead><tr><th>公司 / 代码</th><th>研究绑定</th><th className="num">数量</th><th className="num">原币成本</th><th className="num">演练估值价</th>{showMarket&&<th className="num">市场参照 · 不计盈亏</th>}<th className="num">演练市值 USD</th><th className="num">占比</th><th className="num">浮盈亏 USD</th><th>复核</th><th>操作</th></tr></thead><tbody>{book.positions.map(p=>{const t=topics.find(t=>t.id===p.topicId),last=book.reviews.filter(r=>r.symbol===p.symbol).at(-1),live=watch.find(w=>w.symbol===p.symbol)?.quote;return <tr key={p.symbol} className={p.symbol===selectedSymbol?'v7-selected-holding':p.topicId===selectedTopic?'v7-related-holding':''}><td><button onClick={()=>onSelect(p)}><b>{p.name}</b><small>{p.symbol}</small></button></td><td title={t?.title}>{t?.label||'样例观察'} · v{p.researchVersion??'—'}<small>{t?.version!==p.reviewedResearchVersion?'研究更新，需复核':`已核对 v${p.reviewedResearchVersion} · 建仓依据保留`}</small></td><td className="num">{number(p.qty,0)}</td><td className="num">{number(p.avgNative)} <small>{p.currency}</small></td><td className="num">{number(p.scenarioPrice)}<small>{p.currency} · 场景价</small></td>{showMarket&&<td className="num">{live?number(live.last):'无行情'}<small>{live?`${live.providerTime} ${live.providerTimezone}`:'待获取'}</small></td>}<td className="num">{usd(p.valueUSD)}</td><td className="num">{(p.valueUSD/book.nav*100).toFixed(1)}%</td><td className={`num ${p.unrealized>=0?'up':'down'}`}>{number(p.unrealized)}<small>{p.returnPct.toFixed(2)}%</small></td><td><button className={last?.result==='invalidated'?'down':''} onClick={()=>onReview(p)}>{last?names[last.result]:'待首次复核'}</button></td><td><Button onClick={()=>onSell(p)}>减仓</Button></td></tr>;})}</tbody></table></div><div className="i-holdings-foot"><span>USD 基准 · 固定演练汇率：1 USD = {book.params.fx.CNY} CNY / {book.params.fx.HKD} HKD · 非实时汇率</span><span>组合 v{book.version} · {time(book.updatedAt)}</span></div></section>;
}
