import React,{useState} from 'react';
import {Modal,Button} from '../major/Primitives';
import {time} from '../major/api';
import {usd,number,names} from './format';
export function Proposal({book,topic,workflow,symbol,side,onClose,mutate,busy}){
 const position=book.positions.find(p=>p.symbol===symbol),[base]=useState(book.version),[researchVersion]=useState(topic.version),[clientId]=useState(()=>crypto.randomUUID());
 const [form,setForm]=useState({qty:side==='sell'?Math.max(1,Math.floor((position?.qty||1)/4)):100,price:book.prices[symbol]||0,limit:(book.prices[symbol]||0)*(side==='sell'?.98:1.02),reason:'',holdingHorizon:topic.hypothesis.holdingHorizon||'',invalidation:topic.hypothesis.invalidation||''});
 const update=(key,value)=>setForm(v=>({...v,[key]:value}));
 return <Modal title={`${side==='sell'?'拟减仓':'拟建仓 / 增仓'} · ${symbol}`} onClose={onClose}><form className="m-form" onSubmit={async e=>{e.preventDefault();if(await mutate('/api/paper/proposals','POST',{...form,version:base,topicVersion:researchVersion,topicId:topic.id,symbol,side,clientId}))onClose();}}><p className="m-warning">结构演练：已建场景的参考价与估值价保持一致，不能单独改申请价。新证券首次设定场景价；限价仍可调整。提交后等待你本人批准，市场行情不进入演练净值。</p><p>{topic.title} · 冻结研究 v{researchVersion}</p><ResearchGaps workflow={workflow}/><div className="m-form-row">{[['qty','股数'],['price','场景参考价（原币）'],['limit',side==='sell'?'最低接受价':'最高接受价']].map(([k,l])=><label key={k}>{l}<input required type="number" min={k==='qty'?1:.0001} max="10000000" step={k==='qty'?1:'any'} value={form[k]} readOnly={k==='price'&&!!book.prices[symbol]} onChange={e=>update(k,Number(e.target.value))}/></label>)}</div><label>本次申请依据<textarea required maxLength={1000} rows={3} value={form.reason} onChange={e=>update('reason',e.target.value)} placeholder="变化是什么、公司如何受影响、为什么现在处理？"/></label><label>预期持有期 / 下一次检查<input required maxLength={200} value={form.holdingHorizon} onChange={e=>update('holdingHorizon',e.target.value)}/></label><label>反证与失效条件<textarea required maxLength={1000} rows={3} value={form.invalidation} onChange={e=>update('invalidation',e.target.value)}/></label><p className="m-note">申请 24 小时后失效；现金、发行人、主题预算均含其他待批申请。过期或拒绝后自动释放未执行占用。三市场真实成交规则尚未接入。</p>{(base!==book.version||researchVersion!==topic.version)&&<p className="m-warning">组合或研究已有更新，请关闭后重新核对。</p>}<Button primary disabled={busy||base!==book.version||researchVersion!==topic.version}>提交模拟申请</Button></form></Modal>;
}
export function Decision({book,order,workflow,onClose,mutate,busy}){
 const [version]=useState(book.version),[confirmed,setConfirmed]=useState(false),[note,setNote]=useState('');
 const stale=version!==book.version,blocked=order.status!=='pending'||stale||order.stale||order.expired||order.errors.length>0;
 async function decide(decision){if(await mutate(`/api/paper/orders/${order.id}`,'POST',{version,decision,confirmScenario:confirmed,note}))onClose();}
 return <Modal title={`审核模拟申请 · ${order.symbol}`} onClose={onClose}><div className="m-form"><p className="m-warning">这是结构演练。下方场景价、假设汇率和简化即时成交用于检查产品流程，不是实时市场成交或投资建议。</p><ResearchGaps workflow={workflow}/><div className="i-approval-stats"><div><small>{names[order.side]}数量</small><b>{order.qty} 股</b></div><div><small>预估{order.side==='buy'?'支出':'回款'}（含费）</small><b>{usd(order.estimate.total)}</b></div><div><small>滑点后场景价格</small><b>{number(order.estimate.execution,4)} {order.estimate.currency}</b></div><div><small>费用 / 汇率</small><b>{usd(order.estimate.fee)} / {order.estimate.fx}</b></div></div><p><b>依据：</b>{order.reason}</p><p><b>持有期：</b>{order.holdingHorizon}</p><p><b>失效：</b>{order.invalidation}</p><p className="m-note">研究 v{order.topicVersion} · 到期 {time(order.expiresAt)} · 组合 v{version}</p>{blocked&&<p className="m-warning">{stale?'组合已更新，请重新打开审核。':order.stale?'研究版本变化，请拒绝后按新研究重建。':order.expired?'申请已过期，占用已释放，请重建。':order.errors.join('；')}</p>}<label>决策备注<input value={note} maxLength={1000} onChange={e=>setNote(e.target.value)}/></label><label className="i-checkbox"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>我已核对场景参数，确认仅在模拟账本执行</label><div className="m-form-actions"><Button disabled={busy||stale||order.status!=='pending'} onClick={()=>decide('reject')}>拒绝申请</Button><Button primary disabled={busy||blocked||!confirmed} onClick={()=>decide('approve')}>批准模拟{order.side==='buy'?'买入':'卖出'}</Button></div></div></Modal>;
}
export function Parameters({book,onClose,busy,mutate}){
 const [base]=useState(book.version),[form,setForm]=useState(book.params);
 return <Modal title="组合演练参数" onClose={onClose}><form className="m-form" onSubmit={async e=>{e.preventDefault();if(await mutate('/api/paper/params','PATCH',{...form,version:base}))onClose();}}><p className="m-note">当前数值是用于检验结构的可调整默认值，不代表已验证的最优策略。更改后，待批申请会重新检查约束。</p>{[['cashFloorPct','最低现金比例 %'],['issuerCapPct','同一发行人上限 %（含 A/H）'],['themeCapPct','主题预算上限 %'],['feeBps','演练费率 bp'],['slippageBps','演练滑点 bp']].map(([k,l])=><label key={k}>{l}<input type="number" required min="0" max="100" step="any" value={form[k]} onChange={e=>setForm(v=>({...v,[k]:Number(e.target.value)}))}/></label>)}<p className="m-note">成本汇率已冻结：1 USD = {book.params.fx.CNY} CNY / {book.params.fx.HKD} HKD。实时汇率与真实费用表待接入。</p><Button primary disabled={busy||base!==book.version}>保存参数版本</Button></form></Modal>;
}
export function Review({book,position,onClose,onExit,busy,mutate}){
 const [base]=useState(book.version),[topicVersion]=useState(position.currentResearchVersion),[result,setResult]=useState('verify'),[note,setNote]=useState('');
 return <Modal title={`持仓临时复核 · ${position.symbol}`} onClose={onClose}><form className="m-form" onSubmit={async e=>{e.preventDefault();if(await mutate('/api/paper/review','POST',{version:base,topicVersion,symbol:position.symbol,result,note})){onClose();if(result==='invalidated')onExit(position);}}}><p className="m-note">传闻也可能需要防御：评估可信度、潜在损失和持仓敞口后决定是否提出减仓申请。保存复核本身不会卖出。</p><p className="m-note">本次复核研究 v{topicVersion}；原建仓依据 v{position.researchVersion} 保留。新版本或新反证会再次提醒。</p><label>结论<select value={result} onChange={e=>setResult(e.target.value)}>{['verify','intact','weakened','invalidated'].map(v=><option key={v} value={v}>{names[v]}</option>)}</select></label><label>新增事实、来源与对原逻辑的影响<textarea required maxLength={1000} rows={5} value={note} onChange={e=>setNote(e.target.value)}/></label>{topicVersion!==position.currentResearchVersion&&<p className="m-warning">研究已有更新，请重新打开复核。</p>}<Button primary disabled={busy||base!==book.version||topicVersion!==position.currentResearchVersion}>{result==='invalidated'?'保存复核并拟减仓':'保存复核'}</Button></form></Modal>;
}
export function Records({book,onClose}){
 return <Modal title="模拟成交与复核记录" onClose={onClose}><p className="m-note">初始化持仓独立于成交记录；本页均为场景演练，未接真实券商。</p><h3>申请记录</h3><div className="i-records">{[...book.orders].reverse().map(o=><article key={o.id}><b>{o.symbol} · {names[o.side]} {o.qty} 股 · {names[o.status]}</b><p>{o.reason}</p><small>研究 v{o.topicVersion} · {time(o.closedAt||o.decidedAt||o.createdAt)} · {o.decisionNote||'等待本人决定'}</small></article>)}</div><h3>成交记录</h3>{book.fills.length?book.fills.map(f=><p key={f.id}>{time(f.at)} · {f.symbol} · {names[f.side]} {f.qty} 股 · {number(f.execution,4)} {f.currency} · 费用 {usd(f.fee)} · 研究 v{f.topicVersion}</p>):<p className="m-note">尚无批准成交。</p>}<h3>持仓复核</h3>{book.reviews.length?[...book.reviews].reverse().map(r=><p key={r.id}><b>{r.symbol} · {names[r.result]}</b> · 复核研究 v{r.reviewedResearchVersion??'旧记录未绑定'} · {time(r.at)}<br/>{r.note}</p>):<p className="m-note">尚无临时复核。</p>}</Modal>;
}

function ResearchGaps({workflow}){return <div className="v7-research-gaps"><b>研究状态 · {workflow?.stage||'待核验'}</b><p>{workflow?.assessmentLabel||'消息状态待评估'} · 核心主张概率 {workflow?.assessment?.probability==null?'待评估':workflow.assessment.probability+'%（主观）'}</p><p>{workflow?.priorityReason} · {workflow?.coverage?.against||0} 条反证</p>{workflow?.assessment&&<details><summary>概率依据与真伪两种影响</summary><p>主张：{workflow.assessment.claim} · 截止 {workflow.assessment.resolveBy||'待定'}</p><p>依据：{workflow.assessment.basis||'待评估'}</p><p>若属实：{workflow.assessment.impactIfTrue||'待评估'}</p><p>未兑现：{workflow.assessment.impactIfFalse||'待评估'}</p></details>}{workflow?.blockers?.length>0&&<ul>{workflow.blockers.map(v=><li key={v}>{v}</li>)}</ul>}<small>研究缺口供本人审核；本操作仍仅为结构演练，不代表已生成有效交易信号。</small></div>;}
