import React,{useEffect,useState} from 'react';
import {request} from '../major/api';
import {Button} from '../major/Primitives';
import {EventTime} from '../major/MaterialEvents';
export default function SemanticEventLibrary({onSelect}){
 const [q,setQ]=useState(''),[offset,setOffset]=useState(0),[result,setResult]=useState(null),[error,setError]=useState('');
 useEffect(()=>{let live=true;setResult(null);setError('');const timer=setTimeout(()=>request(`/api/semantic-events/events?${new URLSearchParams({q,offset:String(offset),limit:'20'})}`).then(r=>{if(live)setResult(r);}).catch(e=>{if(live)setError(e.message);}),200);return()=>{live=false;clearTimeout(timer);};},[q,offset]);
 return <section aria-label="已建立的事项研究"><p>选择从材料拆分建立的事项；系统判断与本人处理保留各自来源。只比较指定事项，原材料作为上下文；同篇文章中的不同事项保留各自身份。来源修订后旧事项需重新核对。</p><label>搜索事项标题<input maxLength={200} value={q} onChange={e=>{setQ(e.target.value);setOffset(0);}}/></label>{error&&<p role="alert" className="m-warning">{error}</p>}{!result&&!error&&<p>正在读取事项…</p>}{result&&<><p>共 {result.total} 项 · 显示 {result.items.length} 项</p>{result.items.map(m=><article className="source-item" key={m.id}><h4>{m.eventFocus?.title||m.title}</h4>{m.selectable?<><p>{m.eventFocus.actor} · {m.eventFocus.action} · {m.eventFocus.object} · {m.eventFocus.stage}</p><blockquote>{m.eventFocus.quote}</blockquote><EventTime event={m.eventFocus}/><p>原材料：{m.sourceTitle} · 材料 v{m.materialRevision} · 事项 v{m.revision}</p></>:<p className="m-warning">{m.unavailableReason}</p>}<Button disabled={!m.selectable} onClick={()=>onSelect(m)}>选择事项：{m.eventFocus?.title||m.title}</Button></article>)}{!result.items.length&&<p>没有匹配的事项。先在研究材料中拆分并核对建立研究。</p>}<div className="event-actions"><Button disabled={!offset} onClick={()=>setOffset(v=>Math.max(0,v-20))}>上一页事项</Button><Button disabled={offset+result.items.length>=result.total} onClick={()=>setOffset(v=>v+20)}>下一页事项</Button></div></>}</section>;
}
export function EventFocus({input}){
 if(!input.eventFocus)return null;return <aside className="source-item"><strong>本次限定事项：{input.eventFocus.title}</strong><p>{input.eventFocus.actor} · {input.eventFocus.action} · {input.eventFocus.object} · {input.eventFocus.stage}</p><blockquote>{input.eventFocus.quote}</blockquote><EventTime event={input.eventFocus}/><p>{input.eventProvenance.actor?.kind==='system'?'系统范围判断':'本人范围核对'}：{input.eventProvenance.reviewNote}。原拆分仍是待核对判断，原文及其他事项不能替换本次范围。</p></aside>;
}
