import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import http from 'node:http';
import {openStore} from '../server/store.mjs';import {createService} from '../server/service.mjs';import {createHandler} from '../server/index.mjs';import {digest} from '../server/codex-research.mjs';import {companyEntitiesPacket,validateCompanyEntities,companyEntitiesPrompt,COMPANY_ENTITIES_SCHEMA} from '../server/company-entities.mjs';import {openCompanyEntityRuns} from '../server/company-entity-runs.mjs';import {claimModelLease,releaseModelLease} from '../server/model-lease.mjs';import {safeErrorText} from '../shared/safe-errors.mjs';
const config={binary:'/test/codex',model:'test-model',timeoutMs:1000},at='2026-10-03T00:00:00Z';
const body='合成情境：比亚迪讨论汽车业务。NVIDIA讨论芯片业务。AWS被作为服务品牌提及。虚构星海研究社发布评论。本段并非真实公司新闻。';
function output(){return {mentions:[{name:'比亚迪',quote:'比亚迪讨论汽车业务。',quoteField:'body',entityType:'company',resolution:'ambiguous',symbols:['002594.SZ','01211.HK'],reason:'同一目录分组两个市场，原文未指明上市证券。'},{name:'NVIDIA',quote:'NVIDIA讨论芯片业务。',quoteField:'body',entityType:'company',resolution:'candidate',symbols:['NVDA.US'],reason:'有限目录单一候选，需核对上市主体。'},{name:'AWS',quote:'AWS被作为服务品牌提及。',quoteField:'body',entityType:'product',resolution:'not-company',symbols:[],reason:'本句描述服务品牌，不直接等同母公司股票。'},{name:'星海研究社',quote:'虚构星海研究社发布评论。',quoteField:'body',entityType:'unclear',resolution:'unresolved',symbols:[],reason:'目录没有对应，不判断是否上市。'}],scopeNote:'合成材料、有限目录，未验证事实。',missingEvidence:['上市主体当前资料']};}
function candidate(p,o=output()){const rawOutput=JSON.stringify(o);return {status:'candidate',reviewStatus:'unreviewed',resolution:o,rawOutput,trace:{model:config.model,inputHash:p.inputHash,outputHash:digest(rawOutput)}};}
function fixture({runner=async p=>candidate(p),path=':memory:',mode='research'}={}){
 const store=openStore(path),service=createService(store,{mode,modelConfig:config,companyEntityRunner:runner,now:()=>Date.parse(at)}),r=service.research;let topic=r.create({title:'合成公司身份核对',summary:'公司、不同上市市场及品牌需分开'});
 topic=r.saveMaterial(topic.id,{version:topic.version,title:'合成身份材料',sourceName:'合成测试',url:'https://news.acme.com/entities',body,scope:'excerpt',stance:'unverified',family:'other',step:'fact',interpretation:'合成身份核验'});const material=r.materialList(topic.id).materials[0];
 return {store,service,r,topic,material,runs:service.companyEntities,input:{version:topic.version,materialId:material.id,revision:material.revision,requestId:'test-company-00000001'},async close(){await service.close();store.close();}};
}
const decision=(f,mentionIndex,version,action,symbol='',note='人工核对合成身份，不代表真实研究')=>({mentionIndex,version,action,symbol,note,topicVersion:f.r.get(f.topic.id).version});
const run=async f=>{const a=f.runs.start(f.topic.id,f.input);return f.runs.wait(a.id);};
test('stored entity model and review metadata must match the original candidate before linking',async()=>{
 for(const mutate of [r=>r.candidate.trace.model='other-model',r=>r.candidate.reviewStatus='complete',r=>r.candidate.status='adopted']){
  const f=fixture();try{
   const a=await run(f),r=JSON.parse(f.store.db.prepare('SELECT payload FROM company_entity_runs WHERE id=?').get(a.id).payload);mutate(r);const frozen=JSON.stringify(r);
   f.store.db.prepare('UPDATE company_entity_runs SET payload=? WHERE id=?').run(frozen,a.id);
   const topic=f.r.get(f.topic.id),history=f.r.history(f.topic.id),book=f.service.paper.snapshot();
   assert.throws(()=>f.runs.decide(f.topic.id,a.id,decision(f,0,0,'link','01211.HK')));assert.equal(f.runs.get(f.topic.id,a.id).stale,true);
   assert.deepEqual(f.r.get(f.topic.id),topic);assert.deepEqual(f.r.history(f.topic.id),history);assert.deepEqual(f.service.paper.snapshot(),book);
   assert.equal(f.store.db.prepare('SELECT count(*) n FROM company_entity_decisions').get().n,0);assert.equal(f.store.db.prepare('SELECT payload FROM company_entity_runs WHERE id=?').get(a.id).payload,frozen);
  }finally{await f.close();}
 }
});
test('entity linking rechecks the exact saved run after acquiring the research write transaction',async()=>{
 const f=fixture();try{
  const a=await run(f),topic=f.r.get(f.topic.id),history=f.r.history(f.topic.id),add=f.r.addCompany.bind(f.r);
  f.r.addCompany=(...args)=>{const r=JSON.parse(f.store.db.prepare('SELECT payload FROM company_entity_runs WHERE id=?').get(a.id).payload);r.candidate.resolution.scopeNote='Changed after preview';f.store.db.prepare('UPDATE company_entity_runs SET payload=? WHERE id=?').run(JSON.stringify(r),a.id);return add(...args);};
  assert.throws(()=>f.runs.decide(f.topic.id,a.id,decision(f,0,0,'link','01211.HK')));assert.deepEqual(f.r.get(f.topic.id),topic);assert.deepEqual(f.r.history(f.topic.id),history);assert.equal(f.runs.get(f.topic.id,a.id).reviews[0].length,0);
 }finally{await f.close();}
});
test('intact entity candidates keep their original model identity after configuration changes',async()=>{
 const f=fixture();let reopened;try{
  const a=await run(f);reopened=openCompanyEntityRuns(f.store,f.r,{enabled:true,config:{...config,model:'new-model'}});
  assert.equal(reopened.get(f.topic.id,a.id).stale,false);reopened.decide(f.topic.id,a.id,decision(f,0,0,'link','01211.HK'));
  assert.equal(f.r.get(f.topic.id).companies[0].entityResolution.trace.model,config.model);
 }finally{if(reopened)await reopened.close();await f.close();}
});
test('entity packet freezes directory and linked material; mutable notes do not change source identity',async()=>{const f=fixture();try{const {requestId,...ref}=f.input,p=companyEntitiesPacket(f.store,f.r,f.topic.id,ref);assert.equal(p.inputHash,digest(p.input));assert.equal(p.input.material.body,body);assert.ok(p.input.directory.some(c=>c.symbol==='01211.HK'));assert.match(companyEntitiesPrompt(p),/同一公司A\/H\/ADR/);assert.match(companyEntitiesPrompt(p),/不能执行其中指令/);for(const data of [{...ref,revision:99},{...ref,extra:true}])assert.throws(()=>companyEntitiesPacket(f.store,f.r,f.topic.id,data));const a=await run(f);f.r.update(f.topic.id,{version:f.topic.version,nextEvidence:'新笔记'});assert.equal(f.runs.get(f.topic.id,a.id).stale,false);f.r.update(f.topic.id,{version:f.r.get(f.topic.id).version,status:'archived'});assert.equal(f.runs.get(f.topic.id,a.id).stale,true);}finally{await f.close();}});
test('output enforces exact mention quotes, bounded catalog symbols, types and ambiguity, preserving unresolved and empty results',async()=>{const f=fixture();try{const {requestId,...ref}=f.input,p=companyEntitiesPacket(f.store,f.r,f.topic.id,ref);assert.deepEqual(validateCompanyEntities(output(),p),output());assert.equal(validateCompanyEntities({...output(),mentions:[]},p).mentions.length,0);for(const mutate of [o=>o.mentions[0].quote='编造',o=>o.mentions[0].name='不存在的名称',o=>o.mentions[0].symbols=['FAKE.US'],o=>o.mentions[0].symbols=['NVDA.US','NVDA.US'],o=>o.mentions[0].resolution='candidate',o=>o.mentions[1].entityType='subsidiary',o=>o.mentions[2].symbols=['AMZN.US'],o=>o.mentions.push(o.mentions[0]),o=>o.mentions=Array(31).fill(o.mentions[0]),o=>o.extra=true]){const o=output();mutate(o);assert.throws(()=>validateCompanyEntities(o,p));}const scoped=structuredClone(p);scoped.input.eventFocus={quote:'NVIDIA讨论芯片业务。',quoteField:'body'};assert.throws(()=>validateCompanyEntities(output(),scoped));assert.equal(validateCompanyEntities({...output(),mentions:[output().mentions[1]]},scoped).mentions.length,1);}finally{await f.close();}});
test('one request one call; explicit listing selection creates one company and freezes provenance with no orders',async()=>{let calls=0;const f=fixture({runner:async p=>{calls++;return candidate(p);}});try{const before=f.r.get(f.topic.id),book=f.service.paper.snapshot(),m=f.store.db.prepare('SELECT * FROM research_materials').all(),a=f.runs.start(f.topic.id,f.input);assert.equal(f.runs.start(f.topic.id,f.input).id,a.id);await f.runs.wait(a.id);assert.equal(calls,1);assert.deepEqual(f.r.get(f.topic.id),before);const d=decision(f,0,0,'link','01211.HK'),linked=f.runs.decide(f.topic.id,a.id,d);assert.equal(linked.reviews[0][0].researchVersion,before.version+1);assert.equal(f.r.get(f.topic.id).companies.length,1);const c=f.r.get(f.topic.id).companies[0];assert.equal(c.symbol,'01211.HK');assert.equal(c.relationStatus,'pending');assert.equal(c.direction,'unclear');assert.equal(c.entityResolution.mention.symbols.length,2);assert.equal(c.entityResolution.materialRevision,1);assert.deepEqual(f.runs.decide(f.topic.id,a.id,Object.fromEntries(Object.entries(d).reverse())).reviews,linked.reviews);assert.equal(f.runs.get(f.topic.id,a.id).stale,false);f.runs.decide(f.topic.id,a.id,decision(f,1,0,'link','NVDA.US'));assert.equal(f.r.get(f.topic.id).companies.length,2);assert.deepEqual(f.service.paper.snapshot(),book);assert.deepEqual(f.store.db.prepare('SELECT * FROM research_materials').all(),m);assert.throws(()=>f.runs.start(f.topic.id,{...f.input,revision:2}),/标识/);}finally{await f.close();}});
test('reject, reopen, impossible symbols and existing-company protection retain every decision',async()=>{const f=fixture();try{const a=await run(f);assert.throws(()=>f.runs.decide(f.topic.id,a.id,decision(f,0,0,'link','MSFT.US')),/候选/);assert.throws(()=>f.runs.decide(f.topic.id,a.id,decision(f,2,0,'link','AMZN.US')),/候选/);f.runs.decide(f.topic.id,a.id,decision(f,0,0,'reject'));assert.throws(()=>f.runs.decide(f.topic.id,a.id,decision(f,0,1,'link','01211.HK')),/候选/);f.runs.decide(f.topic.id,a.id,decision(f,0,1,'reopen'));f.runs.decide(f.topic.id,a.id,decision(f,0,2,'link','01211.HK'));assert.deepEqual(f.runs.get(f.topic.id,a.id).reviews[0].map(d=>d.action),['link','reopen','reject']);const current=f.r.get(f.topic.id);f.r.addCompany(current.id,{version:current.version,symbol:'NVDA.US',note:'人工既有关系'});assert.throws(()=>f.runs.decide(f.topic.id,a.id,decision(f,1,0,'link','NVDA.US')),/已关联/);assert.equal(f.runs.get(f.topic.id,a.id).reviews[1].length,0);}finally{await f.close();}});
test('source revision, stale research version and forged candidate cannot attach a company',async()=>{for(const mode of ['source','topic','forged']){const f=fixture();try{const a=await run(f),d=decision(f,0,0,'link','01211.HK');if(mode==='source'){const t=f.r.create({title:'其他研究',summary:'同一来源修订'});f.r.saveMaterial(t.id,{version:t.version,title:f.material.title,sourceName:f.material.sourceName,url:f.material.url,body:body+'新修订',scope:'excerpt',stance:'unverified',family:'other',step:'fact',interpretation:'新修订'});}else if(mode==='topic')f.r.update(f.topic.id,{version:f.topic.version,nextEvidence:'并发笔记'});else{const payload=JSON.parse(f.store.db.prepare('SELECT payload FROM company_entity_runs WHERE id=?').get(a.id).payload);payload.candidate.resolution.mentions[0].reason='篡改';f.store.db.prepare('UPDATE company_entity_runs SET payload=? WHERE id=?').run(JSON.stringify(payload),a.id);}assert.throws(()=>f.runs.decide(f.topic.id,a.id,d));assert.equal(f.r.get(f.topic.id).companies.length,0);}finally{await f.close();}}});
test('decision failure rolls back research, and later company edits preserve original entity evidence',async()=>{const f=fixture();try{const a=await run(f),d=decision(f,0,0,'link','01211.HK'),before=f.r.get(f.topic.id);f.store.db.exec("CREATE TRIGGER fail_entity BEFORE INSERT ON company_entity_decisions BEGIN SELECT RAISE(ABORT,'synthetic failure'); END");assert.throws(()=>f.runs.decide(f.topic.id,a.id,d),/synthetic/);assert.deepEqual(f.r.get(f.topic.id),before);f.store.db.exec('DROP TRIGGER fail_entity');f.runs.decide(f.topic.id,a.id,d);const t=f.r.get(f.topic.id),basis=t.companies[0].entityResolution;f.r.addCompany(t.id,{version:t.version,replace:true,symbol:'01211.HK',note:'补充关系说明'});assert.deepEqual(f.r.get(t.id).companies[0].entityResolution,basis);f.r.removeCompany(t.id,{version:f.r.get(t.id).version,symbol:'01211.HK',note:'撤销合成关系'});assert.equal(f.r.get(t.id).companies.length,0);assert.equal(f.runs.get(t.id,a.id).reviews[0][0].action,'link');}finally{await f.close();}});
test('shared lease, cancellation, offline and restore guards prevent unintended model calls',async()=>{const f=fixture({runner:(_p,{signal})=>new Promise((_resolve,reject)=>signal.addEventListener('abort',()=>reject(Error('cancelled'))))});try{claimModelLease(f.store.db,'other',Date.parse(at),5000);assert.throws(()=>f.runs.start(f.topic.id,f.input),/正在运行/);releaseModelLease(f.store.db,'other');const a=f.runs.start(f.topic.id,f.input);await Promise.resolve();f.runs.cancel(f.topic.id,a.id);assert.equal((await f.runs.wait(a.id)).status,'cancelled');f.store.db.prepare("INSERT OR REPLACE INTO settings VALUES('restore_review_required','1')").run();assert.throws(()=>f.runs.start(f.topic.id,f.input),/恢复/);}finally{await f.close();}const offline=fixture({mode:'demo'});try{assert.throws(()=>offline.runs.start(offline.topic.id,offline.input),/未启用/);}finally{await offline.close();}});
test('identity results and decisions survive restart and expired work stays interrupted',async()=>{const dir=mkdtempSync(join(tmpdir(),'company-entity-')),path=join(dir,'test.sqlite'),f=fixture({path});try{const a=await run(f);f.runs.decide(f.topic.id,a.id,decision(f,0,0,'link','01211.HK'));const before=f.runs.get(f.topic.id,a.id);await f.close();const s=openStore(path),svc=createService(s,{mode:'research'});try{assert.deepEqual(svc.companyEntities.get(f.topic.id,a.id),before);const fake={...a,id:'interrupted-entity',status:'running'};s.db.prepare('INSERT INTO company_entity_runs VALUES(?,?,?,?,?,?)').run(fake.id,f.topic.id,'interrupted-request','running',1,JSON.stringify(fake));const recovered=openCompanyEntityRuns(s,svc.research);assert.equal(recovered.get(f.topic.id,fake.id).status,'interrupted');await recovered.close();}finally{await svc.close();s.close();}}finally{rmSync(dir,{recursive:true,force:true});}});
test('HTTP identity workflow updates research and watches; forbidden origin and restore are rejected',async()=>{const f=fixture(),server=http.createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;server.on('request',createHandler(f.store,f.service,{apiPort:port,frontendPort:port}));const base=`http://127.0.0.1:${port}/api/research/${f.topic.id}/company-entities`,post=(u,d)=>fetch(u,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});try{const started=await post(base,f.input);assert.equal(started.status,202);const a=await started.json();await f.runs.wait(a.id);assert.equal((await(await fetch(base)).json()).runs.length,1);const linked=await post(base+'/'+a.id+'/decision',decision(f,0,0,'link','01211.HK'));assert.equal(linked.status,200);assert.equal((await linked.json()).companyEntityRun.reviews[0][0].symbol,'01211.HK');assert.ok(f.store.watchlist().some(w=>w.symbol==='01211.HK'));assert.equal((await fetch(base,{headers:{Origin:'https://evil.invalid'}})).status,403);assert.equal((await post(base,{...f.input,model:'override'})).status,400);f.store.db.prepare("INSERT OR REPLACE INTO settings VALUES('restore_review_required','1')").run();assert.equal((await post(base,f.input)).status,409);}finally{await new Promise(r=>server.close(r));await f.close();}});
test('owned identity errors stay actionable without exposing appended diagnostics',()=>{const msg='材料、研究或身份候选已变化，请刷新核对';assert.equal(safeErrorText(msg),msg);assert.equal(safeErrorText(msg+' private details'),'任务失败，请检查来源或运行配置');});

test('reviewed event scope limits identity extraction to its own quoted occurrence end to end',async()=>{const f=fixture();try{const {openMaterialEventRuns}=await import('../server/material-event-runs.mjs');const events=[{title:'合成芯片业务事项',actor:'NVIDIA',action:'讨论',object:'芯片业务',stage:'讨论',eventTime:'未知',timeEvidence:{basis:'unknown',quote:'',quoteField:'none'},timeRole:'unknown',quote:'NVIDIA讨论芯片业务。',quoteField:'body',boundaryReason:'与汽车业务分别追踪'}];const er=openMaterialEventRuns(f.store,f.r,{enabled:true,config,runner:async p=>{const decomposition={events,scopeNote:'合成单事项',missingEvidence:[]},rawOutput=JSON.stringify(decomposition);return {status:'candidate',reviewStatus:'unreviewed',decomposition,rawOutput,trace:{model:config.model,inputHash:p.inputHash,outputHash:digest(rawOutput)}};}});try{const a=er.start(f.topic.id,{...f.input,requestId:'event-scope-00000001'});await er.wait(a.id);const reviewed=er.decide(f.topic.id,a.id,{eventIndex:0,version:0,action:'create',note:'合成范围核对'}),id=reviewed.reviews[0][0].topicId;const p=companyEntitiesPacket(f.store,f.r,id,{version:1,materialId:f.material.id,revision:1});assert.equal(p.input.eventFocus.quote,events[0].quote);assert.throws(()=>validateCompanyEntities(output(),p));const scoped=openCompanyEntityRuns(f.store,f.r,{enabled:true,config,runner:async p=>candidate(p,{...output(),mentions:[output().mentions[1]]})});try{const c=scoped.start(id,{version:1,materialId:f.material.id,revision:1,requestId:'scoped-entity-00000001'});await scoped.wait(c.id);scoped.decide(id,c.id,{mentionIndex:0,version:0,action:'link',symbol:'NVDA.US',note:'只核对本事项主体',topicVersion:1});assert.deepEqual(f.r.get(id).companies.map(c=>c.symbol),['NVDA.US']);assert.equal(f.r.get(f.topic.id).companies.length,0);}finally{await scoped.close();}}finally{await er.close();}}finally{await f.close();}});
test('a concurrent archival before the write transaction prevents candidate adoption',async()=>{const f=fixture();try{const a=await run(f),d=decision(f,0,0,'link','01211.HK'),exec=f.store.db.exec.bind(f.store.db);let armed=true;f.store.db.exec=sql=>{if(armed&&sql==='BEGIN IMMEDIATE'){armed=false;f.r.update(f.topic.id,{version:f.topic.version,status:'archived'});}return exec(sql);};try{assert.throws(()=>f.runs.decide(f.topic.id,a.id,d));assert.equal(f.r.get(f.topic.id).companies.length,0);assert.equal(f.runs.get(f.topic.id,a.id).reviews[0].length,0);}finally{f.store.db.exec=exec;}}finally{await f.close();}});
test('invalid model output persists a failed attempt and never mutates research',async()=>{const f=fixture({runner:async p=>{const c=candidate(p);c.trace.outputHash='forged';return c;}});try{const a=await run(f);assert.equal(a.status,'failed');assert.equal(a.failure.code,'output');assert.equal(f.r.get(f.topic.id).companies.length,0);assert.equal(f.runs.list(f.topic.id).runs.length,1);}finally{await f.close();}});

test('validation never mutates the shared output schema between frozen model calls',async()=>{const f=fixture();try{const {requestId,...ref}=f.input,p=companyEntitiesPacket(f.store,f.r,f.topic.id,ref),before=digest(COMPANY_ENTITIES_SCHEMA);validateCompanyEntities(output(),p);validateCompanyEntities(output(),p);assert.equal(digest(COMPANY_ENTITIES_SCHEMA),before);}finally{await f.close();}});
