import test from 'node:test';
import assert from 'node:assert/strict';
import {openStore} from '../server/store.mjs';
import {openResearch} from '../server/research.mjs';
import {openPaper} from '../server/paper.mjs';
import {createService} from '../server/service.mjs';
import {assessTopic} from '../server/workflow.mjs';
import {classifyHeadline} from '../server/triage.mjs';
import {createScheduler} from '../server/scheduler.mjs';
import {planExit} from '../server/risk-rules.mjs';
import {orderedTopics,dataHealth} from '../src/integrated/decision-model.js';
const setup=()=>{let now='2026-09-24T10:00:00Z';const store=openStore(':memory:'),r=openResearch(store,{clock:()=>now}),p=openPaper(store,r,{clock:()=>now});return {store,r,p,setTime:v=>now=v};};
const assessment={status:'rumor',claim:'Fixture acquisition completes by deadline',probability:20,basis:'One original source, no independent corroboration',impactIfTrue:'Potentially expands addressable market; quantify revenue',impactIfFalse:'Reversal of expectations; no operating uplift',horizon:'Recheck in one week',resolveBy:'2026-10-01'};
const proposal=(p,r,extra={})=>({version:p.snapshot().version,clientId:crypto.randomUUID(),topicId:'memory-global',topicVersion:r.get('memory-global').version,symbol:'MU.US',side:'buy',qty:1,price:120,limit:125,reason:'Conditional rumor scenario',holdingHorizon:'One week',invalidation:'Denied or fails to complete',...extra});

test('general event routing covers new issuers without inventing company associations',()=>{
 for(const [title,rule] of [['FDA approves Nova therapy for rare disease','approval'],['Nova clinical trial fails primary endpoint','clinical'],['Manufacturer recalls 80000 vehicles','recall'],['Railway wins $2 billion contract','order'],['Miner halts production at copper mine','supply'],['Company announces share repurchase','capital'],['Company plans acquisition of rival','deal']]){const r=classifyHeadline({title});assert.equal(r.bucket,'review',title);assert.ok(r.matchedRules.includes(rule),title);assert.equal(r.tradeSignal,false);assert.deepEqual(r.companies,[]);}
 for(const title of ['Court orders witness to appear','Muse band announces concert','Scientists study ancient tools'])assert.equal(classifyHeadline({title}).bucket,'quiet',title);
 assert.notEqual(classifyHeadline({title:'Weather service raises temperature forecast'}).category,'经营指引变化');
});
test('rumor, denial and cancellation stay distinct and do not imply completion',()=>{
 const rumor=classifyHeadline({title:'Nova reportedly in talks for acquisition of rival'});assert.equal(rumor.messageStatus,'rumor');assert.equal(rumor.bucket,'review');
 assert.match(classifyHeadline({title:'Nova denies acquisition talks'}).stage,/否认/);
 assert.match(classifyHeadline({title:'Nova cancels acquisition after talks'}).stage,/终止/);
});
test('probability assessment is versioned, survives restart and never verifies evidence or places trades',()=>{const {store,r,p}=setup();try{let t=r.get('memory-global');const oldEvidence=structuredClone(t.evidence);t=r.update(t.id,{version:t.version,assessment});assert.equal(t.assessment.probability,20);t=r.update(t.id,{version:t.version,assessment:{...assessment,probability:70,basis:'Second independent source; subjective revision'}});assert.equal(r.history(t.id)[1].topic.assessment.probability,20);assert.equal(openResearch(store).get(t.id).assessment.probability,70);assert.deepEqual(t.evidence,oldEvidence);assert.equal(p.snapshot().fills.length,0);assert.equal(assessTopic(t).assessmentLabel,'传闻');t=r.update(t.id,{version:t.version,assessment:{...assessment,status:'denied',probability:0}});assert.equal(r.history(t.id)[1].topic.assessment.probability,70);}finally{store.close();}});
test('probabilities require a falsifiable claim, basis, scenarios and a valid deadline',()=>{const {store,r}=setup();try{const t=r.get('memory-global');for(const patch of [{probability:101},{probability:'50'},{basis:''},{impactIfFalse:''},{resolveBy:'2026-02-31'},{claim:''}])assert.throws(()=>r.update(t.id,{version:t.version,assessment:{...assessment,...patch}}));const a=r.update(t.id,{version:t.version,assessment:{...assessment,probability:null,basis:'',impactIfFalse:'',resolveBy:''}});assert.equal(a.assessment.probability,null);}finally{store.close();}});
test('unconfirmed assessed research can create a proposal and retain the human approval boundary',()=>{const {store,r,p}=setup();try{const t=r.get('memory-global');r.update(t.id,{version:t.version,assessment});p.propose(proposal(p,r));assert.equal(p.snapshot().orders.at(-1).status,'pending');assert.equal(p.snapshot().fills.length,0);}finally{store.close();}});
test('unverified contrary evidence on holdings raises review priority without automatic exit',()=>{const {store,r,p}=setup();try{const t=r.get('memory-global');t.evidence=[{verification:'unverified',stance:'against'}];t.hypothesis.reviewAt='';const w=assessTopic(t,{book:p.snapshot(),today:'2026-09-24'});assert.equal(w.priorityRank,1);assert.equal(w.coverage.against,0);assert.equal(w.coverage.pendingAgainst,1);assert.equal(w.automaticBuy,false);const later={...t,id:'later',companies:[],evidence:[],updatedAt:'9999'};assert.equal(orderedTopics([later,t],[w])[0].id,t.id);}finally{store.close();}});
test('expired reservations disappear immediately and maintenance records expiry exactly once without fills',()=>{const {store,p,setTime}=setup();try{const b=p.snapshot();setTime(b.orders[0].expiresAt);const after=p.snapshot();assert.equal(after.reserved,0);assert.equal(after.pendingCount,0);assert.equal(after.cash,b.cash);assert.deepEqual(after.positions,b.positions);assert.equal(after.orders.filter(o=>o.status==='expired').length,3);assert.equal(p.expire(),3);assert.equal(p.expire(),0);assert.equal(p.history().length,2);assert.equal(p.snapshot().fills.length,0);assert.throws(()=>p.decide(b.orders[0].id,{version:p.snapshot().version,decision:'reject'}),/过期/);}finally{store.close();}});
test('expired sell reservations allow a fresh proposal, including at the exact deadline',()=>{const {store,p,r,setTime}=setup();try{const b=p.snapshot();setTime(b.orders[0].expiresAt);p.propose(proposal(p,r,{topicId:'spotify-access',topicVersion:r.get('spotify-access').version,symbol:'SPOT.US',side:'sell',qty:120,price:500,limit:490}));assert.equal(p.snapshot().pendingCount,1);assert.equal(p.snapshot().fills.length,0);}finally{store.close();}});
test('conflicting terminal decisions are rejected while same decision retries remain idempotent',()=>{const {store,p}=setup();try{const b=p.snapshot(),id=b.orders[0].id;p.decide(id,{version:b.version,decision:'reject'});p.decide(id,{version:b.version,decision:'reject'});assert.throws(()=>p.decide(id,{version:b.version,decision:'approve',confirmScenario:true}),/不同决定/);assert.equal(p.history().length,2);}finally{store.close();}});
test('human invalidation blocks related new risk, allows sale proposals, and intact review restores eligibility',()=>{const {store,p,r}=setup();try{p.review({version:p.snapshot().version,topicVersion:r.get('memory-global').version,symbol:'03986.HK',result:'invalidated',note:'Fixture invalidation'});assert.throws(()=>p.propose(proposal(p,r)),/失效/);p.propose(proposal(p,r,{symbol:'03986.HK',side:'sell',qty:100,price:150,limit:145}));assert.equal(p.snapshot().fills.length,0);assert.equal(assessTopic(r.get('memory-global'),{book:p.snapshot()}).priorityRank,0);p.review({version:p.snapshot().version,topicVersion:r.get('memory-global').version,symbol:'03986.HK',result:'intact',note:'Fixture renewed rationale'});p.propose(proposal(p,r));assert.equal(p.snapshot().fills.length,0);}finally{store.close();}});
test('scheduler permits news refresh while daily lane stalls, and does not duplicate the stalled job',async()=>{let release;const gate=new Promise(r=>release=r);let news=0,daily=0;const s=createScheduler({news:async()=>{news++;},daily:async()=>{daily++;await gate;}});const first=s.run();await new Promise(r=>setImmediate(r));const second=s.run();await new Promise(r=>setImmediate(r));assert.equal(news,2);assert.equal(daily,1);assert.equal(s.snapshot().daily.running,true);release();await Promise.all([first,second]);assert.equal(s.snapshot().daily.running,false);});
test('one scheduler lane failure is visible and recovers without suppressing the other lane',async()=>{let fail=true,count=0;const s=createScheduler({news:()=>{if(fail)throw new Error('fixture');},daily:()=>{count++;}});await s.run();assert.equal(s.snapshot().news.error,'fixture');assert.equal(count,1);fail=false;await s.run();assert.equal(s.snapshot().news.error,null);assert.equal(count,2);});
test('snapshot does not add new watch links but explicit association synchronization does',()=>{const store=openStore(':memory:');try{const service=createService(store),r=service.research;let t=r.create({title:'Fixture',summary:'Fixture'});r.addCompany(t.id,{version:t.version,symbol:'TSLA.US',note:'Fixture relationship'});service.snapshot();assert.equal(store.watchlist().some(w=>w.symbol==='TSLA.US'),false);service.syncWatches();assert.equal(store.watchlist().some(w=>w.symbol==='TSLA.US'),true);}finally{store.close();}});
test('health distinguishes old cache and failed collection from a live local connection',()=>{const h=dataHealth({checks:{news:{state:'error',receivedAt:'2026-09-23T00:00:00Z'},'daily:A':{state:'error'}},watchlist:[{symbol:'A',daily:{receivedAt:'2026-09-23T00:00:00Z'}}]},Date.parse('2026-09-24T00:00:00Z'));assert.equal(h.issue,true);assert.equal(h.rssState,'更新失败');assert.equal(h.oldCount,1);assert.equal(h.failedCount,1);});
test('assessed rumor may reach exit approval; changing probability invalidates the old approval fingerprint',()=>{const input={position:{id:'p',version:1,qty:100,sellableQty:100},evidence:{id:'e',invalidatesThesis:true,verification:'unverified',assessment:{probability:20,basis:'Fixture independent source',impact:'Material downside if true'}},requestedQty:20,quote:{id:'q',fresh:true},market:{open:true,halted:false,sellLiquidity:true}};const a=planExit(input);assert.equal(a.state,'awaiting-human');input.approval={valid:true,fingerprint:a.fingerprint};assert.equal(planExit(input).state,'eligible-for-paper-engine');input.evidence.assessment.probability=70;assert.equal(planExit(input).state,'awaiting-human');assert.equal(planExit(input).automaticExecution,false);});
test('failed collection retains the last success timestamp; successful recovery clears the old error',()=>{const store=openStore(':memory:');try{store.status('news',{state:'ok',receivedAt:'2026-09-24T00:00:00Z'});store.status('news',{state:'error',attemptedAt:'2026-09-24T01:00:00Z',error:'fixture'});assert.equal(store.checks().news.receivedAt,'2026-09-24T00:00:00Z');store.status('news',{state:'ok',receivedAt:'2026-09-24T02:00:00Z'});assert.equal(store.checks().news.error,undefined);}finally{store.close();}});
test('ordinary reports and talks are not mislabeled as rumors; tentative business stages remain distinct',()=>{for(const title of ['Company reports record quarterly earnings','US and Iran peace talks continue','Teenager reports crime to police'])assert.notEqual(classifyHeadline({title}).messageStatus,'rumor');assert.equal(classifyHeadline({title:'Company in talks for acquisition of rival'}).messageStatus,'proposed');assert.equal(classifyHeadline({title:'Company in talks for acquisition of rival, sources say'}).messageStatus,'rumor');});
