import test from 'node:test';
import {crossThemeCandidates} from '../server/cross-theme-observations.mjs';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {openStore} from '../server/store.mjs';
import {createService} from '../server/service.mjs';
import {createHandler} from '../server/index.mjs';
import {digest,CodexResearchError} from '../server/codex-research.mjs';
const at='2026-10-03T00:00:00Z',config={binary:'/test/codex',model:'test-model',timeoutMs:1000};
function output(packet,relation){const fields=side=>({actor:'合成主体',action:'待核',object:'合成对象',eventTime:'未知',timeEvidence:{basis:'unknown',quote:'',quoteField:'none'},stage:'未知',quote:packet.input[side].body||packet.input[side].title,...(packet.schema==='event-pair-1'?{}:{quoteField:packet.input[side].body?'body':'title'})});const comparison={relation,left:fields('left'),right:fields('right'),reason:'合成判断，等待核对',missingEvidence:['核验事实']},rawOutput=JSON.stringify(comparison);return {status:'candidate',reviewStatus:'unreviewed',comparison,rawOutput,trace:{model:config.model,promptVersion:packet.schema,inputHash:packet.inputHash,outputHash:digest(rawOutput)}};}
function fixture(path=':memory:',count=4){
 const store=openStore(path);let value='followup';const service=createService(store,{mode:'research',modelConfig:config,now:()=>Date.parse(at),semanticRunner:async p=>{if(value==='fail')throw new CodexResearchError('process');return output(p,value);}}),b=service.semanticBatches,c=service.eventClusters,s=service.semanticEvents;
 const news=Array.from({length:count},(_,i)=>({id:digest(`cluster-news-${i}`),title:`合成材料${i}`,url:`https://example.invalid/cluster-${i}`,publisher:'合成来源',publishedAt:at}));store.ingest(news,at);const refs=news.map(n=>({id:n.id,revision:1}));
 const batch=async(inputs=refs.slice(0,3),relations=[])=>{const p=b.preview({inputs}),saved=b.create({inputs,planHash:p.planHash,requestId:randomUUID()});for(let i=0;i<p.pairs.length;i++){value=relations[i]||'followup';b.step({assertActive(){}});for(const row of b.get(saved.id).items)if(row.runId)await s.wait(row.runId);}return saved;};
 const command=(batchId,group=c.preview(batchId).groups.find(g=>g.canSave))=>({batchId,groupId:group.id,previewHash:group.hash,clusterId:group.overlaps[0]?.id||'',version:group.overlaps[0]?.version||0,title:'合成事件簇',note:'本人核对这些材料针对同一具体事件',requestId:randomUUID()});
 return {store,service,b,c,s,news,refs,batch,command,set relation(v){value=v;},async close(){await service.close();store.close();}};
}
test('complete pair agreement proposes one scope without creating identity, decisions, research or trades',async()=>{
 const f=fixture();try{const batch=await f.batch(undefined,['repeat','followup','reversal']),before=f.service.paper.snapshot(),p=f.c.preview(batch.id);assert.equal(p.groups.length,1);assert.equal(p.groups[0].state,'ready');assert.equal(p.groups[0].pairs.length,3);assert.equal(p.groups[0].canSave,true);assert.deepEqual(f.c.preview(batch.id),p);assert.equal(f.c.list().total,0);assert.equal(f.store.db.prepare('SELECT count(*) n FROM semantic_decisions').get().n,0);assert.deepEqual(f.service.paper.snapshot(),before);assert.equal(f.service.research.list().length,0);}finally{await f.close();}
});
test('A-B and B-C identity never imply A-C identity when that pair disagrees',async()=>{
 const f=fixture();try{const b=await f.batch(undefined,['repeat','related','followup']),g=f.c.preview(b.id).groups[0];assert.equal(g.members.length,3);assert.equal(g.state,'conflict');assert.equal(g.canSave,false);assert.equal(g.pairs.filter(p=>p.status==='different').length,1);assert.throws(()=>f.c.save(f.command(b.id,g)),/组内关系/);assert.equal(f.c.list().total,0);}finally{await f.close();}
});
test('related, analogy, unrelated and uncertainty remain ungrouped and visible',async()=>{
 const f=fixture();try{for(const relation of ['related','analogy','unrelated','uncertain']){const b=await f.batch(f.refs.slice(0,2),[relation]),p=f.c.preview(b.id);assert.equal(p.groups.length,2);assert.ok(p.groups.every(g=>g.state==='single'&&!g.canSave));assert.equal(p.unmergedPairs.length,1);assert.equal(p.unmergedPairs[0].relation,relation);}}finally{await f.close();}
});
test('missing, failed and uncertain internal pairs prevent confirmation of a connected scope',async()=>{
 const f=fixture();try{for(const relation of ['fail','uncertain']){const b=await f.batch(undefined,['followup',relation,'followup']),g=f.c.preview(b.id).groups[0];assert.equal(g.state,'conflict');assert.equal(g.pairs.length,3);assert.equal(g.canSave,false);}const p=f.b.preview({inputs:f.refs.slice(0,2)}),pending=f.b.create({inputs:f.refs.slice(0,2),planHash:p.planHash,requestId:randomUUID()});assert.equal(f.c.preview(pending.id).unmergedPairs[0].status,'pending');}finally{await f.close();}
});
test('confirmation freezes identity and every pair, is idempotent, and preserves model decisions and ledgers',async()=>{
 const f=fixture();try{const b=await f.batch(),request=f.command(b.id),before=f.service.paper.snapshot(),saved=f.c.save(request),record=f.c.get(saved.id);assert.equal(saved.version,1);assert.deepEqual(f.c.save(request),saved);assert.equal(f.c.list().total,1);assert.equal(record.history.length,1);assert.equal(record.members.length,3);assert.equal(record.pairs.length,3);assert.equal(record.health.current,true);for(const p of record.pairs)assert.ok(p.left.title&&p.right.title&&p.basis.comparison.left.quote);assert.equal(f.store.db.prepare('SELECT count(*) n FROM semantic_decisions').get().n,0);assert.deepEqual(f.service.paper.snapshot(),before);assert.throws(()=>f.c.save({...request,title:'另一名称'}),/请求标识/);assert.throws(()=>f.c.save({...request,requestId:randomUUID()}),/预览已变化/);}finally{await f.close();}
});
test('expansion retains the stable identity and immutable old membership; partial replacement is rejected',async()=>{
 const f=fixture();try{const first=await f.batch(f.refs.slice(0,2)),saved=f.c.save(f.command(first.id)),old=f.c.get(saved.id).history[0],expanded=await f.batch(),next=f.c.save({...f.command(expanded.id),title:'完整事件'});assert.equal(next.id,saved.id);assert.equal(next.version,2);assert.deepEqual(f.c.get(saved.id).history[1],old);assert.equal(f.c.get(saved.id).members.length,3);const partial=f.c.preview(first.id).groups[0];assert.equal(partial.missing.length,1);assert.equal(partial.canSave,false);assert.throws(()=>f.c.save(f.command(first.id,partial)),/未包含原簇/);}finally{await f.close();}
});
test('news revision invalidates saved evidence without rewriting it and refreshed input can create a new cluster version',async()=>{
 const f=fixture();try{const b=await f.batch(f.refs.slice(0,2)),saved=f.c.save(f.command(b.id)),old=f.c.get(saved.id).history[0];f.store.ingest([{...f.news[0],title:'修订后的合成新闻'}],'2026-10-03T01:00:00Z');assert.equal(f.c.get(saved.id).health.current,false);assert.deepEqual(f.c.get(saved.id).history[0],old);assert.equal(f.c.preview(b.id).groups[0].canSave,false);const nextBatch=await f.batch([{id:f.refs[0].id,revision:2},f.refs[1]]),next=f.c.save(f.command(nextBatch.id));assert.equal(next.id,saved.id);assert.equal(next.version,2);assert.equal(f.c.get(saved.id).health.current,true);assert.deepEqual(f.c.get(saved.id).history[1],old);}finally{await f.close();}
});
test('material revisions retain document membership and mixed input source scopes',async()=>{
 const f=fixture();try{const r=f.service.research;let t=r.create({title:'材料研究',summary:'合成'});const save=body=>{t=r.saveMaterial(t.id,{version:t.version,title:'材料正文',sourceName:'合成',url:'https://example.invalid/material',body,scope:'excerpt',publishedAt:'2026-10-01',stance:'unverified',family:'other',step:'fact',interpretation:'核对'});const e=t.evidence.at(-1);return {kind:'material',id:e.materialId,revision:e.materialRevision};};const m=save('第一版正文'),b=await f.batch([m,f.refs[0]]),saved=f.c.save(f.command(b.id));assert.equal(f.c.get(saved.id).members[0].contentScope,'excerpt');assert.equal(f.service.research.related(t.id).eventClusters[0].id,saved.id);const revised=save('第二版正文');assert.equal(f.c.get(saved.id).health.current,false);const next=await f.batch([revised,f.refs[0]]);assert.equal(f.c.save(f.command(next.id)).id,saved.id);assert.equal(f.store.db.prepare('SELECT count(*) n FROM event_cluster_members').get().n,2);}finally{await f.close();}
});
test('rejection, withdrawal and superseding decisions invalidate current evidence but retain frozen history',async()=>{
 const f=fixture();try{const b=await f.batch(f.refs.slice(0,2)),run=f.b.get(b.id).items[0].runId;f.s.decide(run,{version:0,action:'accept',note:'核对'});const saved=f.c.save(f.command(b.id)),old=f.c.get(saved.id).history[0];f.s.decide(run,{version:1,action:'withdraw',note:'发现疑点'});assert.equal(f.c.get(saved.id).health.current,false);assert.equal(f.c.preview(b.id).groups[0].pairs[0].status,'rejected');assert.deepEqual(f.c.get(saved.id).history[0],old);const other=f.s.start({left:f.refs[0],right:f.refs[1]});await f.s.wait(other.id);f.s.decide(other.id,{version:2,action:'accept',note:'核对新版'});assert.equal(f.c.preview(b.id).groups[0].pairs[0].status,'superseded');assert.equal(f.c.get(saved.id).health.current,false);}finally{await f.close();}
});
test('stored output corruption invalidates cluster evidence without rewriting the confirmed cluster',async()=>{
 const f=fixture();try{
  const batch=await f.batch(f.refs.slice(0,2)),request=f.command(batch.id),saved=f.c.save(request),before=f.c.get(saved.id);
  const id=f.b.get(batch.id).items[0].runId,run=JSON.parse(f.store.db.prepare('SELECT payload FROM semantic_runs WHERE id=?').get(id).payload);
  run.candidate.rawOutput='Damaged stored response';f.store.db.prepare('UPDATE semantic_runs SET payload=? WHERE id=?').run(JSON.stringify(run),id);
  assert.equal(f.c.get(saved.id).health.current,false);assert.deepEqual(f.c.get(saved.id).history,before.history);
  assert(f.c.preview(batch.id).groups.every(g=>!g.canSave));
  assert.throws(()=>f.c.save({...request,requestId:randomUUID()}));
  assert.equal(f.c.get(saved.id).version,before.version);assert.equal(f.store.db.prepare('SELECT count(*) n FROM event_cluster_members').get().n,2);
 }finally{await f.close();}
});
test('clusters sharing active document identities cannot merge implicitly; explicit archival releases assignments',async()=>{
 const f=fixture();try{const a=await f.batch(f.refs.slice(0,2)),b=await f.batch(f.refs.slice(2)),ca=f.c.save(f.command(a.id)),cb=f.c.save(f.command(b.id)),all=await f.batch(f.refs),g=f.c.preview(all.id).groups[0];assert.equal(g.overlaps.length,2);assert.equal(g.canSave,false);assert.throws(()=>f.c.save(f.command(all.id,g)),/其他事件簇/);f.c.archive(cb.id,{version:1,note:'核对后撤销此独立归组，保留历史',requestId:randomUUID()});assert.equal(f.c.get(cb.id).history.length,2);const updated=f.c.save(f.command(all.id));assert.equal(updated.id,ca.id);assert.equal(f.c.get(ca.id).members.length,4);assert.equal(f.c.list({status:'active'}).total,1);assert.equal(f.c.list({status:'archived'}).total,1);}finally{await f.close();}
});
test('archiving is version checked and idempotent and keeps all original input and decisions',async()=>{
 const f=fixture();try{const b=await f.batch(),saved=f.c.save(f.command(b.id)),before=f.c.get(saved.id).history[0],request={version:1,note:'重新核对之前先归档',requestId:randomUUID()},result=f.c.archive(saved.id,request);assert.deepEqual(f.c.archive(saved.id,request),result);assert.equal(result.version,2);assert.equal(f.c.get(saved.id).status,'archived');assert.equal(f.c.get(saved.id).health.current,false);assert.deepEqual(f.c.get(saved.id).history[1],before);assert.equal(f.store.db.prepare('SELECT count(*) n FROM event_cluster_members').get().n,0);assert.throws(()=>f.c.archive(saved.id,{...request,requestId:randomUUID()}),/已更新或归档/);assert.equal(f.b.get(b.id).counts.candidate,3);}finally{await f.close();}
});
test('research projections require exact member versions and do not change research or evaluation truth',async()=>{
 const f=fixture();try{const topic=f.service.research.createFromNews({newsId:f.refs[0].id,newsRevision:1}),before=f.service.research.get(topic.id),b=await f.batch(f.refs.slice(0,2)),saved=f.c.save(f.command(b.id));let links=f.service.research.related(topic.id).eventClusters;assert.equal(links[0].bindingCurrent,true);assert.equal(links[0].matchedMembers.length,1);f.store.ingest([{...f.news[0],title:'新版本'}],'2026-10-03T01:00:00Z');const next=await f.batch([{id:f.refs[0].id,revision:2},f.refs[1]]);f.c.save(f.command(next.id));links=f.service.research.related(topic.id).eventClusters;assert.equal(links[0].health.current,true);assert.equal(links[0].bindingCurrent,false);assert.equal(links[0].matchedMembers.length,0);assert.deepEqual(f.service.research.get(topic.id),before);f.c.archive(saved.id,{version:2,note:'归档',requestId:randomUUID()});assert.equal(f.service.research.related(topic.id).eventClusters.length,0);}finally{await f.close();}
});
test('invalid payload, preview fingerprint and injected members cannot be persisted',async()=>{
 const f=fixture();try{const b=await f.batch(),input=f.command(b.id);for(const change of [{title:''},{note:' '},{version:0.5},{members:[]},{clusterId:null},{requestId:'short'}])assert.throws(()=>f.c.save({...input,...change}));assert.throws(()=>f.c.save({...input,previewHash:'wrong'}),/预览已变化/);assert.throws(()=>f.c.save({...input,clusterId:randomUUID()}),/已更新或归档/);assert.equal(f.c.list().total,0);}finally{await f.close();}
});
test('restore review prohibits commands but reading and candidates remain read only',async()=>{
 const f=fixture();try{const b=await f.batch(),input=f.command(b.id),saved=f.c.save(input);f.store.db.prepare("INSERT INTO settings(key,value) VALUES('restore_review_required','1')").run();assert.throws(()=>f.c.save(input),/恢复副本/);assert.throws(()=>f.c.archive(saved.id,{version:1,note:'归档',requestId:randomUUID()}),/恢复副本/);assert.equal(f.c.get(saved.id).version,1);assert.equal(f.c.preview(b.id).groups.length,1);}finally{await f.close();}
});
test('history insertion failure rolls back current identity, assignments and command receipt together',async()=>{
 const f=fixture();try{const b=await f.batch(),input=f.command(b.id);f.store.db.exec("CREATE TRIGGER reject_cluster_version BEFORE INSERT ON event_cluster_versions BEGIN SELECT RAISE(ABORT,'synthetic failure'); END");assert.throws(()=>f.c.save(input),/synthetic failure/);for(const table of ['event_clusters','event_cluster_versions','event_cluster_members','event_cluster_commands'])assert.equal(f.store.db.prepare(`SELECT count(*) n FROM ${table}`).get().n,0);f.store.db.exec('DROP TRIGGER reject_cluster_version');assert.equal(f.c.save(input).version,1);}finally{await f.close();}
});
test('concurrent revision or another confirmation before the write lock invalidates the old preview atomically',async()=>{
 for(const mode of ['revision','confirmation','decision']){const dir=mkdtempSync(join(tmpdir(),'event-cluster-race-')),path=join(dir,'fixture.sqlite'),f=fixture(path),otherStore=openStore(path),other=createService(otherStore,{mode:'research',modelConfig:config,now:()=>Date.parse(at)}),exec=f.store.db.exec.bind(f.store.db);try{const b=await f.batch(),input=f.command(b.id);let armed=true;f.store.db.exec=sql=>{if(sql==='BEGIN IMMEDIATE'&&armed){armed=false;if(mode==='revision')otherStore.ingest([{...f.news[0],title:'并发修订'}],'2026-10-03T01:00:00Z');else if(mode==='confirmation')other.eventClusters.save({...input,requestId:randomUUID()});else other.semanticEvents.decide(f.b.get(b.id).items[0].runId,{version:0,action:'reject',note:'另一个窗口发现疑点'});}return exec(sql);};assert.throws(()=>f.c.save(input),/预览已变化/);assert.equal(f.c.list().total,mode==='confirmation'?1:0);assert.equal(f.store.db.prepare('SELECT count(*) n FROM event_cluster_commands WHERE request_id=?').get(input.requestId).n,0);}finally{f.store.db.exec=exec;await other.close();otherStore.close();await f.close();rmSync(dir,{recursive:true,force:true});}}
});
test('identity and archived history survive reopening without changing snapshots',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'event-cluster-reopen-')),path=join(dir,'fixture.sqlite'),f=fixture(path);let other,store;try{const b=await f.batch(),saved=f.c.save(f.command(b.id));f.c.archive(saved.id,{version:1,note:'留存',requestId:randomUUID()});const before=f.c.get(saved.id);await f.close();store=openStore(path);other=createService(store,{mode:'research',modelConfig:config,now:()=>Date.parse(at)});assert.deepEqual(other.eventClusters.get(saved.id),before);}finally{if(other){await other.close();store.close();}else await f.close();rmSync(dir,{recursive:true,force:true});}
});
test('registry paginates all clusters including identities older than recent comparison lists',async()=>{
 const f=fixture(':memory:',42);try{for(let i=0;i<21;i++){const b=await f.batch(f.refs.slice(i*2,i*2+2));f.c.save({...f.command(b.id),title:`样本簇${String(i).padStart(2,'0')}`});}for(let i=0;i<55;i++){const run=f.s.start({left:f.refs[0],right:f.refs[1]});await f.s.wait(run.id);}const a=f.c.list(),b=f.c.list({offset:20});const oldest=f.c.get(b.items[0].id);assert.ok(!f.s.list().runs.some(r=>r.id===oldest.pairs[0].basis.runId));assert.equal(oldest.health.current,true);assert.equal(a.total,21);assert.equal(a.items.length,20);assert.equal(b.items.length,1);assert.equal(new Set([...a.items,...b.items].map(r=>r.id)).size,21);assert.equal(f.c.list({q:'样本簇00'}).total,1);for(const p of [{offset:-1},{q:'x'.repeat(141)},{status:'wrong'},{limit:1000}])assert.throws(()=>f.c.list(p));}finally{await f.close();}
});
test('HTTP can preview, confirm, read history and archive while rejecting arbitrary client memberships',async()=>{
 const f=fixture(),handler=createHandler(f.store,f.service),call=async(method,url,data)=>{let status,result;await handler({method,url,headers:{host:'127.0.0.1:4179','content-type':'application/json'},async *[Symbol.asyncIterator](){yield JSON.stringify(data||{});}},{writeHead:s=>status=s,end:b=>result=JSON.parse(b)});return {status,result};};try{const b=await f.batch(),p=await call('GET',`/api/semantic-batches/${b.id}/clusters`);assert.equal(p.result.groups[0].canSave,true);const input=f.command(b.id),saved=await call('POST','/api/event-clusters',input);assert.equal(saved.status,201);const id=saved.result.id;assert.equal((await call('GET',`/api/event-clusters/${id}`)).result.history.length,1);assert.equal((await call('POST','/api/event-clusters',{...input,members:[]})).status,400);assert.equal((await call('POST',`/api/event-clusters/${id}/archive`,{version:1,note:'归档',requestId:randomUUID()})).status,200);assert.equal((await call('GET','/api/event-clusters?status=archived')).result.total,1);}finally{await f.close();}
});

test('cross-theme observations use current registry bindings and retain unknown status after source revisions',async()=>{
 const f=fixture();try{
  const topics=f.refs.slice(0,2).map(r=>f.service.research.createFromNews({newsId:r.id,newsRevision:1}));const batch=await f.batch(f.refs.slice(0,2));const saved=f.c.save(f.command(batch.id));
  const snapshots=[{accountId:'steady',at,quotes:{},book:{version:1,config:{},orders:[],lots:topics.map((t,i)=>({id:String(i),topicId:t.id,symbol:'AAPL.US',qty:1,issuerId:'synthetic'}))}}];
  const read=()=>crossThemeCandidates(snapshots,topics,t=>f.c.forResearch(t)).find(c=>c.hit?.input.groupKind==='event-cluster');const first=read();assert.equal(first.state,'hit');assert.equal(first.hit.input.groupId,saved.id);assert.equal(first.hit.input.bases.length,2);assert(first.hit.input.bases.every(([,b])=>b.bindingCurrent&&b.matchedMembers.length===1));
  const frozen=structuredClone(first);f.store.ingest([{...f.news[0],title:'修订的合成材料'}],'2026-10-03T01:00:00Z');assert.equal(read().state,'unknown');assert.deepEqual(first,frozen);
 }finally{await f.close();}
});
