import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {openStore} from '../server/store.mjs';
import {createService} from '../server/service.mjs';
import {createHandler} from '../server/index.mjs';
import {digest} from '../server/codex-research.mjs';
import {comparisonPacket,comparisonPrompt,validateComparison} from '../server/semantic-events.mjs';
import {eventComparisonSnapshot} from '../server/semantic-event-scopes.mjs';
const config={binary:'/test/codex',model:'test-model',timeoutMs:1000},at='2026-10-03T00:00:00Z';
const unknown={basis:'unknown',quote:'',quoteField:'none'};
const events=[{title:'合成甲收购乙',actor:'合成甲',action:'收购',object:'乙公司',stage:'拟议',eventTime:'未知',timeEvidence:unknown,timeRole:'unknown',quote:'合成甲拟收购乙公司。',quoteField:'body',boundaryReason:'独立交易'},{title:'合成甲终止丙项目',actor:'合成甲',action:'终止',object:'丙项目',stage:'终止',eventTime:'未知',timeEvidence:unknown,timeRole:'unknown',quote:'合成甲终止丙项目。',quoteField:'body',boundaryReason:'不同项目'}];
const body=events.map(e=>e.quote).join('');
function candidate(p,field,value){const rawOutput=JSON.stringify(value);return {status:'candidate',reviewStatus:'unreviewed',[field]:value,rawOutput,trace:{model:config.model,promptVersion:p.schema,inputHash:p.inputHash,outputHash:digest(rawOutput)}};}
function comparison(p){const side=s=>{const input=p.input[s],e=input.eventFocus||events[0];return {actor:e.actor,action:e.action,object:e.object,stage:e.stage,eventTime:'未知',timeEvidence:unknown,quote:input.eventFocus?e.quote:input.body||input.title,quoteField:input.eventFocus?e.quoteField:input.body?'body':'title'};};return {relation:p.input.left.eventFocus?.object===p.input.right.eventFocus?.object?'repeat':'unrelated',left:side('left'),right:side('right'),reason:'合成控制判断，不是质量验证',missingEvidence:['核验事实']};}
async function fixture(path=':memory:'){
 const store=openStore(path),svc=createService(store,{mode:'research',modelConfig:config,now:()=>Date.parse(at),materialEventRunner:async p=>candidate(p,'decomposition',{events,scopeNote:'合成两个事项',missingEvidence:['原公告']}),semanticRunner:async p=>candidate(p,'comparison',comparison(p))}),r=svc.research;
 const sources=[],refs=[];
 for(let i=0;i<2;i++){let t=r.create({title:`合成来源${i}`,summary:'合成两个事项'});t=r.saveMaterial(t.id,{version:t.version,title:`合成公告${i}`,sourceName:'合成',url:`https://news.acme.com/source-${i}`,body,scope:'excerpt',stance:'unverified',family:'other',step:'fact',interpretation:'核对'});const m=r.materialList(t.id).materials[0],run=svc.materialEvents.start(t.id,{version:t.version,materialId:m.id,revision:m.revision,requestId:randomUUID()});await svc.materialEvents.wait(run.id);sources.push({topic:t,material:m,runId:run.id});for(let j=0;j<2;j++){const done=svc.materialEvents.decide(t.id,run.id,{eventIndex:j,version:0,action:'create',note:'合成核对各自事项'});refs.push({kind:'event',id:done.reviews[j][0].topicId,revision:1});}}
 const batch=async inputs=>{const plan=svc.semanticBatches.preview({inputs}),b=svc.semanticBatches.create({inputs,planHash:plan.planHash,requestId:randomUUID()});for(let i=0;i<plan.pairs.length;i++){const step=svc.semanticBatches.step({assertActive(){}});assert.ok(step.runId);await svc.semanticEvents.wait(step.runId);}return b;};
 const save=(b,g)=>svc.eventClusters.save({batchId:b.id,groupId:g.id,previewHash:g.hash,clusterId:'',version:0,title:g.members[0].title,note:'合成核对同一具体事项',requestId:randomUUID()});
 return {store,svc,r,refs,sources,batch,save,async close(){await svc.close();store.close();}};
}

async function revised(f,index){
 const source=f.sources[index],topic=f.r.get(source.topic.id);
 const t=f.r.saveMaterial(topic.id,{version:topic.version,title:source.material.title,sourceName:'合成',url:source.material.url,body:body+'修订说明：补充材料核对范围。'+topic.version,scope:'excerpt',stance:'unverified',family:'other',step:'fact',interpretation:'修订核对'}),m=f.r.materialList(t.id).materials.at(-1);
 const run=f.svc.materialEvents.start(t.id,{version:t.version,materialId:m.id,revision:m.revision,requestId:randomUUID()});await f.svc.materialEvents.wait(run.id);
 const refs=[];for(let i=0;i<2;i++){const done=f.svc.materialEvents.decide(t.id,run.id,{eventIndex:i,version:0,action:'create',note:'合成新版本事项核对'});refs.push({kind:'event',id:done.reviews[i][0].topicId,revision:1});}return refs;
}
async function initialCluster(f){const b=await f.batch([f.refs[0],f.refs[2]]);return f.save(b,f.svc.eventClusters.preview(b.id).groups[0]);}
function request(f,id,b,replacements){const group=f.svc.eventClusters.preview(b.id).groups[0],data={batchId:b.id,groupId:group.id,version:f.svc.eventClusters.get(id).version,replacements};return {...data,previewHash:f.svc.eventClusters.replacementPreview(id,data).previewHash,note:'逐项核对原文及主体、对象和阶段，确认新版本延续同一事项。',requestId:randomUUID()};}

test('partial revision continues the same cluster identity and preserves old topic, source and comparison history',async()=>{
 const f=await fixture();try{const saved=await initialCluster(f),before=f.svc.eventClusters.get(saved.id),oldTopic=f.r.get(f.refs[0].id),book=f.svc.paper.snapshot(),next=await revised(f,0),b=await f.batch([next[0],f.refs[2]]),input=request(f,saved.id,b,[{beforeId:f.refs[0].id,afterId:next[0].id}]);assert.equal(f.svc.eventClusters.get(saved.id).health.current,false);const result=f.svc.eventClusters.replace(saved.id,input),after=f.svc.eventClusters.get(saved.id);assert.equal(result.id,saved.id);assert.equal(result.version,2);assert.equal(after.health.current,true);assert.equal(after.confirmedAt,before.confirmedAt);assert.deepEqual(after.history[1],before.history[0]);assert.equal(after.replacement.mappings[0].before.materialRevision,1);assert.equal(after.replacement.mappings[0].after.materialRevision,2);assert.deepEqual(f.r.get(f.refs[0].id),oldTopic);assert.deepEqual(f.svc.paper.snapshot(),book);assert.equal(f.r.related(next[0].id).eventClusters[0].bindingCurrent,true);const historical=f.r.related(f.refs[0].id).eventClusters[0];assert.equal(historical.id,saved.id);assert.equal(historical.bindingCurrent,false);assert.deepEqual(historical.historicalVersions,[1]);assert.equal(f.store.db.prepare('SELECT cluster_id FROM event_cluster_members WHERE member_key=?').get('event:'+f.refs[0].id),undefined);}finally{await f.close();}
});
test('all revised members can continue an old identity even with no current membership overlap',async()=>{
 const f=await fixture();try{const saved=await initialCluster(f),a=await revised(f,0),b=await revised(f,1),batch=await f.batch([a[0],b[0]]),group=f.svc.eventClusters.preview(batch.id).groups[0];assert.equal(group.overlaps.length,0);const input=request(f,saved.id,batch,[{beforeId:f.refs[0].id,afterId:a[0].id},{beforeId:f.refs[2].id,afterId:b[0].id}]);const result=f.svc.eventClusters.replace(saved.id,input);assert.equal(result.version,2);assert.equal(f.svc.eventClusters.list().total,1);const reversed={requestId:input.requestId,note:input.note,previewHash:input.previewHash,replacements:[...input.replacements].reverse().map(m=>({afterId:m.afterId,beforeId:m.beforeId})),version:input.version,groupId:input.groupId,batchId:input.batchId};assert.deepEqual(f.svc.eventClusters.replace(saved.id,reversed),result);assert.throws(()=>f.svc.eventClusters.replace(saved.id,{...input,note:'其他意思'}),/请求标识/);}finally{await f.close();}
});
test('missing, duplicate, arbitrary and cross-document replacement mappings cannot retire members',async()=>{
 const f=await fixture();try{const saved=await initialCluster(f),a=await revised(f,0),b=await revised(f,1),batch=await f.batch([a[0],b[0]]),valid=request(f,saved.id,batch,[{beforeId:f.refs[0].id,afterId:a[0].id},{beforeId:f.refs[2].id,afterId:b[0].id}]);for(const replacements of [[],valid.replacements.slice(0,1),[valid.replacements[0],valid.replacements[0]],[{beforeId:f.refs[0].id,afterId:b[0].id},{beforeId:f.refs[2].id,afterId:a[0].id}],[{beforeId:'unknown',afterId:a[0].id},valid.replacements[1]],[{...valid.replacements[0],forged:true},valid.replacements[1]]])assert.throws(()=>f.svc.eventClusters.replacementPreview(saved.id,{batchId:valid.batchId,groupId:valid.groupId,version:1,replacements}));assert.equal(f.svc.eventClusters.get(saved.id).version,1);}finally{await f.close();}
});
test('a target member owned by another active cluster cannot silently merge identities',async()=>{
 const f=await fixture();try{const original=await initialCluster(f),a=await revised(f,0),b=await revised(f,1),batch=await f.batch([a[0],b[0]]),other=f.save(batch,f.svc.eventClusters.preview(batch.id).groups[0]);assert.notEqual(other.id,original.id);assert.throws(()=>request(f,original.id,batch,[{beforeId:f.refs[0].id,afterId:a[0].id},{beforeId:f.refs[2].id,afterId:b[0].id}]),/其他事件簇/);assert.equal(f.svc.eventClusters.get(original.id).version,1);}finally{await f.close();}
});
test('source, decision and target-cluster changes invalidate the reviewed replacement preview',async()=>{
 for(const mode of ['source','decision','archive']){const f=await fixture();try{const saved=await initialCluster(f),a=await revised(f,0),batch=await f.batch([a[0],f.refs[2]]),input=request(f,saved.id,batch,[{beforeId:f.refs[0].id,afterId:a[0].id}]);if(mode==='source'){const t=f.r.get(a[0].id);f.r.update(t.id,{version:t.version,status:'archived'});}else if(mode==='decision'){const run=f.svc.semanticBatches.get(batch.id).items[0].runId;f.svc.semanticEvents.decide(run,{version:0,action:'reject',note:'发现疑点'});}else f.svc.eventClusters.archive(saved.id,{version:1,note:'暂不延续',requestId:randomUUID()});assert.throws(()=>f.svc.eventClusters.replace(saved.id,input));assert.equal(f.svc.eventClusters.get(saved.id).version,mode==='archive'?2:1);}finally{await f.close();}}
});
test('restore guard, hash mismatch and failed history insert leave current assignments untouched',async()=>{
 const f=await fixture();try{const saved=await initialCluster(f),a=await revised(f,0),batch=await f.batch([a[0],f.refs[2]]),input=request(f,saved.id,batch,[{beforeId:f.refs[0].id,afterId:a[0].id}]),before=f.svc.eventClusters.get(saved.id),members=f.store.db.prepare('SELECT * FROM event_cluster_members ORDER BY member_key').all();assert.throws(()=>f.svc.eventClusters.replace(saved.id,{...input,previewHash:'wrong'}),/预览/);f.store.db.exec("CREATE TRIGGER reject_succession BEFORE INSERT ON event_cluster_versions BEGIN SELECT RAISE(ABORT,'synthetic failure'); END");assert.throws(()=>f.svc.eventClusters.replace(saved.id,input),/synthetic failure/);assert.deepEqual(f.svc.eventClusters.get(saved.id),before);assert.deepEqual(f.store.db.prepare('SELECT * FROM event_cluster_members ORDER BY member_key').all(),members);assert.equal(f.store.db.prepare('SELECT 1 FROM event_cluster_commands WHERE request_id=?').get(input.requestId),undefined);f.store.db.exec('DROP TRIGGER reject_succession');f.store.db.prepare("INSERT OR REPLACE INTO settings VALUES('restore_review_required','1')").run();assert.throws(()=>f.svc.eventClusters.replace(saved.id,input),/恢复副本/);}finally{await f.close();}
});
test('a concurrent decision before the transaction prevents stale replacement and retains its command id',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'scope-succession-race-')),path=join(dir,'fixture.sqlite'),f=await fixture(path),store=openStore(path),other=createService(store,{mode:'research'}),exec=f.store.db.exec.bind(f.store.db);try{const saved=await initialCluster(f),a=await revised(f,0),batch=await f.batch([a[0],f.refs[2]]),input=request(f,saved.id,batch,[{beforeId:f.refs[0].id,afterId:a[0].id}]),run=f.svc.semanticBatches.get(batch.id).items[0].runId;let armed=true;f.store.db.exec=sql=>{if(sql==='BEGIN IMMEDIATE'&&armed){armed=false;other.semanticEvents.decide(run,{version:0,action:'reject',note:'并发核对反对'});}return exec(sql);};assert.throws(()=>f.svc.eventClusters.replace(saved.id,input),/组内关系/);assert.equal(f.svc.eventClusters.get(saved.id).version,1);assert.equal(f.store.db.prepare('SELECT 1 FROM event_cluster_commands WHERE request_id=?').get(input.requestId),undefined);}finally{f.store.db.exec=exec;await other.close();store.close();await f.close();rmSync(dir,{recursive:true,force:true});}
});
test('HTTP preview and explicit replacement preserve history through restart and later cluster archival',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'scope-succession-restart-')),path=join(dir,'fixture.sqlite'),f=await fixture(path);let store,svc;try{const saved=await initialCluster(f),a=await revised(f,0),batch=await f.batch([a[0],f.refs[2]]),input=request(f,saved.id,batch,[{beforeId:f.refs[0].id,afterId:a[0].id}]),h=createHandler(f.store,f.svc),call=async(suffix,data)=>{let status,result;await h({method:'POST',url:'/api/event-clusters/'+saved.id+'/'+suffix,headers:{host:'127.0.0.1:4179','content-type':'application/json'},async *[Symbol.asyncIterator](){yield JSON.stringify(data);}},{writeHead:s=>status=s,end:b=>result=JSON.parse(b)});return {status,result};};const {note,previewHash,requestId,...preview}=input;assert.equal((await call('replacement-preview',preview)).result.previewHash,previewHash);assert.equal((await call('replace',input)).status,200);const before=f.svc.eventClusters.get(saved.id);await f.close();store=openStore(path);svc=createService(store,{mode:'research'});assert.deepEqual(svc.eventClusters.get(saved.id),before);assert.deepEqual(svc.research.related(f.refs[0].id).eventClusters[0].historicalVersions,[1]);svc.eventClusters.archive(saved.id,{version:2,note:'归档保留延续依据',requestId:randomUUID()});assert.equal(svc.eventClusters.get(saved.id).history.length,3);assert.equal(svc.research.related(f.refs[0].id).eventClusters.length,0);}finally{if(svc){await svc.close();store.close();}else await f.close();rmSync(dir,{recursive:true,force:true});}
});

test('re-extracting the same material revision does not qualify as a source revision replacement',async()=>{
 const f=await fixture();try{const saved=await initialCluster(f),source=f.sources[0],m=source.material,t=f.r.get(source.topic.id),run=f.svc.materialEvents.start(t.id,{version:t.version,materialId:m.id,revision:m.revision,requestId:randomUUID()});await f.svc.materialEvents.wait(run.id);const done=f.svc.materialEvents.decide(t.id,run.id,{eventIndex:0,version:0,action:'create',note:'重新拆分同一版本'}),next={kind:'event',id:done.reviews[0][0].topicId,revision:1},batch=await f.batch([next,f.refs[2]]);assert.equal(f.svc.eventClusters.preview(batch.id).groups[0].state,'ready');assert.throws(()=>request(f,saved.id,batch,[{beforeId:f.refs[0].id,afterId:next.id}]),/更新版本/);}finally{await f.close();}
});
test('successive source revisions retain every prior membership and succession decision',async()=>{
 const f=await fixture();try{const saved=await initialCluster(f),a=await revised(f,0),b=await f.batch([a[0],f.refs[2]]);f.svc.eventClusters.replace(saved.id,request(f,saved.id,b,[{beforeId:f.refs[0].id,afterId:a[0].id}]));const before=f.svc.eventClusters.get(saved.id),next=await revised(f,0),batch=await f.batch([next[0],f.refs[2]]);f.svc.eventClusters.replace(saved.id,request(f,saved.id,batch,[{beforeId:a[0].id,afterId:next[0].id}]));const after=f.svc.eventClusters.get(saved.id);assert.equal(after.version,3);assert.equal(after.replacement.mappings[0].after.materialRevision,3);assert.equal(after.health.current,true);assert.deepEqual(after.history.slice(1),before.history);assert.deepEqual(f.r.related(f.refs[0].id).eventClusters[0].historicalVersions,[1]);assert.deepEqual(f.r.related(a[0].id).eventClusters[0].historicalVersions,[2]);assert.equal(f.r.related(next[0].id).eventClusters[0].bindingCurrent,true);}finally{await f.close();}
});
