import test from 'node:test';import assert from 'node:assert/strict';import React,{act} from 'react';import {createServer} from 'vite';import {fileURLToPath} from 'node:url';import {JSDOM} from 'jsdom';import {strategyProfiles} from '../shared/strategy-profiles.mjs';
const clone=value=>structuredClone(value);
async function ui(run){
 const vite=await createServer({configFile:false,root:fileURLToPath(new URL('../',import.meta.url)),server:{middlewareMode:true,watch:null},appType:'custom'}),dom=new JSDOM('<div id="root"></div>',{url:'http://localhost/'}),names=['window','document','HTMLElement','sessionStorage','fetch','IS_REACT_ACT_ENVIRONMENT'],before=new Map(names.map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));let root;
 const data={runtime:{instance:{id:'synthetic-instance-a'}},serverTime:'2026-10-04T13:00:00Z',operations:{execution:{paused:true}},research:{topics:[{id:'synthetic-topic',version:1,status:'active',title:'虚构市场申请测试',companies:[{symbol:'AAPL.US'}]}]}};
 let book={id:'synthetic-account',version:1,enabled:true,configured:true,profile:clone(strategyProfiles.aggressive),config:clone(strategyProfiles.aggressive.suggestedConfig),settledCashCents:50000000,unsettledCashCents:0,reservedCents:0,availableCashCents:50000000,navCents:50000000,realizedCents:0,feesCents:0,riskPaused:false,strategyRisk:{drawdownPct:0,alerts:[]},orders:[],positions:[],fills:[],missing:[]};let handle=async(path,method)=>{if(method==='POST')throw Error('Unconfigured synthetic write');return {body:path.endsWith('/history')?[]:book};};const requests=[];
 try{
  Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,sessionStorage:dom.window.sessionStorage,IS_REACT_ACT_ENVIRONMENT:true});dom.window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};dom.window.HTMLDialogElement.prototype.close=function(){this.open=false;};
  globalThis.fetch=async(input,options={})=>{const u=new URL(input,'http://localhost'),method=options.method||'GET',payload=options.body?JSON.parse(options.body):null;requests.push({path:u.pathname,account:u.searchParams.get('account'),method,payload});const response=await handle(u.pathname,method,payload),status=response.status||200;return {status,ok:status<400,headers:{get:k=>k==='content-type'?'application/json':null},json:async()=>clone(response.body)};};
  const {createRoot}=await import('react-dom/client'),{default:Market}=await vite.ssrLoadModule('/src/integrated/MarketSimulation.jsx');root=createRoot(document.getElementById('root'));
  const field=label=>[...document.querySelectorAll('label')].find(e=>e.firstChild?.textContent===label)?.querySelector('input,textarea,select'),button=text=>[...document.querySelectorAll('button')].find(e=>e.textContent===text);
  const fill=(label,value)=>act(()=>{const e=field(label);assert.ok(e,'Missing '+label);const proto=e.tagName==='TEXTAREA'?window.HTMLTextAreaElement.prototype:e.tagName==='SELECT'?window.HTMLSelectElement.prototype:window.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(e,value);e.dispatchEvent(new window.Event(e.tagName==='SELECT'?'change':'input',{bubbles:true}));});
  const render=props=>act(()=>root.render(React.createElement(Market,{data,onClose(){},...props}))),submit=kind=>document.querySelectorAll('form')[kind==='config'?0:1].dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));
  await run({data,render,field,button,fill,submit,requests,getBook:()=>clone(book),setBook:b=>{book=clone(b);},handle:f=>{handle=f;},text:()=>document.body.textContent});
 }finally{if(root)await act(()=>root.unmount());for(const [k,d] of before)if(d)Object.defineProperty(globalThis,k,d);else delete globalThis[k];dom.window.close();await vite.close();}
}
const order={id:'synthetic-order',topicId:'synthetic-topic',topicVersion:1,configVersion:1,symbol:'AAPL.US',side:'buy',qty:5,filledQty:0,limitPrice:'100',currency:'USD',status:'pending',expiresAt:'2026-10-04T14:00:00Z',thesis:'Synthetic thesis',trigger:'Synthetic trigger',invalidation:'Synthetic invalidation'};
const fillOrder=async fill=>{for(const [label,value] of [['股数','5'],['限价（证券原币）','100'],['含费用总预算 USD','550'],['订单到期（本机时间）','2026-10-04T22:00'],['持有复核截止（本机时间）','2026-10-05T22:00'],['交易假设','Synthetic thesis'],['触发依据','Synthetic trigger'],['失效条件','Synthetic invalidation']])await fill(label,value);};
test('market form sends one command while pending, even before the disabled state renders',()=>ui(async({render,fill,submit,requests,getBook,setBook,handle})=>{
 const pending=[];handle(async(path,method)=>{if(method==='POST')return new Promise(resolve=>pending.push(resolve));return {body:path.endsWith('/history')?[]:getBook()};});await render();await fillOrder(fill);
 try{await act(()=>{submit('order');submit('order');});assert.equal(requests.filter(r=>r.method==='POST').length,1);}finally{const b={...getBook(),version:2,orders:[order]};setBook(b);await act(async()=>pending.forEach(resolve=>resolve({body:b})));}
}));
test('successful market application remains saved and selected when optional history loading fails',()=>ui(async({render,fill,submit,getBook,setBook,handle,text})=>{
 handle(async(path,method)=>{if(method==='POST'){const b={...getBook(),version:2,orders:[order]};setBook(b);return {body:b};}if(path.endsWith('/history')&&getBook().version>1)return {status:503,body:{error:'Synthetic history unavailable'}};return {body:path.endsWith('/history')?[]:getBook()};});await render();await fillOrder(fill);await act(()=>submit('order'));
 assert.match(text(),/已保存/);assert.match(document.querySelector('[aria-label="市场订单详情"]').textContent,/Synthetic thesis/);assert.match(text(),/history unavailable|历史/);
}));
test('new configuration input survives an earlier save reply and later account refresh',()=>ui(async({data,render,field,fill,submit,getBook,setBook,handle})=>{
 let resolve,submitted;handle(async(path,method,payload)=>{if(method==='POST'){submitted=payload;return new Promise(r=>resolve=r);}return {body:path.endsWith('/history')?[]:getBook()};});await render();await fill('发行人仓位上限 %','18');await fill('变更说明','Synthetic saved revision');await act(()=>submit('config'));await fill('发行人仓位上限 %','19');
 const b={...getBook(),version:2,config:submitted.config};setBook(b);await act(async()=>resolve({body:b}));await render({data:{...data,serverTime:'2026-10-04T13:00:15Z'}});assert.equal(field('发行人仓位上限 %').value,'19');assert.equal(JSON.parse(sessionStorage.getItem('signal.market-simulation-draft:synthetic-instance-a:aggressive')).configEdited,true);
}));
test('a failed configuration write keeps its draft and releases the request guard for an explicit retry',()=>ui(async({render,field,fill,submit,requests,getBook,setBook,handle,text})=>{
 let fail=true;handle(async(path,method,payload)=>{if(method==='POST'){if(fail)return {status:409,body:{error:'Synthetic conflict'}};const b={...getBook(),version:2,config:payload.config};setBook(b);return {body:b};}return {body:path.endsWith('/history')?[]:getBook()};});await render();await fill('发行人仓位上限 %','17');await fill('变更说明','Retained after refusal');await act(()=>submit('config'));assert.match(text(),/Synthetic conflict/);assert.equal(field('发行人仓位上限 %').value,'17');assert.equal(requests.filter(r=>r.method==='POST').length,1);fail=false;await act(()=>submit('config'));assert.equal(requests.filter(r=>r.method==='POST').length,2);assert.equal(field('发行人仓位上限 %').value,'17');assert.match(text(),/已保存/);
}));
test('an earlier background account read cannot replace a successful command result',()=>ui(async({data,render,fill,submit,getBook,setBook,handle,text})=>{
 await render();await fillOrder(fill);let oldReply,hold=true;const oldBook=getBook();handle(async(path,method)=>{if(method==='POST'){const b={...getBook(),version:2,orders:[order]};setBook(b);return {body:b};}if(!path.endsWith('/history')&&hold){hold=false;return new Promise(r=>oldReply=r);}return {body:path.endsWith('/history')?[]:getBook()};});await render({data:{...data,serverTime:'2026-10-04T13:00:15Z'}});await act(()=>submit('order'));await act(async()=>oldReply({body:oldBook}));assert.match(text(),/账本 v2/);assert.match(document.querySelector('[aria-label="市场订单详情"]').textContent,/Synthetic thesis/);
}));
test('mounted account changes keep separate dataset drafts and do not copy old values into the new key',()=>ui(async({data,render,field,fill})=>{
 await render();await fill('股数','12');await render({data:{...data,runtime:{instance:{id:'synthetic-instance-b'}}}});assert.equal(field('股数').value,'');assert.equal(JSON.parse(sessionStorage.getItem('signal.market-simulation-draft:synthetic-instance-a:aggressive')).qty,'12');assert.equal(JSON.parse(sessionStorage.getItem('signal.market-simulation-draft:synthetic-instance-b:aggressive')).qty,undefined);await render();assert.equal(field('股数').value,'12');
}));
test('pending order inspection prevents changing the displayed order before the disabled state renders',()=>ui(async({render,button,getBook,setBook,handle})=>{
 const second={...order,id:'synthetic-second',symbol:'MSFT.US',thesis:'Second order'};setBook({...getBook(),orders:[order,second]});let resolve;handle(async(path)=>{if(path.endsWith('/review'))return new Promise(r=>resolve=r);return {body:path.endsWith('/history')?[]:getBook()};});await render();const orders=[...document.querySelectorAll('[aria-label="市场订单列表"] button')];await act(()=>orders.find(b=>b.textContent.includes('AAPL.US')).click());await act(()=>{button('核对当前风险与市场输入').click();orders.find(b=>b.textContent.includes('MSFT.US')).click();});assert.match(document.querySelector('[aria-label="市场订单详情"]').textContent,/Synthetic thesis/);await act(async()=>resolve({body:{eligible:false,reasons:['Synthetic input missing'],checkedAt:'2026-10-04T13:00:00Z'}}));assert.match(document.querySelector('[aria-label="市场订单详情"]').textContent,/Synthetic input missing/);
}));
