import test from 'node:test';import assert from 'node:assert/strict';import React,{act} from 'react';import {createServer} from 'vite';import {fileURLToPath} from 'node:url';import {JSDOM} from 'jsdom';
test('todo pages preserve drafts, prevent duplicate navigation, keep keyboard focus and require explicit revision reconciliation',async()=>{
 const vite=await createServer({configFile:false,root:fileURLToPath(new URL('../',import.meta.url)),server:{middlewareMode:true,watch:null,hmr:false},appType:'custom'}),dom=new JSDOM('<div id="root"></div>',{url:'http://localhost/'}),names=['window','document','HTMLElement','fetch','IS_REACT_ACT_ENVIRONMENT'],before=new Map(names.map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));let root;
 try{Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true});dom.window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};dom.window.HTMLDialogElement.prototype.close=function(){this.open=false;};const {createRoot}=await import('react-dom/client');root=createRoot(document.getElementById('root'));const {default:Inbox}=await vite.ssrLoadModule('/src/integrated/ObservationInbox.jsx');
 const item=(id,revision=1)=>({id:id.repeat(64),revision,title:'Synthetic '+id,state:'pending',symbols:[],createdAt:'2026-10-01T00:00:00Z'}),page=(items,nextCursor)=>({items,total:51,ceiling:51,nextCursor,revision:'51:0'});let revision=1,calls=0,release,failed=false;
 globalThis.fetch=async path=>{calls++;if(failed)throw Error('Synthetic failure');if(path.includes('before='))return await new Promise(resolve=>{release=()=>resolve(new Response(JSON.stringify(page([item('b')],null)),{headers:{'content-type':'application/json'}}));});return new Response(JSON.stringify(page([item('a',revision)],'2')),{headers:{'content-type':'application/json'}});};let submitted;
 const button=text=>[...document.querySelectorAll('button')].find(b=>b.textContent===text),click=async text=>act(async()=>button(text).click());
 await act(async()=>root.render(React.createElement(Inbox,{data:{runtime:{mode:'demo',instance:{id:'fixture'}},observationInbox:{revision:'51:0'}},mutate:async(path,method,input)=>{submitted=input;return null;},onClose:()=>{},onTopic:()=>{}})));assert.equal(calls,1);
 const input=document.querySelector('input');await act(()=>{Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype,'value').set.call(input,'Keep this note');input.dispatchEvent(new dom.window.Event('input',{bubbles:true}));});
 const next=button('下一页待办');next.focus();await click('下一页待办');assert.equal(calls,2);assert.equal(document.activeElement,next);await click('下一页待办');assert.equal(calls,2);await act(async()=>release());assert(document.body.textContent.includes('Synthetic b'));
 revision=2;await click('上一页待办');assert.equal(document.querySelector('input').value,'Keep this note');assert(document.body.textContent.includes('待办已由 v1 更新为 v2'));assert.equal(button('记录已处理').disabled,true);await click('已核对，保留说明继续');assert.equal(button('记录已处理').disabled,false);await click('记录已处理');assert.equal(submitted.revision,2);assert.equal(submitted.note,'Keep this note');assert.equal(document.querySelector('input').value,'Keep this note');
 failed=true;await click('刷新到最新待办');assert(!document.body.textContent.includes('Synthetic a'));assert.equal(document.querySelector('[role="alert"]').textContent,'Synthetic failure');assert.equal(button('刷新到最新待办').getAttribute('aria-disabled'),'false');
 }finally{if(root)await act(()=>root.unmount());for(const [k,d] of before)if(d)Object.defineProperty(globalThis,k,d);else delete globalThis[k];dom.window.close();await vite.close();}
});
