import test from 'node:test';
import assert from 'node:assert/strict';
import {openStore} from '../server/store.mjs';
import {openResearch} from '../server/research.mjs';
import {openPaper} from '../server/paper.mjs';
import {syncResearchWatches,assessTopic} from '../server/workflow.mjs';
import {createHandler} from '../server/index.mjs';
import {createService} from '../server/service.mjs';
const setup=()=>{let now='2026-09-24T10:00:00Z';const store=openStore(':memory:'),r=openResearch(store),p=openPaper(store,r,{clock:()=>now});return {store,r,p,setTime:v=>now=v};};
const proposal=(p,r,overrides={})=>({version:p.snapshot().version,clientId:crypto.randomUUID(),topicId:'memory-global',topicVersion:r.get('memory-global').version,symbol:'MU.US',side:'buy',qty:100,price:120,limit:125,reason:'Fixture causal hypothesis',holdingHorizon:'Recheck in 7 days',invalidation:'Orders contract',...overrides});
test('USD initialization is reproducible, zero-profit and isolated from live quotes',()=>{const {store,p}=setup();try{let b=p.snapshot();assert.equal(b.nav,1000000);assert.equal(b.pnl,0);assert.equal(b.positions.length,5);assert.equal(b.orders.length,3);assert.ok(b.exposurePct>34&&b.exposurePct<35);assert.equal(b.fills.length,0);assert.deepEqual(new Set(b.positions.map(p=>p.currency)),new Set(['USD','HKD','CNY']));assert.equal(b.positions.reduce((s,p)=>s+p.valueUSD,0)+b.cash,1000000);assert.equal(openPaper(store,openResearch(store)).snapshot().version,b.version);}finally{store.close();}});
test('approval consumes exactly once, costs reduce NAV, and history is immutable',()=>{const {store,p}=setup();try{const before=p.snapshot(),o=before.orders.find(o=>o.symbol==='ARM.US');assert.throws(()=>p.decide(o.id,{version:before.version,decision:'approve'}),/场景/);p.decide(o.id,{version:before.version,decision:'approve',confirmScenario:true});const after=p.snapshot();assert.equal(after.fills.length,1);assert.equal(after.positions.find(p=>p.symbol==='ARM.US').qty,200);assert.equal(after.cash,Math.round((before.cash-o.estimate.total)*100)/100);assert.ok(after.pnl<0);p.decide(o.id,{version:before.version,decision:'approve',confirmScenario:true});assert.equal(p.snapshot().version,after.version);assert.equal(p.history().length,2);const original=JSON.parse(store.db.prepare('SELECT payload FROM paper_versions WHERE version=1').get().payload);assert.equal(original.fills.length,0);}finally{store.close();}});
test('sell cannot exceed unreserved quantity; approved sale uses proportional cost and fees',()=>{const {store,p,r}=setup();try{assert.throws(()=>p.propose(proposal(p,r,{symbol:'SPOT.US',topicId:'spotify-access',topicVersion:r.get('spotify-access').version,side:'sell',qty:1000,price:500,limit:400})),/同方向|可卖/);const b=p.snapshot(),o=b.orders.find(o=>o.side==='sell'),pos=b.positions.find(p=>p.symbol==='SPOT.US');p.decide(o.id,{version:b.version,decision:'approve',confirmScenario:true});const a=p.snapshot();assert.equal(a.positions.find(p=>p.symbol==='SPOT.US').qty,pos.qty-o.qty);assert.ok(Math.abs(a.realized-(o.estimate.total-pos.costUSD*o.qty/pos.qty))<.02);assert.equal(a.orders.find(x=>x.id===o.id).status,'filled');}finally{store.close();}});
test('A/H issuer cap is combined and failed proposals leave no partial mutation',()=>{const {store,p,r}=setup();try{const b=p.snapshot();assert.throws(()=>p.propose(proposal(p,r,{symbol:'603986.SH',qty:2000,price:180,limit:190})),/发行人/);assert.equal(p.snapshot().version,b.version);assert.deepEqual(p.snapshot().orders,b.orders);}finally{store.close();}});
test('new real-event A/H and H/ADR pairs share pending issuer exposure',()=>{
 for(const [first,second,qty1,qty2] of [['002594.SZ','01211.HK',7100,2340],['09988.HK','BABA.US',7800,300]]){
  const {store,p,r}=setup();try{let t=r.create({title:'Cross-listing test',summary:'Test exposure only'});t=r.addCompany(t.id,{version:t.version,symbol:first,note:'Same issuer'});t=r.addCompany(t.id,{version:t.version,symbol:second,note:'Same issuer'});
   p.propose(proposal(p,r,{topicId:t.id,topicVersion:t.version,symbol:first,qty:qty1,price:100,limit:110}));
   const before=p.snapshot();assert.throws(()=>p.propose(proposal(p,r,{topicId:t.id,topicVersion:t.version,symbol:second,qty:qty2,price:100,limit:110})),/发行人/);assert.equal(p.snapshot().version,before.version);assert.equal(p.snapshot().fills.length,0);
  }finally{store.close();}
 }
});
test('cash and theme budgets reserve pending orders, not future sale proceeds',()=>{const {store,p,r}=setup();try{const b=p.snapshot();assert.ok(b.reserved>50000);p.updateParams({...b.params,version:b.version,themeCapPct:15,issuerCapPct:12});assert.throws(()=>p.propose(proposal(p,r)),/主题/);const n=p.snapshot();p.updateParams({...n.params,version:n.version,cashFloorPct:95});assert.throws(()=>p.propose(proposal(p,r,{qty:1})),/现金/);}finally{store.close();}});
test('stale book, changed research and expiration cannot execute; rejection releases reservation',()=>{const {store,p,r,setTime}=setup();try{let b=p.snapshot(),o=b.orders.find(o=>o.symbol==='ARM.US');assert.throws(()=>p.decide(o.id,{version:999,decision:'approve',confirmScenario:true}),/组合已变化/);r.update(o.topicId,{version:o.topicVersion,hypothesis:{logic:'Changed'}});assert.equal(p.snapshot().orders.find(x=>x.id===o.id).stale,true);assert.throws(()=>p.decide(o.id,{version:b.version,decision:'approve',confirmScenario:true}),/研究版本/);const before=b.reserved;p.decide(o.id,{version:b.version,decision:'reject'});b=p.snapshot();assert.ok(b.reserved<before);setTime('2026-09-26T10:00:00Z');o=b.orders.find(x=>x.side==='sell');assert.throws(()=>p.decide(o.id,{version:b.version,decision:'approve',confirmScenario:true}),/过期/);assert.equal(p.snapshot().fills.length,0);}finally{store.close();}});
test('proposals require association and complete thesis; idempotency and price bounds hold',()=>{const {store,p,r}=setup();try{assert.throws(()=>p.propose(proposal(p,r,{symbol:'AAPL.US'})),/关联/);assert.throws(()=>p.propose(proposal(p,r,{reason:''})),/依据/);assert.throws(()=>p.propose(proposal(p,r,{qty:1.5})),/无效/);assert.throws(()=>p.propose(proposal(p,r,{limit:119})),/限价/);const d=proposal(p,r);p.propose(d);assert.throws(()=>p.propose({...d,version:p.snapshot().version}),/已保存/);assert.equal(p.snapshot().orders.filter(o=>o.clientId===d.clientId).length,1);}finally{store.close();}});
test('position invalidation records a review but does not execute a sale',()=>{const {store,p}=setup();try{const b=p.snapshot();p.review({version:b.version,topicVersion:1,symbol:'SPOT.US',result:'invalidated',note:'Fixture adverse evidence'});const a=p.snapshot();assert.equal(a.reviews.length,1);assert.equal(a.fills.length,0);assert.deepEqual(a.positions,b.positions);}finally{store.close();}});
test('related global companies auto-follow once; manual removal and archived themes respected',()=>{const {store,r}=setup();try{const topics=r.list(),out=syncResearchWatches(store,topics);assert.ok(out.added.includes('MU.US'));assert.ok(out.added.includes('03986.HK'));assert.ok(out.added.includes('603986.SH'));assert.ok(out.added.includes('688008.SH'));store.removeWatch('MU.US');syncResearchWatches(store,topics);assert.equal(store.watchlist().some(w=>w.symbol==='MU.US'),false);assert.equal(assessTopic(r.get('memory-global')).automaticBuy,false);assert.ok(assessTopic(r.get('memory-global')).blockers.length>0);}finally{store.close();}});
test('HTTP paper routes preserve validation, rejection, and immutable history',async()=>{const store=openStore(':memory:'),service=createService(store),handler=createHandler(store,service);const call=async(method,url,data)=>{let status,result;await handler({headers:{host:'127.0.0.1:4179','content-type':'application/json'},method,url,async *[Symbol.asyncIterator](){yield JSON.stringify(data||{});}},{writeHead:v=>status=v,end:b=>result=JSON.parse(b)});return {status,result};};try{const initial=await call('GET','/api/data'),b=initial.result.paper;const res=await call('POST',`/api/paper/orders/${b.orders[0].id}`,{version:b.version,decision:'reject'});assert.equal(res.status,200);assert.equal(res.result.paper.orders[0].status,'rejected');assert.equal((await call('GET','/api/paper/history')).result.length,2);assert.equal((await call('GET','/api/bars?symbol=UNKNOWN.US')).status,400);}finally{store.close();}});

test('fallback minute quotes validate currency and isolate provider/timezone history',async()=>{const {parseYahooMinutes,instrument,fetchMinutes}=await import('../server/providers.mjs');const payload={chart:{result:[{meta:{symbol:'MU',currency:'USD',exchangeTimezoneName:'America/New_York'},timestamp:[1790193540,1790193600,1790193600],indicators:{quote:[{close:[null,110,111]}]}}]}};const q=parseYahooMinutes(payload,instrument('MU.US'));assert.equal(q.providerTimezone,'UTC');assert.equal(q.points.length,1);assert.equal(q.last,111);assert.throws(()=>parseYahooMinutes(payload,instrument('AAPL.US')),/不匹配/);const store=openStore(':memory:');try{store.saveQuote({...q,provider:'eastmoney-public',providerTimezone:'unverified',last:99,points:[{time:q.providerTime,close:99}]});store.saveQuote(q);const rows=store.db.prepare('SELECT * FROM quote_bars').all();assert.equal(rows.length,2);assert.equal(store.db.prepare('SELECT close FROM bars').get().close,99);let calls=0;const fallback=await fetchMinutes('MU.US',async url=>{calls++;if(url.includes('eastmoney'))throw new Error('fetch failed');return Response.json(payload);});assert.equal(fallback.provider,'yahoo-public-chart');assert.equal(calls,2);}finally{store.close();}});

test('due research reviews are visible and order validity ends at the exact deadline',()=>{const {store,r,p,setTime}=setup();try{let t=r.get('memory-global');t.hypothesis.reviewAt='2026-09-24';assert.equal(assessTopic(t,{today:'2026-09-24'}).reviewDue,true);assert.equal(assessTopic(t,{today:'2026-09-23'}).reviewDue,false);const b=p.snapshot(),o=b.orders[0];setTime(o.expiresAt);assert.equal(p.snapshot().orders[0].expired,true);assert.throws(()=>p.decide(o.id,{version:b.version,decision:'approve',confirmScenario:true}),/过期/);}finally{store.close();}});
