import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {openStore} from '../server/store.mjs';
import {createService} from '../server/service.mjs';
import {createHandler} from '../server/index.mjs';
import {digest,codexPrompt} from '../server/codex-research.mjs';
import {assertDatabaseMode} from '../server/runtime.mjs';
import {createBackup} from '../server/backup.mjs';
import {rehearseRecovery} from '../server/recovery-rehearsal.mjs';
const config={binary:'/test/codex',model:'test-model',timeoutMs:1000},at='2026-10-03T00:00:00Z';
const quotes=['虚构甲公司拟收购乙公司，仍需批准。','虚构丙公司终止丁项目，原因待核实。'],body=quotes.join('')+'所有信息仅为合成流程样例，不构成独立证据。'.repeat(20);
const decomposition=()=>({events:quotes.map((quote,i)=>({title:`合成事项${i}`,actor:i?'虚构丙':'虚构甲',action:i?'终止':'拟收购',object:i?'丁项目':'乙公司',stage:'待核',eventTime:'未知',quote,quoteField:'body',boundaryReason:'不同主体和对象的两个具体事项',timeEvidence:{basis:'unknown',quote:'',quoteField:'none'},timeRole:'unknown'})),scopeNote:'仅为合成已提供材料，不代表完整',missingEvidence:['核实原始公告']});
function extraction(p,value=decomposition()){const rawOutput=JSON.stringify(value);return {status:'candidate',reviewStatus:'unreviewed',decomposition:value,rawOutput,trace:{model:config.model,inputHash:p.inputHash,outputHash:digest(rawOutput)}};}
function dossier(p){const v={sections:['facts','materiality','companies','scenarios','conditions'].map(id=>({id,title:id,paragraphs:[p.input.eventExtraction?.event.title||'来源整体的合成研究'],sourceIds:[]})),missingEvidence:['核实事项范围']},rawOutput=JSON.stringify(v);return {status:'candidate',reviewStatus:'unreviewed',...v,rawOutput,trace:{model:config.model,inputHash:p.inputHash,topicId:p.input.topicId,topicVersion:p.input.topicVersion,outputHash:digest(rawOutput)}};}
function fixture({path=':memory:',extractRunner=async p=>extraction(p),modelRunner=async p=>dossier(p),enable=true}={}){
 let clock=Date.parse(at),extractCalls=0,modelCalls=0;const packets=[],store=openStore(path);assertDatabaseMode(store,'research');
 const service=createService(store,{mode:'research',modelConfig:config,now:()=>clock,modelRunner:async p=>{modelCalls++;packets.push(p);return modelRunner(p);},materialEventRunner:async p=>{extractCalls++;return extractRunner(p);},sourceReader:async url=>({url,title:'合成来源正文',sourceName:'合成',body,scope:'extracted-text'})});
 const queue=service.researchPipeline;if(queue.snapshot().settings.version===1)queue.configure({version:1,dailyCalls:10,includeClues:false,extractEvents:enable});
 const news={id:digest('pipeline-events-news'),title:'Synthetic company files for bankruptcy',url:'https://example.com/source',publisher:'合成',publishedAt:at};
 const add=()=>{store.ingest([news],at);service.research.process();};
 const step=()=>{service.controlOperation('discovery','resume');return service.runOperation('discovery');};
 const finish=async()=>{const s=queue.snapshot();for(const i of s.items)if(i.runId)await service.modelResearch.wait(i.runId);for(const j of s.events.items)if(j.runId)await (j.kind==='extract'?service.materialEvents:service.modelResearch).wait(j.runId);return queue.snapshot();};
 const prepare=async()=>{add();await step();await finish();await step();await finish();return queue.snapshot().events.items.find(j=>j.kind==='extract');};
 const choose=(job,index=0,action='create')=>service.materialEvents.decide(job.topicId,job.runId,{eventIndex:index,version:0,action,note:'本人核对合成事项范围'});
 return {store,service,queue,news,packets,add,step,finish,prepare,choose,get modelCalls(){return modelCalls;},get extractCalls(){return extractCalls;},advance(ms){clock+=ms;},async close(){await service.close();store.close();}};
}
test('opt-in extraction proposes multiple events and only a human-selected occurrence gets its own scoped draft',async()=>{
 const f=fixture();try{const book=f.service.paper.snapshot(),job=await f.prepare(),source=f.service.research.get(job.topicId);assert.equal(job.eventCount,2);assert.equal(f.extractCalls,1);assert.equal(f.service.research.list().length,1);await f.step();assert.equal(f.modelCalls,1);assert.equal(f.store.db.prepare('SELECT count(*) n FROM material_event_decisions').get().n,0);
 const created=f.choose(job),child=created.reviews[0][0].topicId;f.choose(job,1,'reject');await f.step();await f.finish();const s=f.queue.snapshot(),draft=s.events.items.find(j=>j.kind==='dossier');assert.equal(draft.topicId,child);assert.equal(draft.status,'candidate');assert.equal(f.modelCalls,2);assert.equal(f.extractCalls,1);assert.equal(s.callsInLast24Hours,3);const p=f.packets[1];assert.equal(p.input.topicId,child);assert.equal(p.input.eventExtraction.eventIndex,0);assert.equal(p.input.eventExtraction.event.quote,quotes[0]);assert.equal(p.input.eventExtraction.runId,job.runId);assert.match(codexPrompt(p),/不把整篇材料的公司、影响或结论投射到当前事项/);assert.equal(f.service.research.get(child).dossier,undefined);assert.equal(f.service.research.get(child).hypothesis.action,'observe');assert.deepEqual(f.service.research.get(job.topicId),source);assert.deepEqual(f.service.paper.snapshot(),book);assert.equal(f.store.db.prepare('SELECT count(*) n FROM research_materials').get().n,1);await f.step();assert.equal(f.modelCalls,2);assert.equal(f.service.research.list().length,2);
 }finally{await f.close();}
});
test('legacy configuration keeps extraction off and changing it does not backfill already scanned items',async()=>{
 const f=fixture({enable:false});try{f.add();f.queue.scan({assertActive(){}});f.queue.configure({version:2,dailyCalls:10,includeClues:false,extractEvents:true});await f.step();await f.finish();await f.step();assert.equal(f.extractCalls,0);assert.equal(f.queue.snapshot().events.items.length,0);const s=f.queue.snapshot().settings;f.queue.configure({version:s.version,dailyCalls:8,includeClues:false});assert.equal(f.queue.snapshot().settings.extractEvents,true);assert.throws(()=>f.queue.configure({version:4,dailyCalls:10,includeClues:false,extractEvents:'true'}),/无效/);
 }finally{await f.close();}
});
test('an empty decomposition is retained without generating children or retrying the model',async()=>{
 const f=fixture({extractRunner:async p=>extraction(p,{...decomposition(),events:[]})});try{const j=await f.prepare();assert.equal(j.eventCount,0);await f.step();await f.step();assert.equal(f.extractCalls,1);assert.equal(f.modelCalls,1);assert.equal(f.queue.snapshot().events.items.length,1);assert.equal(f.service.research.list().length,1);}finally{await f.close();}
});
test('parent drafts, extraction and selected-event drafts all consume the same rolling quota',async()=>{
 const f=fixture();try{f.queue.configure({version:2,dailyCalls:1,includeClues:false});f.add();await f.step();await f.finish();await f.step();assert.equal(f.extractCalls,0);f.advance(86400001);await f.step();await f.finish();const j=f.queue.snapshot().events.items[0];f.choose(j);await f.step();assert.equal(f.modelCalls,1);assert.equal(f.queue.snapshot().events.counts.queued,1);f.advance(86400001);await f.step();await f.finish();assert.equal(f.modelCalls,2);assert.equal(f.queue.snapshot().callsInLast24Hours,1);}finally{await f.close();}
});
test('failed extraction requires explicit retry and retains the original run and charged attempt',async()=>{
 let fail=true;const f=fixture({extractRunner:async p=>{if(fail)throw Error('synthetic failure');return extraction(p);}});try{let j=await f.prepare();assert.equal(j.status,'failed');const first=j.runId;await f.step();assert.equal(f.extractCalls,1);fail=false;f.queue.retryEvent(j.id);await f.step();await f.finish();j=f.queue.snapshot().events.items[0];assert.equal(j.status,'candidate');assert.equal(j.attempts.length,2);assert.equal(f.service.materialEvents.get(j.topicId,first).status,'failed');assert.equal(f.queue.snapshot().callsInLast24Hours,3);}finally{await f.close();}
});
test('failed child drafts are not retried implicitly or duplicated when explicitly retried',async()=>{
 let fail=true;const f=fixture({modelRunner:async p=>{if(p.input.eventExtraction&&fail)throw Error('synthetic failure');return dossier(p);}});try{const j=await f.prepare();f.choose(j);await f.step();await f.finish();const child=f.queue.snapshot().events.items.find(v=>v.kind==='dossier');assert.equal(child.status,'failed');await f.step();assert.equal(f.modelCalls,2);fail=false;f.queue.retryEvent(child.id);await f.step();await f.finish();const next=f.queue.snapshot().events.items.find(v=>v.id===child.id);assert.equal(next.status,'candidate');assert.equal(next.attempts.length,2);assert.equal(f.service.modelResearch.get(child.topicId,child.runId).status,'failed');assert.equal(f.service.research.list().length,2);}finally{await f.close();}
});
test('both extraction and child-run linkage roll back with a failed budget write before calling models',async()=>{
 for(const kind of ['extract','dossier']){const f=fixture();try{if(kind==='extract'){f.add();await f.step();await f.finish();}else{const j=await f.prepare();f.choose(j);}const before=f.queue.snapshot().callsInLast24Hours,calls=f.modelCalls+f.extractCalls;f.store.db.exec("CREATE TRIGGER reject_event_attempt BEFORE INSERT ON research_pipeline_attempts BEGIN SELECT RAISE(ABORT,'synthetic storage failure'); END");await f.step();assert.equal(f.modelCalls+f.extractCalls,calls);assert.equal(f.queue.snapshot().callsInLast24Hours,before);assert.equal(f.store.db.prepare('SELECT count(*) n FROM model_job_lease').get().n,0);assert.equal(f.queue.snapshot().events.items.find(j=>j.kind===kind).status,'queued');f.store.db.exec('DROP TRIGGER reject_event_attempt');await f.step();await f.finish();assert.equal(f.modelCalls+f.extractCalls,calls+1);}finally{await f.close();}}
});
test('initial extraction plans are atomic with the source dossier and failed start does not leave orphan jobs',async()=>{
 const f=fixture();try{f.add();f.store.db.exec("CREATE TRIGGER reject_plan BEFORE INSERT ON research_pipeline_event_jobs BEGIN SELECT RAISE(ABORT,'synthetic storage failure'); END");await f.step();assert.equal(f.modelCalls,0);assert.equal(f.queue.snapshot().events.items.length,0);assert.equal(f.queue.snapshot().callsInLast24Hours,0);assert.equal(f.store.db.prepare('SELECT count(*) n FROM model_research_runs').get().n,0);f.store.db.exec('DROP TRIGGER reject_plan');f.queue.retry(f.queue.snapshot().items[0].id);await f.step();await f.finish();assert.equal(f.queue.snapshot().events.items.length,1);}finally{await f.close();}
});
test('changed or archived selected research and corrupted origin remain recorded without automatic drafts',async()=>{
 for(const change of ['edited','archived','origin']){const f=fixture();try{const j=await f.prepare(),r=f.choose(j),id=r.reviews[0][0].topicId;if(change==='origin'){const run=JSON.parse(f.store.db.prepare('SELECT payload FROM material_event_runs WHERE id=?').get(j.runId).payload);run.candidate.decomposition.events[0].title='Altered candidate';f.store.db.prepare('UPDATE material_event_runs SET payload=? WHERE id=?').run(JSON.stringify(run),j.runId);}else f.service.research.update(id,{version:1,...(change==='archived'?{status:'archived'}:{nextEvidence:'本人已编辑研究，请停止自动准备'})});await f.step();assert.equal(f.modelCalls,1);assert.equal(f.queue.snapshot().events.items.find(v=>v.kind==='dossier').status,'invalidated');await f.step();assert.equal(f.queue.snapshot().events.items.length,2);}finally{await f.close();}}
});
test('source revision or frozen prompt mismatch invalidates pending extraction without changing the original plan',async()=>{
 for(const change of ['news','prompt']){const f=fixture();try{f.add();await f.step();await f.finish();if(change==='news')f.store.ingest([{...f.news,title:'Revised bankruptcy headline'}],'2026-10-03T01:00:00Z');else{const row=f.store.db.prepare('SELECT id,payload FROM research_pipeline_event_jobs').get(),p=JSON.parse(row.payload);p.executionHash='old-prompt';f.store.db.prepare('UPDATE research_pipeline_event_jobs SET payload=? WHERE id=?').run(JSON.stringify(p),row.id);}const before=f.store.db.prepare('SELECT payload FROM research_pipeline_event_jobs').get().payload;await f.step();assert.equal(f.extractCalls,0);assert.equal(f.queue.snapshot().events.counts.invalidated,1);assert.equal(f.store.db.prepare('SELECT payload FROM research_pipeline_event_jobs').get().payload,before);}finally{await f.close();}}
});
test('pause before extraction commit prevents a late model call and keeps the plan queued',async()=>{
 const f=fixture();try{f.add();await f.step();await f.finish();const start=f.service.materialEvents.start;f.service.materialEvents.start=(...args)=>{f.service.controlOperation('discovery','pause');return start(...args);};await f.step();assert.equal(f.extractCalls,0);assert.equal(f.queue.snapshot().events.counts.queued,1);assert.equal(f.store.db.prepare('SELECT count(*) n FROM material_event_runs').get().n,0);assert.equal(f.queue.snapshot().callsInLast24Hours,1);}finally{await f.close();}
});
test('separate services share the extraction lease and restart never repeats a completed child',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'pipeline-event-shared-')),path=join(dir,'fixture.sqlite');let finish,other;const f=fixture({path,extractRunner:p=>new Promise(resolve=>{finish=()=>resolve(extraction(p));})});
 try{f.add();await f.step();await f.finish();other=fixture({path});await f.step();await other.step();assert.equal(f.extractCalls,1);assert.equal(other.extractCalls,0);finish();await f.finish();const j=f.queue.snapshot().events.items[0];f.choose(j);await f.step();await f.finish();f.service.controlOperation('discovery','pause');const before=f.queue.snapshot();await other.close();other=null;await f.close();other=fixture({path});assert.deepEqual(other.queue.snapshot(),before);assert(other.service.operations().tasks.discovery.paused);assert.equal(other.modelCalls+other.extractCalls,0);
 }finally{finish?.();if(other)await other.close();else await f.close();rmSync(dir,{recursive:true,force:true});}
});
test('event retry API enforces source revision, origin, instance and restore checks',async()=>{
 const f=fixture({extractRunner:async()=>{throw Error('synthetic failure');}});try{const j=await f.prepare();f.service.instance={id:'fixture-instance'};const handler=createHandler(f.store,f.service),call=async(headers={},body={})=>{let status;await handler({method:'POST',url:`/api/research-pipeline/events/${j.id}/retry`,headers:{host:'127.0.0.1:4179','content-type':'application/json','x-signal-instance':'fixture-instance',...headers},async *[Symbol.asyncIterator](){yield JSON.stringify(body);}},{writeHead:n=>status=n,end(){}});return status;};assert.equal(await call({'x-signal-instance':'wrong'}),409);assert.equal(await call({origin:'https://example.com'}),403);assert.equal(await call({},{extra:true}),400);f.store.db.prepare("INSERT INTO settings VALUES('restore_review_required','1')").run();assert.equal(await call(),409);f.store.db.prepare("DELETE FROM settings WHERE key='restore_review_required'").run();assert.equal(await call(),200);await f.step();await f.finish();f.store.ingest([{...f.news,title:'Revised bankruptcy report'}],'2026-10-03T01:00:00Z');assert.equal(await call(),400);assert.equal(f.extractCalls,2);}finally{await f.close();}
});
test('backup and restore preserve extraction, human decisions, pending child drafts and old material without model calls',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'pipeline-event-recovery-')),path=join(dir,'source.sqlite'),f=fixture({path});try{const j=await f.prepare();f.choose(j);f.queue.configure({version:2,dailyCalls:2,includeClues:false});await f.step();f.service.controlOperation('discovery','pause');const b=await createBackup(path,join(dir,'backups')),report=await rehearseRecovery(b.directory,join(dir,'drills'));assert(report.passed,JSON.stringify(report));assert.equal(report.original.tables.research_pipeline_event_jobs.count,2);assert.equal(report.original.tables.material_event_decisions.count,1);assert(report.idle.identical&&report.rollback.identical&&report.snapshotUnchanged);assert.equal(report.networkAttempts,0);}finally{await f.close();rmSync(dir,{recursive:true,force:true});}
});
test('two selected occurrences sharing one article retain separate research, input hashes and model drafts',async()=>{
 const f=fixture();try{const job=await f.prepare(),first=f.choose(job,0).reviews[0][0].topicId,second=f.choose(job,1).reviews[1][0].topicId;await f.step();await f.finish();await f.step();await f.finish();const jobs=f.queue.snapshot().events.items.filter(j=>j.kind==='dossier');assert.equal(jobs.length,2);assert(jobs.every(j=>j.status==='candidate'));assert.equal(f.queue.snapshot().callsInLast24Hours,4);const packets=f.packets.filter(p=>p.input.eventExtraction);assert.equal(new Set(packets.map(p=>p.inputHash)).size,2);for(const [i,id] of [first,second].entries()){const p=packets.find(p=>p.input.topicId===id);assert.equal(p.input.eventExtraction.eventIndex,i);assert.equal(p.input.eventExtraction.event.quote,quotes[i]);assert.equal(p.input.evidence.length,1);assert.equal(f.service.research.get(id).dossier,undefined);}assert.equal(f.store.db.prepare('SELECT count(*) n FROM research_materials').get().n,1);await f.step();assert.equal(f.modelCalls,3);assert.equal(f.service.research.list().length,3);}finally{await f.close();}
});
