import test from 'node:test';import assert from 'node:assert/strict';import React,{act} from 'react';import {createServer} from 'vite';import {fileURLToPath} from 'node:url';import {JSDOM} from 'jsdom';
async function ui(run){
 const vite=await createServer({configFile:false,root:fileURLToPath(new URL('../',import.meta.url)),server:{middlewareMode:true,watch:null},appType:'custom'}),dom=new JSDOM('<div id="root"></div>',{url:'http://localhost/'}),names=['window','document','HTMLElement','IS_REACT_ACT_ENVIRONMENT'],before=new Map(names.map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));let root;dom.window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};dom.window.HTMLDialogElement.prototype.close=function(){this.open=false;};
 try{Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true});const {createRoot}=await import('react-dom/client');root=createRoot(document.getElementById('root'));const forms=await vite.ssrLoadModule('/src/major/ResearchForms.jsx');const button=t=>[...document.querySelectorAll('button')].find(x=>x.textContent===t),area=t=>[...document.querySelectorAll('label')].find(x=>x.firstChild?.textContent===t).querySelector('textarea,input,select');
 const edit=async(label,value)=>act(()=>{const e=area(label);Object.getOwnPropertyDescriptor(Object.getPrototypeOf(e),'value').set.call(e,value);e.dispatchEvent(new dom.window.Event('input',{bubbles:true}));e.dispatchEvent(new dom.window.Event('change',{bubbles:true}));});
 await run({...forms,render:n=>act(()=>root.render(n)),button,area,edit,submit:()=>act(async()=>document.querySelector('form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true})))});
 }finally{if(root)await act(()=>root.unmount());for(const [k,d] of before)if(d)Object.defineProperty(globalThis,k,d);else delete globalThis[k];dom.window.close();await vite.close();}
}

const topic=()=>({id:crypto.randomUUID(),createdAt:'2026-10-04',title:'Synthetic topic',version:1,chain:[{id:'step',title:'Synthetic link'}]});
test('new research survives close and failed submit, saves once and starts clean after success',()=>ui(async({NewTopic,render,button,area,edit,submit})=>{
 let calls=0,closed=0,succeed=false;const view=()=>React.createElement(NewTopic,{busy:false,onClose:()=>closed++,onCreate:async data=>{calls++;assert.equal(data.title,'Synthetic title');return succeed?{createdTopicId:'created'}:null;}});
 await render(view());await edit('主题标题','Synthetic title');await edit('初始假设','Synthetic summary');await render(null);await render(view());assert.equal(area('主题标题').value,'Synthetic title');await submit();assert.equal(closed,0);assert.equal(area('初始假设').value,'Synthetic summary');succeed=true;await submit();assert.equal(calls,2);assert.equal(closed,1);await render(null);await render(view());assert.equal(area('主题标题').value,'');
}));
test('evidence draft freezes original research version, blocks concurrent changes and supports explicit discard',()=>ui(async({AddEvidence,render,button,area,edit,submit})=>{
 let t=topic(),calls=[],closed=0;const view=()=>React.createElement(AddEvidence,{topic:t,busy:false,onClose:()=>closed++,mutate:async(p,m,d)=>{calls.push(d);return {research:{topics:[{...t,version:t.version+1}]}};}});
 await render(view());await edit('证据或线索','Keep evidence');await edit('为什么与这个环节有关？','Keep interpretation');await render(null);await render(view());assert.equal(area('证据或线索').value,'Keep evidence');t={...t,version:2};await render(view());assert(button('保存到证据链').disabled);await submit();assert.equal(calls.length,0);await act(()=>button('丢弃证据草稿并载入最新版本').click());assert.equal(area('证据或线索').value,'');await edit('证据或线索','Fresh evidence');await submit();assert.equal(calls[0].version,2);assert.equal(closed,1);
}));
test('verification drafts are evidence-specific, preserve failure and block a newer research version',()=>ui(async({VerifyEvidence,render,button,area,edit,submit})=>{
 let t=topic(),calls=0,which='a',succeed=false;const view=()=>React.createElement(VerifyEvidence,{key:which,topic:t,evidence:{id:which,claim:'Synthetic '+which,stance:'unverified'},busy:false,onClose(){},mutate:async()=>{calls++;return succeed?{research:{topics:[{...t,version:t.version+1}]}}:null;}});
 await render(view());await edit('核验依据与限制','Evidence A review');which='b';await render(view());assert.equal(area('核验依据与限制').value,'');await edit('核验依据与限制','Evidence B review');which='a';await render(view());assert.equal(area('核验依据与限制').value,'Evidence A review');await submit();assert.equal(calls,1);assert.equal(area('核验依据与限制').value,'Evidence A review');t={...t,version:4,evidence:[{id:'a',claim:'Synthetic a',stance:'against'}]};await render(view());assert(button('保存核验版本').disabled);await submit();assert.equal(calls,1);await act(()=>button('丢弃核验草稿并载入最新版本').click());assert.equal(area('核验依据与限制').value,'');assert.equal(area('对本主题的作用').value,'against');succeed=true;await edit('核验依据与限制','New review');await submit();await render(null);await render(view());assert.equal(area('核验依据与限制').value,'');
}));
test('late create response neither erases a reopened newer draft nor closes its dialog',()=>ui(async({NewTopic,render,button,area,edit})=>{
 let resolve,closed=0,selected=0;const pending=new Promise(r=>resolve=r),view=()=>React.createElement(NewTopic,{busy:false,onClose:()=>closed++,onCreate:()=>pending,onCreated:()=>selected++});
 await render(view());await edit('主题标题','Submitted title');await edit('初始假设','Submitted summary');await act(()=>{document.querySelector('form').dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));});await render(null);await render(view());await edit('主题标题','Newer title');await act(async()=>resolve({createdTopicId:'created'}));assert.equal(area('主题标题').value,'Newer title');assert.equal(closed,0);assert.equal(selected,0);await act(()=>button('丢弃新主题草稿').click());
}));
