import test from 'node:test';import assert from 'node:assert/strict';import React,{act} from 'react';import {createServer} from 'vite';import {fileURLToPath} from 'node:url';import {JSDOM} from 'jsdom';
test('history uses bounded summaries, pins pages across live changes, prevents duplicate clicks and retries without losing context',async()=>{
 const vite=await createServer({configFile:false,root:fileURLToPath(new URL('../',import.meta.url)),server:{middlewareMode:true,watch:null,hmr:false},appType:'custom'}),dom=new JSDOM('<div id="root"></div>',{url:'http://localhost/'}),names=['window','document','HTMLElement','fetch','IS_REACT_ACT_ENVIRONMENT'],before=new Map(names.map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));let root;
 try{
 Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true});const {createRoot}=await import('react-dom/client');root=createRoot(document.getElementById('root'));const {default:History}=await vite.ssrLoadModule('/src/major/ResearchHistory.jsx');
 const topic={id:'topic',version:26,evidence:[],hypothesis:{logic:'Synthetic',trigger:'',invalidation:'',industryHorizon:'',holdingHorizon:''},companies:[],claims:[]},row=v=>({version:v,recordedAt:'2026-10-04T00:00:00Z',reason:'Synthetic revision'}),page=(ceiling,old=false)=>({items:old?[row(1)]:Array.from({length:25},(_,i)=>row(ceiling-i)),ceiling,total:ceiling,nextCursor:old?null:ceiling-24}),detail=v=>({...row(v),topic:{...topic,version:v,evidence:[{id:'old',claim:'Prior evidence'}]},previousVersion:v===1?null:v-1,addedEvidenceIds:v===1?['old']:[]});
 let latest=26,release,failPage=false,failDetail=false;const calls=[];globalThis.fetch=async path=>{calls.push(path);let value;if(path.includes('?')){if(failPage)throw Error('Synthetic list failure');if(path.includes('before='))value=await new Promise(resolve=>{release=()=>resolve(page(Number(new URL('http://fixture'+path).searchParams.get('ceiling')),true));});else value=page(latest);}else{if(failDetail)throw Error('Synthetic detail failure');value=detail(Number(path.split('/').at(-1)));}return new Response(JSON.stringify(value),{headers:{'content-type':'application/json'}});};
 const render=version=>act(async()=>root.render(React.createElement(History,{topic:{...topic,version}}))),button=text=>[...document.querySelectorAll('button')].find(b=>b.textContent===text),click=text=>act(async()=>button(text).click());
 await render(26);assert.equal(document.querySelectorAll('.m-history-version').length,25);assert.equal(calls.length,2);assert.match(calls[0],/view=summary&limit=25/);assert.match(calls[1],/history\/26$/);assert.match(document.body.textContent,/本版新增 0 条/);
 const next=button('下一页研究版本');next.focus();await click('下一页研究版本');await click('下一页研究版本');assert.equal(calls.filter(x=>x.includes('before=')).length,1);assert.equal(document.activeElement,next);assert.equal(next.getAttribute('aria-disabled'),'true');
 latest=27;await render(27);assert.match(document.body.textContent,/已有新版本/);await act(async()=>release());assert.match(calls.at(-2),/ceiling=26&before=2/);assert.match(document.body.textContent,/第 2 页/);assert.match(document.body.textContent,/本版新增 1 条/);assert.equal(button('下一页研究版本').getAttribute('aria-disabled'),'true');
 failPage=true;await click('上一页研究版本');assert.match(document.querySelector('[role="alert"]').textContent,/Synthetic list failure/);assert.match(document.body.textContent,/第 2 页/);failPage=false;failDetail=true;await click('重试读取版本列表');assert.match(document.body.textContent,/第 1 页/);assert.match(document.body.textContent,/Synthetic detail failure/);failDetail=false;await click('重试读取此版研究');assert.match(document.body.textContent,/当时判断：Synthetic/);assert.equal(document.querySelector('[role="alert"]'),null);
 await click('刷新到最新研究版本');assert.match(document.body.textContent,/固定至 v27/);assert.equal(document.querySelectorAll('.m-history-version').length,25);assert(!document.body.textContent.includes('已有新版本'));
 }finally{if(root)await act(()=>root.unmount());for(const [k,d] of before)if(d)Object.defineProperty(globalThis,k,d);else delete globalThis[k];dom.window.close();await vite.close();}
});
