import test from 'node:test';
import assert from 'node:assert/strict';
import React,{act} from 'react';
import {createServer} from 'vite';
import {fileURLToPath} from 'node:url';
import {JSDOM} from 'jsdom';
test('queue UI submits bounded configuration and explicit retry while keeping source titles escaped',async()=>{
 const vite=await createServer({configFile:false,root:fileURLToPath(new URL('../',import.meta.url)),server:{middlewareMode:true,watch:null},appType:'custom'}),dom=new JSDOM('<div id="root"></div>',{url:'http://localhost/'}),keys=['window','document','HTMLElement','IS_REACT_ACT_ENVIRONMENT'],before=Object.fromEntries(keys.map(k=>[k,globalThis[k]]));let root;
 try{Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true});const {createRoot}=await import('react-dom/client'),{ResearchPipeline}=await vite.ssrLoadModule('/src/integrated/Operations.jsx');root=createRoot(document.getElementById('root'));const calls=[],pipeline={enabled:true,settings:{version:3,dailyCalls:7,includeClues:false},callsInLast24Hours:2,counts:{failed:1},items:[{id:'fixture-id',title:'<script>合成新闻</script>',revision:2,status:'failed',topicId:'fixture-topic',reason:'来源待处理'}],relations:{counts:{failed:1,candidate:1},items:[{id:'relation-id',status:'failed',source:{id:'new',title:'新报道',version:2},target:{id:'old',title:'已有研究',version:3}},{id:'done',status:'candidate',source:{id:'new',title:'新报道',version:2},target:{id:'old',title:'已有研究',version:3},scopes:['extracted-text','excerpt'],comparison:{relation:'unrelated',reason:'未见足够关联',left:{quote:'<script>新材料</script>'},right:{quote:'合成已有材料'}}}]}};const render=busy=>root.render(React.createElement(ResearchPipeline,{pipeline,busy,onChange:(...args)=>calls.push(args)}));await act(()=>render(false));assert.equal(document.querySelectorAll('script').length,0);assert.match(document.body.textContent,/过去24小时已调用 2 次/);assert.equal(document.querySelector('a').getAttribute('href'),'/?topic=fixture-topic');await act(()=>document.querySelector('input[type=checkbox]').click());await act(()=>document.querySelector('form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true})));assert.deepEqual(calls[0],['configure',{version:3,dailyCalls:7,includeClues:true}]);const retry=[...document.querySelectorAll('button')].find(b=>b.textContent==='重试此项');await act(()=>retry.click());assert.deepEqual(calls[1],['retry',{id:'fixture-id'}]);const relationRetry=[...document.querySelectorAll('button')].find(b=>b.textContent==='重试比较');await act(()=>relationRetry.click());assert.deepEqual(calls[2],['retry-relation',{id:'relation-id'}]);assert.match(document.body.textContent,/没有足够关联/);assert.match(document.body.textContent,/网页提取文本 \/ 摘录/);assert.equal(document.querySelectorAll('script').length,0);pipeline.relations.items[0].stale=true;await act(()=>render(false));assert(relationRetry.disabled);assert.match(document.body.textContent,/依据已变化/);await act(()=>render(true));assert(document.querySelector('fieldset').disabled);assert([...document.querySelectorAll('button')].every(b=>b.disabled));
 }finally{if(root)await act(()=>root.unmount());for(const k of keys)if(before[k]===undefined)delete globalThis[k];else globalThis[k]=before[k];dom.window.close();await vite.close();}
});
