import test from 'node:test';import assert from 'node:assert/strict';import React,{act} from 'react';import {createServer} from 'vite';import {fileURLToPath} from 'node:url';import {JSDOM} from 'jsdom';
async function ui(run){
 const vite=await createServer({configFile:false,root:fileURLToPath(new URL('../',import.meta.url)),server:{middlewareMode:true,watch:null},appType:'custom'}),dom=new JSDOM('<div id="root"></div>',{url:'http://localhost/'}),names=['window','document','HTMLElement','IS_REACT_ACT_ENVIRONMENT'],before=new Map(names.map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));let root;
 try{Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true});const {createRoot}=await import('react-dom/client');root=createRoot(document.getElementById('root'));const {default:Claims}=await vite.ssrLoadModule('/src/major/ClaimsEditor.jsx'),{default:Detail}=await vite.ssrLoadModule('/src/major/TopicDetail.jsx');const button=t=>[...document.querySelectorAll('button')].find(x=>x.textContent===t),area=t=>[...document.querySelectorAll('label')].find(x=>x.firstChild?.textContent===t).querySelector('textarea');
 const edit=async(label,value)=>act(()=>{const e=area(label);Object.getOwnPropertyDescriptor(dom.window.HTMLTextAreaElement.prototype,'value').set.call(e,value);e.dispatchEvent(new dom.window.Event('input',{bubbles:true}));e.dispatchEvent(new dom.window.Event('change',{bubbles:true}));});
 await run({Claims,Detail,render:n=>act(()=>root.render(n)),button,area,edit,submit:()=>act(async()=>document.querySelector('form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true})))});
 }finally{if(root)await act(()=>root.unmount());for(const [k,d] of before)if(d)Object.defineProperty(globalThis,k,d);else delete globalThis[k];dom.window.close();await vite.close();}
}
const topic=()=>({id:crypto.randomUUID(),createdAt:'2026-10-04',title:'Synthetic edit',version:1,status:'active',evidence:[],claims:[],companies:[],hypothesis:{logic:'initial',trigger:'',invalidation:'',industryHorizon:'',holdingHorizon:'',action:'observe',reviewAt:''},nextEvidence:'Initial next',coverage:{families:[],support:0,against:0,pending:0,sources:[],origins:[],missingSteps:[]},chain:[]});
test('claim edit restores on remount, retains original base after conflict and clears only after successful save',()=>ui(async({Claims,render,button,area,edit,submit})=>{
 let t=topic(),calls=[];const mutate=async(path,method,data)=>{calls.push(data);return {research:{topics:[{...t,version:t.version+1}]}};};const view=()=>React.createElement(Claims,{topic:t,busy:false,mutate});await render(view());await act(()=>button('＋ 新增独立主张').click());await edit('可检验的具体主张','Synthetic preserved claim');await edit('本次新增或修订原因','Synthetic rationale');await render(null);await render(view());assert.equal(area('可检验的具体主张').value,'Synthetic preserved claim');t={...t,version:2};await render(view());assert(button('保存主张版本').disabled);await submit();assert.equal(calls.length,0);assert.equal(area('可检验的具体主张').value,'Synthetic preserved claim');
 await act(()=>button('丢弃主张草稿').click());await act(()=>button('＋ 新增独立主张').click());await edit('可检验的具体主张','New draft');await edit('本次新增或修订原因','New reason');await submit();assert.equal(calls[0].version,2);assert(button('＋ 新增独立主张'));await render(null);await render(view());assert(button('＋ 新增独立主张'));
}));
test('hypothesis draft survives tab unmount, explicit rebase and failed save without silently adopting newer research',()=>ui(async({Detail,render,button,area,edit,submit})=>{
 let t=topic(),calls=[],succeed=false;const mutate=async(path,method,data)=>{calls.push(data);return succeed?{research:{topics:[{...t,version:t.version+1,hypothesis:data.hypothesis,nextEvidence:data.nextEvidence}]}}:null;};const view=tab=>React.createElement(Detail,{topic:t,tab,setTab(){},busy:false,mutate});
 await render(view('hypothesis'));await edit('影响逻辑','Draft logic');await render(view('brief'));await render(view('hypothesis'));assert.equal(area('影响逻辑').value,'Draft logic');t={...t,version:3,hypothesis:{...t.hypothesis,logic:'Concurrent save'}};await render(view('hypothesis'));assert(button('保存交易假设').disabled);await submit();assert.equal(calls.length,0);await act(()=>button('已核对更新，保留假设草稿继续编辑').click());await submit();assert.equal(calls[0].version,3);assert.equal(area('影响逻辑').value,'Draft logic');succeed=true;await submit();await render(view('brief'));t={...t,version:4,hypothesis:{...t.hypothesis,logic:'Draft logic'}};await render(view('hypothesis'));assert.equal(area('影响逻辑').value,'Draft logic');assert(!button('保存交易假设').disabled);
}));
