import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {openStore} from '../server/store.mjs';
import {createService} from '../server/service.mjs';
import {createHandler} from '../server/index.mjs';
import {digest} from '../server/codex-research.mjs';
import {comparisonPacket,comparisonPrompt,validateComparison} from '../server/semantic-events.mjs';
import {eventComparisonSnapshot} from '../server/semantic-event-scopes.mjs';
const config={binary:'/test/codex',model:'test-model',timeoutMs:1000},at='2026-10-03T00:00:00Z';
const unknown={basis:'unknown',quote:'',quoteField:'none'};
const events=[{title:'合成甲收购乙',actor:'合成甲',action:'收购',object:'乙公司',stage:'拟议',eventTime:'未知',timeEvidence:unknown,timeRole:'unknown',quote:'合成甲拟收购乙公司。',quoteField:'body',boundaryReason:'独立交易'},{title:'合成甲终止丙项目',actor:'合成甲',action:'终止',object:'丙项目',stage:'终止',eventTime:'未知',timeEvidence:unknown,timeRole:'unknown',quote:'合成甲终止丙项目。',quoteField:'body',boundaryReason:'不同项目'}];
const body=events.map(e=>e.quote).join('');
function candidate(p,field,value){const rawOutput=JSON.stringify(value);return {status:'candidate',reviewStatus:'unreviewed',[field]:value,rawOutput,trace:{model:config.model,promptVersion:p.schema,inputHash:p.inputHash,outputHash:digest(rawOutput)}};}
function comparison(p){const side=s=>{const input=p.input[s],e=input.eventFocus||events[0];return {actor:e.actor,action:e.action,object:e.object,stage:e.stage,eventTime:'未知',timeEvidence:unknown,quote:input.eventFocus?e.quote:input.body||input.title,quoteField:input.eventFocus?e.quoteField:input.body?'body':'title'};};return {relation:p.input.left.eventFocus?.object===p.input.right.eventFocus?.object?'repeat':'unrelated',left:side('left'),right:side('right'),reason:'合成控制判断，不是质量验证',missingEvidence:['核验事实']};}
async function fixture(path=':memory:'){
 const store=openStore(path),svc=createService(store,{mode:'research',modelConfig:config,now:()=>Date.parse(at),materialEventRunner:async p=>candidate(p,'decomposition',{events,scopeNote:'合成两个事项',missingEvidence:['原公告']}),semanticRunner:async p=>candidate(p,'comparison',comparison(p))}),r=svc.research;
 const sources=[],refs=[];
 for(let i=0;i<2;i++){let t=r.create({title:`合成来源${i}`,summary:'合成两个事项'});t=r.saveMaterial(t.id,{version:t.version,title:`合成公告${i}`,sourceName:'合成',url:`https://news.acme.com/source-${i}`,body,scope:'excerpt',stance:'unverified',family:'other',step:'fact',interpretation:'核对'});const m=r.materialList(t.id).materials[0],run=svc.materialEvents.start(t.id,{version:t.version,materialId:m.id,revision:m.revision,requestId:randomUUID()});await svc.materialEvents.wait(run.id);sources.push({topic:t,material:m,runId:run.id});for(let j=0;j<2;j++){const done=svc.materialEvents.decide(t.id,run.id,{eventIndex:j,version:0,action:'create',note:'合成核对各自事项'});refs.push({kind:'event',id:done.reviews[j][0].topicId,revision:1});}}
 const batch=async inputs=>{const plan=svc.semanticBatches.preview({inputs}),b=svc.semanticBatches.create({inputs,planHash:plan.planHash,requestId:randomUUID()});for(let i=0;i<plan.pairs.length;i++){const step=svc.semanticBatches.step({assertActive(){}});assert.ok(step.runId);await svc.semanticEvents.wait(step.runId);}return b;};
 const save=(b,g)=>svc.eventClusters.save({batchId:b.id,groupId:g.id,previewHash:g.hash,clusterId:'',version:0,title:g.members[0].title,note:'合成核对同一具体事项',requestId:randomUUID()});
 return {store,svc,r,refs,sources,batch,save,async close(){await svc.close();store.close();}};
}
test('reviewed event scope freezes source, quote, provenance and time purpose without creating extra source records',async()=>{
 const f=await fixture();try{const p=comparisonPacket(f.store,{left:f.refs[0],right:f.refs[2]});assert.equal(p.schema,'event-pair-scoped-1');assert.equal(p.input.left.body,body);assert.equal(p.input.left.title,'合成公告0');assert.equal(p.input.left.eventFocus.title,events[0].title);assert.equal(p.input.left.materialId,f.sources[0].material.id);assert.equal(p.input.left.eventProvenance.runId,f.sources[0].runId);assert.equal(p.input.left.eventFocus.timeRole,'unknown');assert.equal(f.store.db.prepare('SELECT count(*) n FROM research_materials').get().n,2);assert.match(comparisonPrompt(p),/不能改选正文里更相似的另一事项/);assert.match(comparisonPrompt(p),/deadline/);assert.throws(()=>comparisonPacket(f.store,{left:{...f.refs[0],revision:2},right:f.refs[2]}));assert.throws(()=>comparisonPacket(f.store,{left:{...f.refs[0],scope:events[1]},right:f.refs[2]}));const m={kind:'material',id:f.sources[0].material.id,revision:1};assert.equal(comparisonPacket(f.store,{left:m,right:{...m,id:f.sources[1].material.id}}).schema,'event-pair-material-1');}finally{await f.close();}
});
test('quoted text from another event in the same body cannot replace the selected event anchor',async()=>{
 const f=await fixture();try{const p=comparisonPacket(f.store,{left:f.refs[0],right:f.refs[1]}),out=comparison(p);assert.equal(validateComparison(out,p).relation,'unrelated');out.left.quote=events[1].quote;assert.throws(()=>validateComparison(out,p),e=>e.code==='output');out.left.quote=events[0].quote;out.left.quoteField='title';assert.throws(()=>validateComparison(out,p),e=>e.code==='output');}finally{await f.close();}
});
test('one document can support two distinct clusters across reports without widening research bindings',async()=>{
 const f=await fixture();try{const before=f.r.list(),book=f.svc.paper.snapshot(),b=await f.batch(f.refs),p=f.svc.eventClusters.preview(b.id);assert.equal(p.groups.length,2);assert.ok(p.groups.every(g=>g.state==='ready'&&g.members.length===2));assert.equal(p.unmergedPairs.length,4);const saved=p.groups.map(g=>f.save(b,g));assert.notEqual(saved[0].id,saved[1].id);for(let i=0;i<4;i++){const groups=f.r.related(f.refs[i].id).eventClusters;assert.equal(groups.length,1);assert.equal(groups[0].id,saved[i%2].id);assert.equal(groups[0].matchedMembers.length,1);}assert.equal(f.r.related(f.sources[0].topic.id).eventClusters.length,0);assert.equal(f.store.db.prepare('SELECT count(*) n FROM event_cluster_members').get().n,4);assert.deepEqual(f.r.list(),before);assert.deepEqual(f.svc.paper.snapshot(),book);}finally{await f.close();}
});
test('accepted scoped comparisons recall only corresponding event research and survive unrelated research edits',async()=>{
 const f=await fixture();try{const a=f.svc.semanticEvents.start({left:f.refs[0],right:f.refs[2]});await f.svc.semanticEvents.wait(a.id);f.svc.semanticEvents.decide(a.id,{version:0,action:'accept',note:'核对同一交易'});const links=f.r.related(f.refs[0].id).semantic;assert.equal(links.total,1);assert.equal(links.items[0].topicId,f.refs[2].id);assert.equal(f.r.related(f.refs[1].id).semantic.total,0);assert.equal(f.r.related(f.sources[0].topic.id).semantic.total,0);const t=f.r.get(f.refs[0].id);f.r.update(t.id,{version:t.version,nextEvidence:'继续核对'});assert.equal(f.svc.semanticEvents.get(a.id).active,true);assert.equal(f.r.related(t.id).semantic.total,1);const source=f.r.get(t.id),target=f.r.get(f.refs[2].id);f.r.linkTopic(source.id,{version:source.version,topicId:target.id,targetVersion:target.version,kind:'related',active:true,note:'保存事项级关联',semanticBasis:{runId:a.id,decisionVersion:1,sourceSide:'left'}});assert.equal(f.r.related(t.id).links[0].basisStatus.current,true);const reversed=f.svc.semanticEvents.start({left:f.refs[2],right:f.refs[0]});await f.svc.semanticEvents.wait(reversed.id);assert.equal(f.svc.semanticEvents.get(reversed.id).decisionVersion,1);}finally{await f.close();}
});
test('whole-material clusters and accepted comparisons do not leak into derived event topics',async()=>{
 const f=await fixture();try{const refs=f.sources.map(s=>({kind:'material',id:s.material.id,revision:1})),b=await f.batch(refs),g=f.svc.eventClusters.preview(b.id).groups[0];assert.equal(g.canSave,true);f.save(b,g);const id=f.svc.semanticBatches.get(b.id).items[0].runId;f.svc.semanticEvents.decide(id,{version:0,action:'accept',note:'整篇材料核对'});assert.equal(f.r.related(f.sources[0].topic.id).semantic.total,1);assert.equal(f.r.related(f.sources[0].topic.id).eventClusters.length,1);for(const ref of f.refs){assert.equal(f.r.related(ref.id).semantic.total,0);assert.equal(f.r.related(ref.id).eventClusters.length,0);}}finally{await f.close();}
});
test('source correction invalidates scoped comparisons and queued plans while retaining frozen histories',async()=>{
 const f=await fixture();try{const b=await f.batch([f.refs[0],f.refs[2]]),saved=f.save(b,f.svc.eventClusters.preview(b.id).groups[0]),old=f.svc.eventClusters.get(saved.id).history;const inputs=[f.refs[1],f.refs[3]],plan=f.svc.semanticBatches.preview({inputs}),queued=f.svc.semanticBatches.create({inputs,planHash:plan.planHash,requestId:randomUUID()});const s=f.sources[0];f.r.saveMaterial(s.topic.id,{version:s.topic.version,title:s.material.title,sourceName:s.material.sourceName,url:s.material.url,body:body+'修订内容。',scope:'excerpt',stance:'unverified',family:'other',step:'fact',interpretation:'核对新版本'});assert.equal(f.svc.eventClusters.get(saved.id).health.current,false);assert.deepEqual(f.svc.eventClusters.get(saved.id).history,old);const step=f.svc.semanticBatches.step({assertActive(){}});assert.equal(step.invalidated,true);assert.equal(f.svc.semanticBatches.get(queued.id).counts.invalidated,1);assert.equal(f.svc.semanticEvents.events().items.filter(x=>!x.selectable).length,2);}finally{await f.close();}
});
test('archival invalidates comparisons without deleting decisions, scopes or clusters',async()=>{
 const f=await fixture();try{const b=await f.batch([f.refs[0],f.refs[2]]),saved=f.save(b,f.svc.eventClusters.preview(b.id).groups[0]);const t=f.r.get(f.refs[0].id);f.r.update(t.id,{version:t.version,status:'archived'});assert.equal(f.svc.eventClusters.get(saved.id).health.current,false);assert.equal(f.svc.semanticEvents.events().total,3);assert.equal(f.svc.eventClusters.get(saved.id).history.length,1);assert.equal(f.store.db.prepare('SELECT count(*) n FROM material_event_decisions').get().n,4);}finally{await f.close();}
});
test('forged event provenance, unreviewed candidates and mismatched stored output fail closed',async()=>{
 const f=await fixture();try{assert.throws(()=>eventComparisonSnapshot(f.store.db,{id:f.sources[0].topic.id,revision:1}));const ref=f.refs[0],t=f.r.get(ref.id),original=f.store.db.prepare('SELECT payload FROM research_topics WHERE id=?').get(ref.id).payload;for(const patch of [x=>x.eventExtraction.event=events[1],x=>x.eventExtraction.runId='unknown',x=>x.eventExtraction.reviewNote='forged']){const altered=structuredClone(t);patch(altered);f.store.db.prepare('UPDATE research_topics SET payload=? WHERE id=?').run(JSON.stringify(altered),ref.id);assert.throws(()=>eventComparisonSnapshot(f.store.db,ref));}f.store.db.prepare('UPDATE research_topics SET payload=? WHERE id=?').run(original,ref.id);const row=f.store.db.prepare('SELECT payload FROM material_event_runs WHERE id=?').get(f.sources[0].runId),run=JSON.parse(row.payload);run.candidate.rawOutput='{}';f.store.db.prepare('UPDATE material_event_runs SET payload=? WHERE id=?').run(JSON.stringify(run),run.id);assert.throws(()=>eventComparisonSnapshot(f.store.db,ref));}finally{await f.close();}
});
test('event picker paginates and HTTP exposes validated summaries without source bodies',async()=>{
 const f=await fixture();try{const a=f.svc.semanticEvents.events({limit:2}),b=f.svc.semanticEvents.events({limit:2,offset:2});assert.equal(a.total,4);assert.equal(new Set([...a.items,...b.items].map(x=>x.id)).size,4);assert.ok(a.items.every(x=>!('body' in x)&&x.eventFocus&&x.sourceTitle));assert.equal(f.svc.semanticEvents.events({q:'终止'}).total,2);for(const p of [{limit:51},{offset:-1},{q:'x'.repeat(201)},{unknown:1}])assert.throws(()=>f.svc.semanticEvents.events(p));const h=createHandler(f.store,f.svc);let status,result;await h({method:'GET',url:'/api/semantic-events/events?limit=2',headers:{host:'127.0.0.1:4179'}},{writeHead:s=>status=s,end:b=>result=JSON.parse(b)});assert.equal(status,200);assert.equal(result.items.length,2);}finally{await f.close();}
});
test('event identities, frozen comparisons and independent clusters survive reopening',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'scope-reopen-')),path=join(dir,'fixture.sqlite'),f=await fixture(path);let svc,store;try{const b=await f.batch(f.refs),saved=f.svc.eventClusters.preview(b.id).groups.map(g=>f.save(b,g)),before=saved.map(s=>f.svc.eventClusters.get(s.id));await f.close();store=openStore(path);svc=createService(store,{mode:'research'});assert.deepEqual(saved.map(s=>svc.eventClusters.get(s.id)),before);assert.equal(svc.semanticEvents.events().total,4);}finally{if(svc){await svc.close();store.close();}else await f.close();rmSync(dir,{recursive:true,force:true});}
});
