import test from 'node:test';import assert from 'node:assert/strict';import React,{act} from 'react';import {createServer} from 'vite';import {fileURLToPath} from 'node:url';import {JSDOM} from 'jsdom';
async function ui(run){
 const vite=await createServer({configFile:false,root:fileURLToPath(new URL('../',import.meta.url)),server:{middlewareMode:true,watch:null},appType:'custom'}),dom=new JSDOM('<div id="root"></div>',{url:'http://localhost/'}),names=['window','document','HTMLElement','fetch','IS_REACT_ACT_ENVIRONMENT'],before=new Map(names.map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));let root;dom.window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};dom.window.HTMLDialogElement.prototype.close=function(){this.open=false;};
 try{Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true});const {createRoot}=await import('react-dom/client');root=createRoot(document.getElementById('root'));const {default:Source}=await vite.ssrLoadModule('/src/major/SourceResearch.jsx'),{default:News}=await vite.ssrLoadModule('/src/major/NewsInspector.jsx');const button=t=>[...document.querySelectorAll('button')].find(x=>x.textContent===t),area=t=>[...document.querySelectorAll('label')].find(x=>x.firstChild?.textContent===t).querySelector('textarea,input,select');
 const edit=async(label,value)=>act(()=>{const e=area(label);Object.getOwnPropertyDescriptor(Object.getPrototypeOf(e),'value').set.call(e,value);e.dispatchEvent(new dom.window.Event('input',{bubbles:true}));e.dispatchEvent(new dom.window.Event('change',{bubbles:true}));});
 const respond=b=>new Response(JSON.stringify(b),{headers:{'content-type':'application/json'}});let handler=()=>({enabled:false,runs:[],materials:[],attempts:[],history:[],search:{items:[],total:0},samples:[]});globalThis.fetch=async path=>respond(await handler(path));
 await run({Source,News,setFetch:f=>{handler=f;},render:n=>act(()=>root.render(n)),button,area,edit,submit:()=>act(async()=>document.querySelector('form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true})))});
 }finally{if(root)await act(()=>root.unmount());for(const [k,d] of before)if(d)Object.defineProperty(globalThis,k,d);else delete globalThis[k];dom.window.close();await vite.close();}
}


const topic=()=>({id:crypto.randomUUID(),createdAt:'2026-10-04',title:'Synthetic research',summary:'Synthetic',version:1,status:'active',chain:[{id:'fact',title:'Fact'}],evidence:[],companies:[]});
const news=()=>({id:crypto.randomUUID(),title:'Synthetic event',revision:1,firstSeen:'2026-10-04T00:00:00Z',url:'https://example.com/synthetic',triage:{topicHints:[],reasons:[],companies:[],rulesVersion:'test'}});
test('material body and mode persist, original base blocks conflict, explicit rebase keeps text, failed save retains draft',()=>ui(async({Source,render,button,area,edit,submit,setFetch})=>{
 let t=topic(),calls=[],ok=false,savedMaterial;const view=()=>React.createElement(Source,{topic:t,busy:false,mutate:async(p,m,d)=>{calls.push({p,d});if(!ok)return null;
  const id='a'.repeat(64);savedMaterial={...d,id,revision:1,documentId:'b'.repeat(64),contentHash:'c'.repeat(64),url:'',publishedAt:null,method:'manual',availableAt:'2026-10-05T00:00:00Z',verification:'unverified'};
  const evidence={id:'material:'+id,materialId:id,materialRevision:1,claim:d.title,sourceName:d.sourceName,url:'',publishedAt:null,contentScope:d.scope,stance:d.stance,family:d.family,step:d.step,interpretation:d.interpretation,verification:'unverified'};
  return {research:{topics:[{...t,version:t.version+1,evidence:[evidence]}]}};}});
 setFetch(path=>path.endsWith('/materials/'+'a'.repeat(64))?savedMaterial:{enabled:false,runs:[],materials:[],attempts:[],history:[],search:{items:[],total:0},samples:[]});
 await render(view());await edit('材料标题','Synthetic title');await edit('来源名称','Synthetic source');await edit('为什么与这个环节有关？','Synthetic relevance');await edit('材料正文','保留正文'.repeat(20000));await act(()=>button('读取公开网页').click());await render(null);await render(view());assert.equal(button('读取公开网页').getAttribute('aria-pressed'),'true');await act(()=>button('粘贴材料').click());assert.equal(area('材料正文').value.length,80000);t={...t,version:3};await render(view());assert(button('保存材料快照').disabled);await submit();assert.equal(calls.length,0);await act(()=>button('已核对更新，保留材料草稿继续编辑').click());await submit();assert.equal(calls[0].d.version,3);assert.equal(area('材料正文').value.length,80000);ok=true;await act(async()=>button('刷新材料记录').click());await submit();assert.equal(calls.length,2);assert.equal(area('材料正文').value,'');assert.equal(area('材料标题').value,'');
}));
test('news attachment keeps distinct target drafts and rejects newer source or research until explicit reset',()=>ui(async({News,render,button,area,edit,submit})=>{
 let a=topic(),b={...topic(),title:'Second research'},n=news(),calls=[];const view=()=>React.createElement(News,{news:n,topics:[a,b],busy:false,onTarget(){},mutate:async(p,m,d)=>{calls.push(d);return {research:{topics:[{...a,version:a.version+1},b]}};}});
 await render(view());await edit('关联主题',a.id);await edit('为什么与这个环节有关？','A note');await edit('关联主题',b.id);assert.equal(area('为什么与这个环节有关？').value,'');await edit('为什么与这个环节有关？','B note');await edit('关联主题',a.id);assert.equal(area('为什么与这个环节有关？').value,'A note');await render(null);await render(view());assert.equal(area('关联主题').value,a.id);assert.equal(area('为什么与这个环节有关？').value,'A note');n={...n,revision:2};a={...a,version:4};await render(view());assert(button('加入主题证据').disabled);await submit();assert.equal(calls.length,0);await act(()=>button('丢弃新闻关联草稿并载入最新版本').click());await edit('为什么与这个环节有关？','New note');await submit();assert.equal(calls[0].version,4);assert.equal(calls[0].newsRevision,2);assert.equal(area('为什么与这个环节有关？').value,'');
}));
test('explicit news refresh exposes a source revision conflict while preserving original attachment text',()=>ui(async({News,render,button,area,edit,setFetch})=>{
 const t=topic(),n=news();setFetch(path=>path.endsWith('/screening')?{samples:[]}:{...n,revision:2,title:'Updated source'});
 await render(React.createElement(News,{news:n,topics:[t],busy:false,onTarget(){},mutate(){throw Error('must not submit');}}));await edit('关联主题',t.id);await edit('为什么与这个环节有关？','Frozen original explanation');await act(async()=>button('刷新新闻版本').click());assert.equal(document.querySelector('h1').textContent,'Updated source');assert(button('加入主题证据').disabled);assert.equal(area('为什么与这个环节有关？').value,'Frozen original explanation');
}));
