import test from 'node:test';import assert from 'node:assert/strict';
import {openStore} from '../server/store.mjs';import {createService} from '../server/service.mjs';import {digest} from '../server/codex-research.mjs';
const at='2026-10-07T00:00:00Z';
async function fixture(fn){const store=openStore(':memory:'),service=createService(store,{mode:'research',now:()=>Date.parse(at)});try{await fn({store,service,db:store.db});}finally{await service.close();store.close();}}
test('news inbox queries all archived records rather than the 500-row workspace cache, with exact total/match/page counts',()=>fixture(({store,service})=>{
 store.ingest(Array.from({length:605},(_,i)=>({id:digest(String(i)),title:'Synthetic news '+i,url:'https://example.com/'+i,publishedAt:at,publisher:'Fixture'})),at);service.research.process();assert.equal(store.news().length,500);
 const result=service.research.newsPage({q:'Synthetic',limit:'30'});assert.equal(result.newsTotal,605);assert.equal(result.total,605);assert.equal(result.items.length,30);const next=service.research.newsPage({before:String(result.nextCursor),ceiling:String(result.ceiling),limit:'30'});assert(!next.items.some(n=>result.items.some(a=>a.id===n.id)));
}));
test('news preparation filters use current model state, retaining failures and the original candidate topic',()=>fixture(({store,service,db})=>{
 const id=digest('one');store.ingest([{id,title:'Synthetic merger',url:'https://example.com/one',publishedAt:at,publisher:'Fixture'}],at);service.research.process();const topic=service.research.createFromNews({newsId:id,newsRevision:1});const item=digest('item'),run='fixture-model';
 db.prepare('INSERT INTO research_pipeline_items VALUES(?,?,?,?,?,?,?,?)').run(item,id,1,'rules','running',topic.id,run,JSON.stringify({title:'Fixture',createdAt:at}));db.prepare('INSERT INTO model_research_runs VALUES(?,?,?,?,?,?)').run(run,topic.id,'candidate',at,0,'{}');
 assert.equal(service.research.newsPage({stage:'review'}).total,1);assert.equal(service.research.newsPage({stage:'model'}).total,0);assert.equal(service.research.newsPage({stage:'active'}).total,0);db.prepare("UPDATE model_research_runs SET status='failed' WHERE id=?").run(run);assert.equal(service.research.newsPage({stage:'failed'}).total,1);assert.equal(service.research.get(topic.id).title,topic.title);db.prepare("UPDATE model_research_runs SET status='running',expires_at=? WHERE id=?").run(Date.parse(at)-1,run);assert.equal(service.research.newsPage({stage:'failed'}).total,1);db.prepare("UPDATE research_pipeline_items SET run_id=NULL,status='preparing' WHERE id=?").run(item);assert.equal(service.workbenchQueue({kind:'pipeline'}).items[0].status,'interrupted');assert.equal(service.researchPipeline.get(item).id,item);assert.equal(service.research.newsPage({stage:'failed'}).total,1);assert.throws(()=>service.research.newsPage({stage:'invalid'}));
}));
test('unified queue keeps original IDs, complete counts and bounded pagination; targeted receipt opens older records',()=>fixture(({db,service})=>{
 for(let i=0;i<63;i++)db.prepare("INSERT INTO observation_todos VALUES(?,?,'pending',1,?,?)").run(digest(String(i)),JSON.stringify({id:digest(String(i)),topicId:'fixture',title:'Todo '+i,reason:'Requires review',symbols:[]}),at,at);
 const a=service.workbenchQueue({kind:'observation'}),b=service.workbenchQueue({kind:'observation',offset:String(a.nextOffset)});assert.equal(a.total,63);assert.equal(a.items.length,20);assert(!b.items.some(x=>a.items.some(y=>y.id===x.id)));const id=digest('1');assert.equal(service.observations.page({state:'all',id}).items[0].id,id);assert.equal(service.workbenchQueue({topic:'unknown'}).total,0);
 for(const params of [{limit:101},{offset:'NaN'},{kind:'delete'},{topic:[]}])assert.throws(()=>service.workbenchQueue(params));assert.throws(()=>service.observations.page({id:'invalid'}));
}));
