import React,{useEffect,useRef,useState} from 'react';
import DataDesk from '../terminal/DataDesk';
import '../terminal/terminal.css';
import {Panel,Button,Spark,Empty,ErrorContext} from './Primitives';
import {request,time} from './api';
import TopicDetail from './TopicDetail';
import NewsInspector from './NewsInspector';
import {NewTopic,AddEvidence,CompanyForm,Rulebook,VerifyEvidence} from './ResearchForms';
import './major.css';

export default function MajorWorkbench(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[mode,setMode]=useState('topics'),[selected,setSelected]=useState('agent-cpu'),[newsId,setNewsId]=useState(null),[filter,setFilter]=useState('review'),[search,setSearch]=useState(''),[tab,setTab]=useState('evidence'),[dialog,setDialog]=useState(null),[stock,setStock]=useState('META.US');
 const [reviewEvidence,setReviewEvidence]=useState(null);
 const active=useRef(true),sequence=useRef(0),inFlight=useRef(false);
 async function load(){if(inFlight.current)return;const seq=++sequence.current;try{const result=await request('/api/data');if(active.current&&seq===sequence.current){setData(result);setError('');}}catch(e){if(active.current&&seq===sequence.current)setError(e.message);}}
 useEffect(()=>{active.current=true;void load();const interval=setInterval(load,15000);return()=>{active.current=false;sequence.current++;clearInterval(interval);};},[]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),6500);return()=>clearTimeout(timer);},[notice]);
 async function mutate(path,method,payload){if(inFlight.current)return null;inFlight.current=true;sequence.current++;setBusy(true);setError('');try{const result=await request(path,method,payload);if(active.current){setData(result);setNotice(path==='/api/watchlist'?'已加入重点关注；加入关注不会生成交易申请':'已保存到本机，旧研究版本继续保留');}return result;}catch(e){if(active.current)setError(e.message);return null;}finally{inFlight.current=false;if(active.current)setBusy(false);}}
 const research=data?.research,topics=research?.topics||[],topic=topics.find(t=>t.id===selected),inbox=research?.inbox||[],news=inbox.find(n=>n.id===newsId),watch=data?.watchlist||[],quote=(watch.find(w=>w.symbol===stock)||watch[0])?.quote;
 const visibleTopics=topics.filter(t=>(mode==='archived'?t.status==='archived':t.status==='active'));
 const filteredNews=inbox.filter(n=>(filter==='all'||n.triage.bucket===filter)&&n.title.toLowerCase().includes(search.toLowerCase()));
 const queue=topics.filter(t=>t.status==='active'&&t.researchUpdatedAt);
 const today=new Date().toLocaleDateString('en-CA');
 function choose(t){setSelected(t.id);setNewsId(null);setTab('evidence');}
 function closeData(){setDialog(null);void load();}
 return <ErrorContext.Provider value={error}><main className="major" aria-label="重大事件研究工作台"><header className="m-header"><div className="m-brand"><img src="/signal.svg" alt=""/><strong>信号猎手</strong><span>重大事件工作台</span></div><div className="m-header-actions"><Button onClick={()=>setDialog('data')}>数据源</Button><Button onClick={()=>setDialog('rules')}>规则与执行</Button><Button primary disabled={!research||busy} onClick={()=>setDialog('new')}>新建主题</Button><a href="?view=demo">演示交易 ↗</a></div></header>
 <div className="m-pipeline"><div><b>01</b><span>新闻初筛<small>{inbox.length} 条本地新闻 · 常规 {research?.counts.quiet??'—'} 条</small></span></div><div><b>02</b><span>优先核验<small>{research?.counts.review??'—'} 条候选 · 主题线索 {research?.counts.clue??'—'} 条</small></span></div><div><b>03</b><span>事件与复合主题<small>{topics.filter(t=>t.status==='active').length} 个在研 · 因果链与反证</small></span></div><div><b>04</b><span>人工确认成交<small>正式账本待建立 · 不自动下单</small></span></div></div>
 {error&&<div className="m-error" role="alert">{error}<Button onClick={load}>重试连接</Button></div>}
 <div className="m-layout"><div className="m-left"><Panel title="信号雷达" meta={data?.checks.news?.state==='error'?'RSS 更新失败，保留旧值':`最近收取 ${time(data?.checks.news?.receivedAt)}`} className="m-radar"><nav className="m-tabs" aria-label="信号视图">{[['topics','重点'],['rss','RSS 初筛'],['archived','已归档']].map(([v,l])=><button key={v} onClick={()=>{setMode(v);setNewsId(null);}} className={mode===v?'selected':''} aria-current={mode===v?'page':undefined}>{l}</button>)}</nav>
 {mode==='rss'&&<div className="m-rss-filter"><input aria-label="搜索初筛新闻" value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索标题"/><select aria-label="初筛层级" value={filter} onChange={e=>setFilter(e.target.value)}>{[['review','优先核验'],['clue','主题线索'],['quiet','常规资讯'],['all','全部']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>}
 <div className="m-radar-list">{mode==='rss'?filteredNews.length?filteredNews.map(n=><button key={n.id} onClick={()=>{setNewsId(n.id);const target=n.triage.topicHints.find(id=>topics.some(t=>t.id===id&&t.status==='active'));setSelected(target||topics.find(t=>t.status==='active')?.id);}} className={`m-radar-row ${newsId===n.id?'selected':''}`}><div><span>{n.triage.category}</span><small>{time(n.publishedAt)}</small></div><h3>{n.title}</h3><p>{n.triage.reasons[0]}</p><small>标题初筛 · 未核实</small></button>):<p className="m-padding m-muted">没有匹配的新闻。未命中规则的条目仍在常规池。</p>:visibleTopics.length?visibleTopics.map(t=><button key={t.id} onClick={()=>choose(t)} className={`m-radar-row ${selected===t.id&&!newsId?'selected':''}`}><div><span className={t.type==='cluster'?'teal':'amber'}>{t.label}</span><small>{t.origin==='retrospective-case'?'回溯案例':'用户主题'}</small></div><h3>{t.title}</h3><p>{t.summary}</p><small>{t.coverage.support} 支持 / {t.coverage.against} 反向约束 / {t.coverage.pending} 待核实{t.hypothesis.reviewAt&&t.hypothesis.reviewAt<=today?' · 到期复核':''}</small></button>):<p className="m-padding m-muted">{data?'此处暂无主题。':'正在连接本地记录…'}</p>}</div></Panel>
 <Panel title="重点关注" meta={`${watch.length} / 40`} className="m-watch" tools={<Button onClick={()=>setDialog('data')}>管理</Button>}><div className="m-watch-list">{watch.map(w=><button key={w.symbol} onClick={()=>setStock(w.symbol)} className={stock===w.symbol?'selected':''}><span><b>{w.quote?.name||w.symbol}</b><small>{w.symbol}</small></span><Spark quote={w.quote}/><span className="m-watch-price">{w.quote?.last.toFixed(2)||'—'}<small>{w.quote?.currency||'等待行情'}</small></span></button>)}</div>{quote&&<div className="m-watch-chart"><div><b>{quote.symbol}</b><span>1 分钟收盘走势</span></div><Spark quote={quote} large/><p>供应商 {quote.providerTime} · 接收 {time(quote.receivedAt)}</p><p>{data?.checks[quote.symbol]?.state==='error'?'最近更新失败；显示缓存。':quote.providerTimezone==='unverified'?'供应商时区待核验 · ':'供应商时间 UTC+8 · '}送达延迟未核定</p></div>}</Panel></div>
 {news&&mode==='rss'?<NewsInspector key={news.id} news={news} topics={topics} mutate={mutate} busy={busy} onTarget={setSelected}/>:topic?<TopicDetail key={topic.id} topic={topic} busy={busy} mutate={mutate} tab={tab} setTab={setTab} onEvidence={()=>setDialog('evidence')} onVerify={e=>{setReviewEvidence(e);setDialog('verify');}}/>:<Panel title="主题研判"><Empty title="等待研究数据">本地数据服务连接后展示事件与因果链。</Empty></Panel>}
 <div className="m-right"><Panel title="关联公司" meta="研究敞口，非买入清单" tools={<Button disabled={!topic||busy} onClick={()=>setDialog('company')}>关联</Button>} className="m-companies"><div className="m-company-list">{topic?.companies.map(c=>{const followed=watch.some(w=>w.symbol===c.symbol);return <article key={c.symbol}><div className="m-company-top"><span><b>{c.name}</b><code>{c.symbol}</code></span><Button disabled={busy||followed} onClick={async()=>{if(await mutate('/api/watchlist','POST',{symbol:c.symbol}))setStock(c.symbol);}}>{followed?'已关注':'加入关注'}</Button></div><div className="m-company-role">{c.role}</div><p>{c.note}</p>{c.url&&<a href={c.url} target="_blank" rel="noreferrer">关系依据 ↗</a>}</article>})}{topic&&!topic.companies.length&&<p className="m-padding m-muted">尚无关联公司，先确认业务关系与确切代码。</p>}</div></Panel>
 <Panel title="研究队列" meta={`${queue.length} 份已保存研究`} className="m-queue"><div className="m-queue-list">{queue.length?queue.map(t=><button key={t.id} onClick={()=>{choose(t);setTab('hypothesis');}}><b>{t.title}</b><p>v{t.version} · 已保存研究 · 未提交交易申请</p><small>{t.hypothesis.reviewAt?`复核 ${t.hypothesis.reviewAt}`:'复核日期待定'}</small></button>):<Empty title="暂无交易申请">先补证据与触发条件，<br/>再提交人工审批。</Empty>}</div><div className="m-risk-summary"><div><b>持仓风险复核</b><Button onClick={()=>setDialog('rules')}>查看门禁</Button></div><p>正式模拟账本尚未建立。退出规则可演练，实时持仓监控尚未接通。</p></div></Panel></div>
 <Panel title="模拟持仓" meta="正式账本待建立" className="m-holdings" tools={<a href="?view=demo">查看演示交易 ↗</a>}><div className="m-holdings-head"><span>标的 / 事件</span><span>获批研究版本</span><span>数量 / 可卖</span><span>成本 / 现值</span><span>收益 / 风险</span><span>下一次复核</span></div><p>尚无正式持仓记录 · 演示买卖在独立视图中，未混入研究数据</p></Panel></div>
 <footer className="m-footer"><span>本地 v0.4 · 规则初筛 · 回溯案例不代表提前发现</span><span>{busy?'正在保存…':data?'本机存储已连接':'连接中'} · 数据与研判可追溯</span></footer>
 {notice&&<div className="m-toast" role="status">{notice}<button aria-label="关闭提示" onClick={()=>setNotice('')}>×</button></div>}
 {dialog==='verify'&&topic&&reviewEvidence&&<VerifyEvidence topic={topic} evidence={reviewEvidence} busy={busy} mutate={mutate} onClose={()=>setDialog(null)}/>}
 {dialog==='data'&&<DataDesk onClose={closeData}/>}{dialog==='rules'&&<Rulebook onClose={()=>setDialog(null)}/>}{dialog==='new'&&<NewTopic onClose={()=>setDialog(null)} busy={busy} onCreate={async payload=>{const result=await mutate('/api/research','POST',payload);if(result){setSelected(result.createdTopicId);setNewsId(null);setMode('topics');setTab('evidence');setDialog(null);}}}/>}{dialog==='evidence'&&topic&&<AddEvidence topic={topic} busy={busy} mutate={mutate} onClose={()=>setDialog(null)}/>}{dialog==='company'&&topic&&<CompanyForm topic={topic} busy={busy} mutate={mutate} onClose={()=>setDialog(null)}/>}
 </main></ErrorContext.Provider>;
}
