import React,{useState} from 'react';
import useEditorDraft from './useEditorDraft';
import {Button} from './Primitives';
import {request,time} from './api';
export default function NewsReading({news,busy,mutate,onRefresh}){
 const editor=useEditorDraft({id:news.id,createdAt:news.articleFirstSeen||news.firstSeen,version:news.revision},'news-note',()=>({note:news.note||''}),v=>v&&typeof v.note==='string'),[history,setHistory]=useState(null),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const draft=editor.draft,conflict=draft.base!==news.revision;
 async function save(payload){if(busy||saving||conflict)return;setSaving(true);setError('');const submitted=draft;try{const value=await mutate(`/api/news/${news.id}`,'PATCH',payload);if(value){const latest=await request(`/api/news/${news.id}`);if(payload.note!==undefined)editor.ack(submitted,{note:latest.note||''},latest.revision);onRefresh(latest);}}catch(e){setError(e.message);}finally{setSaving(false);}}
 return <details className="news-reading"><summary>选读、阅读笔记与标题修订</summary><p>选读仅表示关注；笔记不代替已核验材料。草稿保留在本标签页。</p><div className="m-form-actions"><Button disabled={busy||saving||conflict} onClick={()=>void save({selected:!news.selected})}>{news.selected?'取消选读':'加入选读'}</Button><Button disabled={busy||saving||conflict} onClick={()=>void save({read:!news.read})}>{news.read?'标为未读':'标为已读'}</Button></div><label className="m-form">我的阅读笔记<textarea value={draft.value.note} maxLength={4000} onChange={e=>editor.change({note:e.target.value})}/></label>{conflict&&<p role="alert">标题已修订，请核对后保留笔记继续，或丢弃草稿。<Button onClick={()=>editor.change(v=>v,news.revision)}>已核对当前版本</Button></p>}<div className="m-form-actions"><Button disabled={busy||saving||conflict||!draft.dirty} onClick={()=>void save({note:draft.value.note})}>保存笔记</Button><Button disabled={busy||saving} onClick={()=>editor.reset()}>丢弃笔记草稿</Button><Button onClick={async()=>{try{setHistory(await request(`/api/news/${news.id}/revisions`));setError('');}catch(e){setError(e.message);}}}>查看标题修订</Button></div>{draft.volatile&&<p role="alert">浏览器草稿存储不可用，请及时保存。</p>}{error&&<p role="alert">{error}</p>}{history?.map(r=><p key={r.version}>v{r.version} · {time(r.receivedAt)} · {r.title}</p>)}</details>;
}
