import React,{useEffect,useState} from 'react';
import {Button} from './Primitives';
import {request,time} from './api';
import './research-materials.css';
export default function NewsLibrary({onOpen,compact=false}){
 const [q,setQ]=useState(''),[bucket,setBucket]=useState('all'),[stage,setStage]=useState('all'),[search,setSearch]=useState({q:'',bucket:'all',stage:'all'}),[pages,setPages]=useState([{}]),[page,setPage]=useState(0),[data,setData]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let active=true;setLoading(true);setError('');const params=new URLSearchParams({...search,...pages[page],limit:'30'});request(`/api/news/search?${params}`).then(r=>{if(active)setData(r);}).catch(e=>{if(active){setData(null);setError(e.message);}}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[search,pages,page]);
 return <section className={`news-library ${compact?'compact-inbox':''}`} aria-label="完整新闻库"><form className="m-form" onSubmit={e=>{e.preventDefault();setPages([{}]);setPage(0);setSearch({q,bucket,stage});}}><div className="source-search"><label>搜索全部入库新闻<input value={q} maxLength={120} onChange={e=>setQ(e.target.value)} placeholder="标题关键词，例如 acquisition"/></label><label>初筛层级<select value={bucket} onChange={e=>setBucket(e.target.value)}>{[['all','全部标题'],['review','优先研判'],['clue','主题线索'],['rumor','传闻标题'],['quiet','普通资讯 / 漏筛复核'],['pending','等待初筛']].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label>处理进度<select aria-label="新闻处理进度" value={stage} onChange={e=>setStage(e.target.value)}>{[['all','全部新闻'],['new','新增未入队'],['body','正文准备中'],['model','等待 / 生成模型'],['review','候选待复核'],['failed','失败与中断'],['active','已形成研判']].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><Button primary type="submit" disabled={loading}>检索</Button></div></form>
 {data?.screeningSamples&&<p className="screening-sample-count">当前规则留样 {data.screeningSamples.current} 条 · 历次已复核 {data.screeningSamples.reviewed} 条 · 包含普通资讯，效果尚待独立验证</p>}
 <p className="m-note">从完整本地新闻库检索，按首次入库倒序。普通资讯也可建立研究；标题分流可能漏报。新入库新闻在重新检索后纳入，筛选结果随修订变化。</p>
 {error&&<p className="m-warning" role="alert">{error}</p>}
 <div className="source-pagination"><span aria-live="polite">{loading?'正在检索…':`总入库 ${data?.newsTotal??0} 条 · 匹配 ${data?.total??0} 条 · 本页 ${data?.items.length??0} 条 · 第 ${page+1} 页`}</span><Button disabled={loading||page===0} onClick={()=>setPage(p=>p-1)}>上一页</Button><Button disabled={loading||!data?.nextCursor} onClick={()=>{setPages(p=>[...p.slice(0,page+1).map((entry,i)=>i===page?{...entry,ceiling:String(data.ceiling)}:entry),{before:String(data.nextCursor),ceiling:String(data.ceiling)}]);setPage(p=>p+1);}}>下一页</Button></div>
 <div className="source-news-list" aria-busy={loading}>{!loading&&data?.items.map(n=><button key={n.id} onClick={()=>onOpen(n)}><span>{n.triage.category} · {time(n.publishedAt)} · v{n.revision}</span><strong>{n.title}</strong><small>本版可用 {time(n.revisionFirstSeen)}{n.triage.messageStatus==='rumor'?' · 传闻':''}</small></button>)}{!loading&&data&&!data.items.length&&<p className="m-note">没有匹配新闻，可缩短关键词或切换初筛层级。</p>}</div>
 </section>;
}
