import React,{Suspense,lazy,useEffect,useRef,useState} from 'react';
import {Button} from './Primitives';
import {request,time} from './api';
import {RELATION_KINDS} from '../../shared/research-links.mjs';
import './research-materials.css';
import SemanticResearchBasis from './SemanticResearchBasis';
const EventClusters=lazy(()=>import('../integrated/EventClusters'));
export default function RelatedResearch({topic,topics,busy,mutate}){
 const [clusterId,setClusterId]=useState(null);
 const [data,setData]=useState(null),[error,setError]=useState(''),[targetId,setTargetId]=useState(''),[kind,setKind]=useState('followup'),[note,setNote]=useState(''),[base,setBase]=useState(topic.version),[targetVersion,setTargetVersion]=useState(null);
 const [basis,setBasis]=useState(null),[offset,setOffset]=useState(0),[refresh,setRefresh]=useState(0);
 const formRef=useRef(null);
 const topicVersions=topics.map(t=>`${t.id}:${t.version}`).join('|');
 useEffect(()=>{let active=true;setError('');setData(null);request(`/api/research/${topic.id}/related?semanticOffset=${offset}`).then(r=>{if(active)setData(r);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[topic.id,topic.version,topicVersions,offset,refresh]);
 const target=topics.find(t=>t.id===targetId);
 const choose=id=>{if(busy)return;setTargetId(id);setTargetVersion(topics.find(t=>t.id===id)?.version);setBasis(null);};
 const save=async(payload)=>{if(busy)return;const r=await mutate(`/api/research/${topic.id}/related`,'POST',payload);if(r){setBase(r.research.topics.find(t=>t.id===topic.id).version);setNote('');setBasis(null);setRefresh(n=>n+1);}};
 if(clusterId)return <Suspense fallback={<p>正在读取事件簇…</p>}><EventClusters initialClusterId={clusterId} onBack={()=>{setClusterId(null);setRefresh(n=>n+1);}}/></Suspense>;
 return <section className="research-materials"><h3>历史召回与多事件关联</h3><p className="m-note">相同来源、公司和标题词用于召回候选，尚不代表因果关系。确认关系并写明依据后，再判断它是同一事件进展、反证、聚合因素还是历史类比。</p>{error&&<p className="m-warning" role="alert">{error}</p>}
 <div className="source-news-list">{data?.candidates.map(c=><button key={c.topicId} disabled={busy} onClick={()=>choose(c.topicId)}><span>{c.status==='archived'?'已归档':'在研'} · v{c.version}</span><strong>{c.title}</strong><small>{c.reasons.join('；')}</small></button>)}{data&&!data.candidates.length&&<p className="m-note">规则未找到明确重合项，可核对下方已采纳比较或选择其他研究。</p>}</div>
 <section aria-label="证据所属事件簇"><h3>证据所属事件簇</h3>{data?.eventClusters?.map(c=><article className="source-item" key={c.id}><strong>{c.title} · v{c.version}</strong><p>{!c.bindingCurrent&&c.historicalVersions?.length?`本事项已由新材料事项接续；原归属保留在事件簇 v${c.historicalVersions.join("、v")} 历史中`:c.health.current&&c.bindingCurrent?"事件簇依据与本研究证据仍匹配":"事件簇或本研究证据版本需复核"} · 本研究匹配 {c.matchedMembers.length} 份材料</p><Button disabled={busy} onClick={()=>setClusterId(c.id)}>查看事件簇：{c.title}</Button></article>)}{data&&!data.eventClusters?.length&&<p className="m-note">当前证据尚未分配到活动事件簇。可从比较批次核对后建立；不会自动合并研究或增加独立证据数。</p>}</section>
 <section aria-label="已采纳比较召回"><h3>已采纳比较中的研究线索</h3><Button disabled={busy} onClick={()=>setRefresh(n=>n+1)}>刷新关联依据</Button><p className="m-note">只使用当前有效的人工采纳结果，按两侧精确证据版本寻找研究。不会自动调用模型或合并研究，也不沿关系链推导其他关联。</p>{data?.semantic?.items.map(c=><article className="source-item" key={c.id}><strong>{c.title}</strong><p>{c.status==='archived'?'已归档':'在研'} · 研究 v{c.version}</p><SemanticResearchBasis basis={c.basis}/><Button disabled={busy} onClick={()=>{choose(c.topicId);setTargetVersion(c.version);setBasis(c.basis);setKind('related');formRef.current?.scrollIntoView({block:'start'});formRef.current?.querySelector('select')?.focus({preventScroll:true});}}>用此比较核对：{c.title}</Button></article>)}{data?.semantic&&<><p>匹配 {data.semantic.total} 条研究线索 · 本页 {data.semantic.items.length} 条 · 有效比较 {data.semantic.acceptedPairs} 对</p>{!data.semantic.total&&<p className="m-note">暂无有效匹配。先在事件追踪中比较并采纳，两侧输入需分别保存在研究证据中。</p>}<div className="source-pagination"><Button disabled={busy||!offset} onClick={()=>setOffset(n=>Math.max(0,n-20))}>上一页线索</Button><Button disabled={busy||offset+20>=data.semantic.total} onClick={()=>setOffset(n=>n+20)}>下一页线索</Button></div></>}</section>
 <form ref={formRef} className="m-form" onSubmit={async e=>{e.preventDefault();await save({version:base,topicId:targetId,targetVersion,kind,note,active:true,...(basis?{semanticBasis:{runId:basis.runId,decisionVersion:basis.decisionVersion,sourceSide:basis.sourceSide}}:{})});}}><label>相关事件<select required disabled={busy} value={targetId} onChange={e=>choose(e.target.value)}><option value="">选择研究事件</option>{topics.filter(t=>t.id!==topic.id).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label>{target&&<p className="m-note">目标 v{targetVersion}：{target.hypothesis.logic}<br/><a href={`/?topic=${encodeURIComponent(target.id)}`} target="_blank" rel="noreferrer">打开目标研究 ↗</a></p>}{basis&&<div><p className="m-note">保存时将冻结此比较的人工决定和引用；研究关系仍由你另行选择。</p><SemanticResearchBasis basis={basis}/><Button type="button" disabled={busy} onClick={()=>setBasis(null)}>取消使用此比较依据</Button></div>}<label>当前事件相对于目标的关系<select disabled={busy} value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(RELATION_KINDS).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label>关系依据或撤销原因<textarea required disabled={busy} maxLength={1200} rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="变化是什么，哪些来源可证明关联，是否存在共同来源或共同原因？"/></label>{(base!==topic.version||target&&targetVersion!==target.version)&&<p className="m-warning">研究版本已变化。输入仍保留，请核对历史后重新打开此页。</p>}<Button primary type="submit" disabled={busy||!target||base!==topic.version||targetVersion!==target?.version}>保存事件关系</Button>
 <h3>已建立关系</h3>{data?.links.map(l=><div className="source-item" key={`${l.topicId}:${l.kind}`}><b>{RELATION_KINDS[l.kind]} · {l.active?(l.basisStatus?.current===false?'依据需复核':'有效'):'已撤销'}</b><p>{l.title}</p><p>{l.note}</p><small>基于目标 v{l.targetVersion} · {time(l.at)}{l.currentVersion!==l.targetVersion?` · 目标现已到 v${l.currentVersion}，需复核`:''}</small>{l.semanticBasis&&<SemanticResearchBasis basis={l.semanticBasis} status={l.basisStatus}/>} {l.active&&<Button type="button" disabled={busy||!note.trim()||base!==topic.version} onClick={()=>save({version:base,topicId:l.topicId,targetVersion:l.currentVersion,kind:l.kind,note,active:false})}>按上方原因撤销关系</Button>}</div>)}{data&&!data.links.length&&<p className="m-note">尚未建立关系。关联不会把两份来源自动算作独立证据。</p>}</form>
 {!!data?.incoming.length&&<><h3>关联到本事件的研究</h3>{data.incoming.map(l=><div className="m-note" key={`${l.topicId}:${l.kind}`}><a href={`/?topic=${encodeURIComponent(l.topicId)}`} target="_blank" rel="noreferrer">{l.title}</a> · {RELATION_KINDS[l.kind]}<p>{l.note}</p>{l.basisStatus?.current===false&&<p className="m-warning">原比较依据已变化，需要复核。</p>}</div>)}</>}
 </section>;
}
