import {readFileSync,writeFileSync} from 'node:fs';
import {RULEBOOK,RULE_FIELDS} from '../shared/rulebook.mjs';
const escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const inline=s=>escape(s).replace(/\[([^\]]+)\]\((https:\/\/[^)]+)\)/g,'<a href="$2" target="_blank" rel="noreferrer">$1 ↗</a>');
const lines=readFileSync(new URL('../../docs/MAJOR-EVENT-SYSTEM.md',import.meta.url),'utf8').split('\n');
const sections=[],parts=[];let table=false,list=false,index=0;
const close=()=>{if(table){parts.push('</tbody></table></div>');table=false;}if(list){parts.push('</ol>');list=false;}};
for(const line of lines){
 if(line.startsWith('|')){if(!table){parts.push('<div class="table-wrap"><table><tbody>');table=true;}if(/^\|[\s:|-]+\|$/.test(line))continue;parts.push('<tr>'+line.slice(1,-1).split('|').map(v=>`<td>${inline(v.trim())}</td>`).join('')+'</tr>');continue;}
 if(/^\d+\. /.test(line)){if(table)close();if(!list){parts.push('<ol>');list=true;}parts.push(`<li>${inline(line.replace(/^\d+\. /,''))}</li>`);continue;}
 close();if(!line.trim())continue;
 if(line.startsWith('# ')){parts.push(`<h1>${inline(line.slice(2))}</h1><p class="lead">重大事件发现 · 多因素聚合 · 历史追踪 · 人工批准 · 持仓复核</p>`);continue;}
 if(line.startsWith('## ')){index++;sections.push({id:`section-${index}`,title:line.slice(3)});parts.push(`<h2 id="section-${index}">${inline(line.slice(3))}</h2>`);if(index===11)parts.push(`<div class="rules">${RULEBOOK.map(r=>`<article><div><code>${r.id}</code><h3>${escape(r.title)}</h3><span>${escape(r.state)}</span></div><p>${escape(r.description)}</p><dl>${RULE_FIELDS.map(([key,label])=>`<dt>${label}</dt><dd>${escape(r.specification[key])}</dd>`).join('')}</dl></article>`).join('')}</div>`);continue;}
 parts.push(`<p>${inline(line)}</p>`);
}close();
const html=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>信号猎手 · Signal Hunter · 设计说明</title><style>
:root{color-scheme:dark;font:16px/1.85 -apple-system,BlinkMacSystemFont,'PingFang SC',sans-serif;color:#dbe3ef;background:#0b111a}*{box-sizing:border-box}body{margin:0}a{color:#71d6cc;text-decoration:none}a:hover{text-decoration:underline}aside{position:fixed;inset:0 auto 0 0;width:258px;background:#111a26;border-right:1px solid #263347;padding:30px 21px;overflow:auto}aside>b{display:block;font-size:18px;margin-bottom:20px}aside a{display:block;color:#a6b9cd;font-size:12px;line-height:1.7;padding:7px 0}aside a:first-of-type{color:#71d6cc;margin-bottom:15px}main{max-width:1320px;margin-left:258px;padding:52px 58px 100px}h1{font-size:32px;line-height:1.45;letter-spacing:-.5px;margin:0 0 15px}h2{font-size:24px;line-height:1.5;margin:62px 0 22px;border-top:1px solid #263347;padding-top:30px;scroll-margin-top:20px}h3{font-size:16px;margin:0}p{margin:18px 0;color:#c0ccdb}.lead{color:#71d6cc;font-size:14px;margin-bottom:35px}.table-wrap{overflow:auto;margin:26px 0}table{width:100%;border-collapse:collapse;font-size:13px;min-width:580px}td{padding:12px 13px;border:1px solid #293b4d;vertical-align:top}tr:first-child{background:#152534;color:#e5eef8;font-weight:600}ol{padding-left:25px}li{margin:14px 0;color:#c0ccdb}.rules{display:grid;grid-template-columns:1fr 1fr;gap:12px}.rules article{padding:16px;border:1px solid #263347;border-radius:4px;background:#111a26}.rules article>div{display:flex;align-items:center;gap:9px;flex-wrap:wrap}.rules code{color:#71d6cc;font-size:12px}.rules span{font-size:11px;color:#e8b567;margin-left:auto}.rules dl{font-size:12px;line-height:1.8;margin:14px 0 0}.rules dt{color:#71d6cc;margin:12px 0 3px}.rules dd{margin:0;color:#b0c0d0}.rules p{font-size:13px;line-height:1.85;margin:10px 0 0}footer{border-top:1px solid #263347;margin-top:60px;padding-top:20px;font-size:12px;color:#96a4b8}@media(max-width:980px){aside{width:210px;padding:22px 15px}main{margin-left:210px;padding:35px 28px}.rules{grid-template-columns:1fr}}@media(max-width:640px){aside{position:static;width:auto;border-right:0;border-bottom:1px solid #263347;padding:20px}aside nav{display:none}aside b{margin:0}aside a:first-of-type{margin:8px 0 0}main{margin:0;padding:28px 20px 60px}h1{font-size:26px}h2{font-size:21px;margin-top:42px}p{font-size:15px}li{font-size:15px}.rules{grid-template-columns:1fr}}@media print{aside{display:none}main{margin:0;padding:20px}body{background:white;color:black}p,li{color:#222}a{color:#146d65}.rules article{background:white;break-inside:avoid}}
</style></head><body><aside><b>信号猎手</b><a href="/">返回重大事件工作台</a><nav>${sections.map(s=>`<a href="#${s.id}">${escape(s.title)}</a>`).join('')}</nav></aside><main>${parts.join('\n')}<footer>设计 v0.7 · 本地研究候选 · 生成源 docs/MAJOR-EVENT-SYSTEM.md 与 shared/rulebook.mjs · 代码验证不等于策略收益有效性</footer></main></body></html>`;
writeFileSync(new URL('../public/major-event-design.html',import.meta.url),html);
console.log('Built standalone major-event-design.html');
