import React,{useState,useEffect,useRef} from 'react';
import {byId,stocks,money,pct} from '../data';
import {increments,researchFor} from './fixtures';
import {Pane,Urgency,TButton,MiniTrend} from './Primitives';

export function EventFeed({selected,onSelect,seen,onSeen}){
 const [urgentOnly,setUrgentOnly]=useState(false);const feed=increments.filter(e=>!urgentOnly||e.urgency==='urgent');
 return <Pane title="事件增量" meta={`${increments.filter(e=>!seen.includes(e.id)).length} 未读`} className="events-pane" tools={<button className={`text-control ${urgentOnly?'active':''}`} aria-pressed={urgentOnly} onClick={()=>setUrgentOnly(!urgentOnly)}>只看紧急</button>}><div className="feed-label"><span>按接收顺序</span><span>虚构场景 · 09/24</span></div><div className="pane-scroll event-feed">{feed.map(e=><article className={`terminal-event-item ${selected===e.stockId?'selected':''}`} key={e.id}><button className="event-select" aria-label={`查看事件：${e.title}`} onClick={()=>onSelect(e.stockId)}><div className="terminal-event-meta"><time>{e.time}</time><span className={`event-kind ${e.kind==='反证'?'loss':''}`}>{e.kind}</span><Urgency level={e.urgency}/><span className="feed-symbol">{byId[e.stockId].symbol}</span>{!seen.includes(e.id)&&<i className="unread-dot" aria-label="未读"/>}</div><h3>{e.title}</h3><p>{e.after}</p><div className="event-symbol"><span>{byId[e.stockId].symbol}</span><span>{byId[e.stockId].name}</span></div></button><button className="event-read" aria-label={`${seen.includes(e.id)?'标为未读':'标为已读'}：${e.title}`} onClick={()=>onSeen(e.id)}>{seen.includes(e.id)?'已读':'标记已读'}</button></article>)}</div><footer className="pane-foot">增量按事件归并，保留研判修订</footer></Pane>;
}
export function WatchPanel({selected,onSelect}){
 const [market,setMarket]=useState('全部');const listRef=useRef(null);const order=['xiaomi','nvda','msft','tencent','catl','baba','maotai','zijin'];const list=order.map(id=>byId[id]).filter(s=>market==='全部'||s.market===market);useEffect(()=>{const list=listRef.current,row=list?.querySelector(`[data-stock="${selected}"]`);if(!row||!matchMedia('(min-width:1001px)').matches)return;const top=row.offsetTop;if(top<list.scrollTop)list.scrollTop=top;else if(top+row.offsetHeight>list.scrollTop+list.clientHeight)list.scrollTop=top+row.offsetHeight-list.clientHeight;},[selected,market]);
 return <Pane title="重点关注" meta={`${list.length} 标的`} className="watch-pane" tools={<select aria-label="关注市场" value={market} onChange={e=>setMarket(e.target.value)}>{['全部','A股','港股','美股'].map(m=><option key={m}>{m}</option>)}</select>}><div className="watch-head"><span>股票 / 市场</span><span>示例价</span><span>近月变化</span><span>走势</span></div><div className="pane-scroll watch-rows" ref={listRef}>{list.map(s=><button key={s.id} data-stock={s.id} className={`watch-row ${selected===s.id?'selected':''}`} aria-label={`关注 ${s.name}`} onClick={()=>onSelect(s.id)}><span><b>{s.name}</b><small>{s.symbol} · {s.market}</small></span><span className="num">{s.price.toFixed(2)}</span><span className={`num ${s.trend.at(-1)<0?'loss':'profit'}`}>{pct(s.trend.at(-1))}</span><MiniTrend stock={s}/></button>)}</div></Pane>;
}
export function ResearchPanel({stock,state,onSubmit,onInspect}){
 const e=researchFor(stock.id),held=state.positions.find(p=>p.stockId===stock.id),pending=state.applications.find(a=>a.stockId===stock.id&&a.status==='pending');
 return <Pane title="事件研判" meta={e.version} className="research-pane" tools={<button className="text-control" onClick={onInspect}>依据与反证</button>}><div className="research-body pane-scroll"><div className="research-verdict"><Urgency level={e.urgency}/><strong>{e.impact}</strong></div><dl className="research-lines"><div><dt>本次变化</dt><dd><span className="old-thesis">{e.before}</span><span>{e.after}</span></dd></div><div className="research-plan"><div><dt>参考买点 · {stock.currency}</dt><dd className="num">{stock.range[0].toFixed(2)}–{stock.range[1].toFixed(2)}</dd></div><div><dt>持有计划{held&&` · 已持有 ${held.days} 日`}</dt><dd><b>{stock.hold[0]}–{stock.hold[1]} 个交易日</b></dd></div></div><div className="research-risk"><dt>退出 / 失效</dt><dd title={stock.risk}>{stock.risk}</dd></div></dl></div><div className="research-actions">{pending?<><span className="muted">已有待确认申请，尚未执行</span><TButton tone="accent" onClick={()=>onSubmit(stock.id,pending.type)}>查看申请</TButton></>:<><TButton tone="accent-outline" onClick={()=>onSubmit(stock.id,'buy')}>{held?'提交增仓申请':'提交建仓申请'}</TButton>{held&&<TButton tone="danger-outline" onClick={()=>onSubmit(stock.id,'sell')}>提交减仓申请</TButton>}</>}</div></Pane>;
}
