import React,{useEffect,useRef,useState} from 'react';
import {Button,Modal} from '../major/Primitives';
import {request,time} from '../major/api';
import NewsCoverage from '../integrated/NewsCoverage';
export default function DataDesk({onClose,data:provided,mutate:externalMutate,busy:externalBusy=false}){
 const [local,setLocal]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[symbol,setSymbol]=useState(''),[notice,setNotice]=useState('');const flight=useRef(false),alive=useRef(true),data=provided||local,locked=busy||externalBusy;
 useEffect(()=>{alive.current=true;if(!provided)request('/api/data').then(d=>{if(alive.current)setLocal(d);}).catch(e=>{if(alive.current)setError(e.message);});return()=>{alive.current=false;};},[]);
 async function mutate(path,method,payload){if(flight.current||locked)return null;flight.current=true;setBusy(true);setError('');try{const value=externalMutate?await externalMutate(path,method,payload):await request(path,method,payload);if(alive.current&&value){setLocal(value);setNotice('已保存；历史与原始新闻保留');}return value;}catch(e){if(alive.current)setError(e.message);return null;}finally{flight.current=false;if(alive.current)setBusy(false);}}
 return <Modal title="数据来源与关注证券" onClose={onClose}><section className="data-source-content"><p className="m-note">新闻阅读、选读和笔记统一在工作台的新闻收件箱中完成；这里设置采集来源与关注证券。分钟行情在公司研究中查看。</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{data?<><p>最近新闻检查 {time(data.checks.news?.attemptedAt)} · {data.runtime.offline?'演示模式关闭外部请求':'按配置独立采集，来源失败保留已有记录'}</p><NewsCoverage data={data} mutate={mutate} busy={locked}/><section className="watch-manager" aria-label="关注证券管理"><h3>关注证券 · {data.watchlist.length}/40</h3><form className="m-form-row" onSubmit={e=>{e.preventDefault();void mutate('/api/watchlist','POST',{symbol});}}><input aria-label="添加关注股票代码" required value={symbol} onChange={e=>setSymbol(e.target.value)} placeholder="600519.SH / 00700.HK / AAPL.US"/><Button type="submit" disabled={locked}>添加关注</Button></form><div className="data-watchlist">{data.watchlist.map(w=><div key={w.symbol}><span>{w.quote?.name||w.symbol} · {w.symbol}</span><Button aria-label={`取消关注 ${w.symbol}`} disabled={locked} onClick={()=>void mutate('/api/watchlist','DELETE',{symbol:w.symbol})}>取消关注</Button></div>)}</div></section></>:<p>正在读取设置…</p>}</section></Modal>;
}
